import "server-only";
import { createHash, randomBytes, randomUUID } from "crypto";
import { resolvePrivateReflectionProviders } from "@/lib/server/privateAiProviderResolver";

const PROJECT_ID = "yorisou";
export const ACTIVE_VISIBILITIES = ["PRIVATE", "INVITE_ONLY", "ANONYMOUS_SHARED", "SIMILAR_STATE_ONLY"] as const;
export type ExperienceVisibility = typeof ACTIVE_VISIBILITIES[number];
export type ExperienceInput = { stateContext: string; situation: string; actionTried: string; perceivedOutcome: string; limitations: string; mayFit: string; mayNotFit: string; visibility: ExperienceVisibility; sourceSavedResultId?: string | null; previewConfirmed?: boolean; aiAssistanceStatus?: "none" | "accepted" | "rejected" };
type CardRow = Record<string, unknown> & { id: string; owner_account_id: string; visibility: ExperienceVisibility; visibility_version: number };

function config() { const url=process.env.SUPABASE_URL?.trim(),key=process.env.SUPABASE_SERVICE_ROLE_KEY?.trim(); if(!url||!key) throw new Error("experience_store_not_configured"); return {url:url.replace(/\/$/,""),key}; }
async function request(path:string,init:RequestInit={}) { const {url,key}=config(); const response=await fetch(`${url}/rest/v1/${path}`,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",...(init.headers||{})},cache:"no-store"}); if(!response.ok) throw new Error(`experience_store_failed:${response.status}`); return response; }
function clean(value:unknown,max:number) { return typeof value==="string"&&value.trim().length>0&&value.trim().length<=max?value.trim():null; }
export function trustFlags(input:ExperienceInput) { const combined=Object.values(input).filter(v=>typeof v==="string").join(" "); const flags:string[]=[]; if(/\b[\w.%+-]+@[\w.-]+\.[A-Za-z]{2,}\b/.test(combined))flags.push("email"); if(/(?:\+?\d[\d -]{8,}\d)/.test(combined))flags.push("phone"); if(/(?<!\d)(?:〒\s*\d{3}-?\d{4}|\d{3}-\d{4})(?![-\d])/.test(combined))flags.push("postal_code"); if(/(?:診断|治療|必ず治る|絶対に効く)/.test(combined))flags.push("clinical_or_absolute_claim"); return flags; }
function payload(input:ExperienceInput) { const values={state_context:clean(input.stateContext,1200),situation:clean(input.situation,3000),action_tried:clean(input.actionTried,3000),perceived_outcome:clean(input.perceivedOutcome,3000),limitations:clean(input.limitations,2000),may_fit:clean(input.mayFit,1200),may_not_fit:clean(input.mayNotFit,1200)}; if(Object.values(values).some(v=>!v)||!ACTIVE_VISIBILITIES.includes(input.visibility))throw new Error("invalid_experience_card"); const flags=trustFlags(input),shared=input.visibility!=="PRIVATE"; if(shared&&!input.previewConfirmed)throw new Error("preview_confirmation_required"); if(shared&&flags.some(f=>f!=="clinical_or_absolute_claim"))throw new Error("identifying_detail_detected"); const now=new Date().toISOString(); return {...values,source_saved_result_id:input.sourceSavedResultId||null,visibility:input.visibility,consented_at:shared?now:null,searchable:shared&&input.visibility!=="INVITE_ONLY",audience_rule:input.visibility==="INVITE_ONLY"?"invite_token":input.visibility==="SIMILAR_STATE_ONLY"?"similar_state_only":shared?"anonymous_shared":"owner_only",moderation_status:shared?"published":"draft",provenance:input.aiAssistanceStatus==="accepted"?"ai_organized":"user_authored",ai_assistance_status:input.aiAssistanceStatus||"none",preview_confirmed_at:input.previewConfirmed?now:null,published_at:shared?now:null}; }
async function validateSource(owner:string,id?:string|null){if(!id)return;const rows=await (await request(`yorisou_test_results?select=id&id=eq.${encodeURIComponent(id)}&owner_account_id=eq.${encodeURIComponent(owner)}&deleted_at=is.null&limit=1`)).json() as Array<{id:string}>;if(!rows[0])throw new Error("invalid_saved_result_source");}
async function sharedCard(owner:string,id:string){return ((await (await request(`yorisou_experience_cards?select=id,owner_account_id,visibility,moderation_status&id=eq.${encodeURIComponent(id)}&owner_account_id=neq.${encodeURIComponent(owner)}&visibility=in.(ANONYMOUS_SHARED,SIMILAR_STATE_ONLY)&moderation_status=eq.published&searchable=eq.true&withdrawn_at=is.null&deleted_at=is.null&limit=1`)).json()) as CardRow[])[0]||null;}
async function event(owner:string,type:string,id?:string,metadata:Record<string,unknown>={}) { await request("yorisou_experience_events",{method:"POST",body:JSON.stringify({project_id:PROJECT_ID,experience_id:id||null,actor_account_id:owner,event_type:type,metadata})}); }
async function revision(owner:string,row:CardRow,number:number) { await request("yorisou_experience_revisions",{method:"POST",body:JSON.stringify({project_id:PROJECT_ID,experience_id:row.id,owner_account_id:owner,revision_number:number,provenance:row.provenance,content:row})}); }
export async function createExperience(owner:string,input:ExperienceInput) { await validateSource(owner,input.sourceSavedResultId);const body=payload(input),flags=trustFlags(input);if(flags.includes("clinical_or_absolute_claim")){body.moderation_status="limited";body.searchable=false;} const row=((await (await request("yorisou_experience_cards",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({project_id:PROJECT_ID,owner_account_id:owner,...body})})).json()) as CardRow[])[0]; if(!row)throw new Error("experience_create_failed"); await revision(owner,row,1); if(input.visibility!=="PRIVATE")await Promise.all([request("yorisou_experience_consents",{method:"POST",body:JSON.stringify({project_id:PROJECT_ID,experience_id:row.id,owner_account_id:owner,visibility:input.visibility})}),request("yorisou_experience_visibility_events",{method:"POST",body:JSON.stringify({project_id:PROJECT_ID,experience_id:row.id,owner_account_id:owner,to_visibility:input.visibility})})]); await event(owner,input.visibility==="PRIVATE"?"draft_created":"published",row.id,{visibility:input.visibility,trust_flags:flags}); return row; }
export async function ownerCard(owner:string,id:string) { return ((await (await request(`yorisou_experience_cards?select=*&id=eq.${encodeURIComponent(id)}&owner_account_id=eq.${encodeURIComponent(owner)}&deleted_at=is.null&limit=1`)).json()) as CardRow[])[0]||null; }
export async function listOwnerCards(owner:string) { return await (await request(`yorisou_experience_cards?select=*&owner_account_id=eq.${encodeURIComponent(owner)}&deleted_at=is.null&order=updated_at.desc&limit=50`)).json() as CardRow[]; }
export async function updateExperience(owner:string,id:string,input:ExperienceInput) { const current=await ownerCard(owner,id); if(!current)throw new Error("experience_not_found");await validateSource(owner,input.sourceSavedResultId); const body=payload(input),version=Number(current.visibility_version)+1;if(["limited","removed"].includes(String(current.moderation_status))){body.moderation_status=current.moderation_status as "limited";body.searchable=false;} const row=((await (await request(`yorisou_experience_cards?id=eq.${id}&owner_account_id=eq.${encodeURIComponent(owner)}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({...body,visibility_version:version,last_visibility_change_at:new Date().toISOString(),updated_at:new Date().toISOString()})})).json()) as CardRow[])[0]; if(!row)throw new Error("experience_update_failed"); await revision(owner,row,version); if(current.visibility!==input.visibility){await Promise.all([request("yorisou_experience_consents",{method:"POST",body:JSON.stringify({project_id:PROJECT_ID,experience_id:id,owner_account_id:owner,visibility:input.visibility})}),request("yorisou_experience_visibility_events",{method:"POST",body:JSON.stringify({project_id:PROJECT_ID,experience_id:id,owner_account_id:owner,from_visibility:current.visibility,to_visibility:input.visibility})})]);} await event(owner,"draft_updated",id,{visibility:input.visibility}); return row; }
export async function withdrawExperience(owner:string,id:string,deleted=false) { if(!await ownerCard(owner,id))throw new Error("experience_not_found"); const now=new Date().toISOString(); await request(`yorisou_experience_cards?id=eq.${id}&owner_account_id=eq.${encodeURIComponent(owner)}`,{method:"PATCH",body:JSON.stringify(deleted?{deleted_at:now,withdrawn_at:now,searchable:false}:{withdrawn_at:now,searchable:false})}); await event(owner,deleted?"deleted":"withdrawn",id); }
export async function createInvite(owner:string,id:string) { const card=await ownerCard(owner,id); if(!card||card.visibility!=="INVITE_ONLY")throw new Error("invite_not_available"); const token=randomBytes(24).toString("base64url"),tokenHash=createHash("sha256").update(token).digest("hex"),expires=new Date(Date.now()+7*86400000).toISOString(); await request("yorisou_experience_invites",{method:"POST",body:JSON.stringify({project_id:PROJECT_ID,experience_id:id,owner_account_id:owner,token_hash:tokenHash,expires_at:expires})}); return {token,expiresAt:expires}; }
export async function invitedCard(token:string) { const hash=createHash("sha256").update(token).digest("hex"); const invite=((await (await request(`yorisou_experience_invites?select=experience_id&token_hash=eq.${hash}&revoked_at=is.null&expires_at=gt.${encodeURIComponent(new Date().toISOString())}&limit=1`)).json()) as Array<{experience_id:string}>)[0]; if(!invite)return null; const row=((await (await request(`yorisou_experience_cards?select=id,state_context,situation,action_tried,perceived_outcome,limitations,may_fit,may_not_fit,visibility,provenance,ai_assistance_status,published_at&id=eq.${invite.experience_id}&visibility=eq.INVITE_ONLY&moderation_status=eq.published&withdrawn_at=is.null&deleted_at=is.null&limit=1`)).json()) as CardRow[])[0]; return row||null; }
function stateTokens(value:string){const normalized=value.replace(/\s+/g,"").toLowerCase();return new Set(Array.from({length:Math.max(0,normalized.length-1)},(_,index)=>normalized.slice(index,index+2)));}
export async function discoverExperiences(owner:string) { const [rows,blocks,ownStates]=await Promise.all([request(`yorisou_experience_cards?select=id,owner_account_id,state_context,situation,action_tried,perceived_outcome,limitations,may_fit,may_not_fit,visibility,provenance,ai_assistance_status,published_at&visibility=in.(ANONYMOUS_SHARED,SIMILAR_STATE_ONLY)&moderation_status=eq.published&searchable=eq.true&withdrawn_at=is.null&deleted_at=is.null&owner_account_id=neq.${encodeURIComponent(owner)}&order=published_at.desc&limit=20`).then(r=>r.json()) as Promise<CardRow[]>,request(`yorisou_experience_blocks?select=blocked_owner_account_id&blocker_account_id=eq.${encodeURIComponent(owner)}`).then(r=>r.json()) as Promise<Array<{blocked_owner_account_id:string}>>,request(`yorisou_experience_cards?select=state_context&owner_account_id=eq.${encodeURIComponent(owner)}&deleted_at=is.null&limit=20`).then(r=>r.json()) as Promise<Array<{state_context:string}>>]); const blocked=new Set(blocks.map(x=>x.blocked_owner_account_id)),viewerTokens=new Set(ownStates.flatMap(item=>[...stateTokens(item.state_context)])); return rows.filter(row=>!blocked.has(row.owner_account_id)&&(row.visibility!=="SIMILAR_STATE_ONLY"||[...stateTokens(String(row.state_context))].some(token=>viewerTokens.has(token)))).map(({owner_account_id:hiddenOwner,...safe})=>{void hiddenOwner;return {...safe,why_shown:safe.visibility==="SIMILAR_STATE_ONLY"?"あなたが自分で書いた関心と一部重なる体験として、限定的に表示されています。":"最近共有された匿名の体験です。"};}); }
export async function interact(owner:string,id:string,action:string,idempotencyKey:string) { if(!await sharedCard(owner,id))throw new Error("experience_not_available");await request("rpc/record_yorisou_experience_interaction",{method:"POST",body:JSON.stringify({p_experience_id:id,p_actor_account_id:owner,p_action:action,p_idempotency_key:idempotencyKey})}); await event(owner,"interaction",id,{action}); }
export async function reportExperience(owner:string,id:string,reason:string,note?:string) { if(!["unsafe","misleading","privacy","other"].includes(reason)||note&&note.length>1000)throw new Error("invalid_report");if(!await sharedCard(owner,id))throw new Error("experience_not_available"); await request("yorisou_experience_reports",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({project_id:PROJECT_ID,experience_id:id,reporter_account_id:owner,reason,note:note||null})});if(["unsafe","privacy"].includes(reason))await request(`yorisou_experience_cards?id=eq.${id}`,{method:"PATCH",body:JSON.stringify({moderation_status:"limited",searchable:false})}); await event(owner,"reported",id,{reason}); }
export async function blockExperienceOwner(owner:string,id:string) { const row=await sharedCard(owner,id); if(!row)throw new Error("invalid_block"); await request("yorisou_experience_blocks",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({project_id:PROJECT_ID,blocker_account_id:owner,blocked_owner_account_id:row.owner_account_id})}); await event(owner,"blocked",id); }
export async function structureExperience(owner:string,input:ExperienceInput) { const flags=trustFlags(input); const routes=resolvePrivateReflectionProviders(); if(!routes.length)throw new Error("experience_provider_unavailable"); const prompt=`YORISOUの体験カードを、事実を追加せず匿名化して日本語JSONに整理してください。診断や断定は禁止です。入力:${JSON.stringify({state_context:input.stateContext,situation:input.situation,action_tried:input.actionTried,perceived_outcome:input.perceivedOutcome,limitations:input.limitations,may_fit:input.mayFit,may_not_fit:input.mayNotFit})}\n出力:{"state_context":"","situation":"","action_tried":"","perceived_outcome":"","limitations":"","may_fit":"","may_not_fit":"","deidentification_notes":[],"safety_flags":[]}`; for(const route of routes){try{const response=await fetch(route.endpoint,{method:"POST",headers:route.headers,body:JSON.stringify(route.body(prompt)),signal:AbortSignal.timeout(20000)});if(!response.ok)continue;const parsed=route.parse(await response.json());if(!parsed.content)continue;const value=JSON.parse(parsed.content) as Record<string,unknown>; const structured={stateContext:clean(value.state_context,1200),situation:clean(value.situation,3000),actionTried:clean(value.action_tried,3000),perceivedOutcome:clean(value.perceived_outcome,3000),limitations:clean(value.limitations,2000),mayFit:clean(value.may_fit,1200),mayNotFit:clean(value.may_not_fit,1200),deidentificationNotes:Array.isArray(value.deidentification_notes)?value.deidentification_notes.slice(0,10):[],safetyFlags:[...flags,...(Array.isArray(value.safety_flags)?value.safety_flags.slice(0,10):[])]}; if(Object.values(structured).slice(0,7).some(v=>!v))continue; await event(owner,"ai_structured",undefined,{provider:route.provider,model:route.model}); return structured;}catch{continue;}} throw new Error("experience_structuring_failed"); }
export async function moderationQueue() { return await (await request("yorisou_experience_cards?select=*&or=(moderation_status.eq.limited,moderation_status.eq.published)&order=updated_at.desc&limit=100")).json() as CardRow[]; }
export async function moderateExperience(admin:string,id:string,action:"limit"|"remove"|"restore",reason:string) { if(!clean(reason,1000))throw new Error("invalid_moderation");const row=((await (await request(`yorisou_experience_cards?select=visibility&id=eq.${id}&limit=1`)).json()) as Array<{visibility:string}>)[0];if(!row)throw new Error("experience_not_found"); const status=action==="limit"?"limited":action==="remove"?"removed":"published",searchable=action==="restore"&&["ANONYMOUS_SHARED","SIMILAR_STATE_ONLY"].includes(row.visibility); await request(`yorisou_experience_cards?id=eq.${id}`,{method:"PATCH",body:JSON.stringify({moderation_status:status,searchable})}); await request("yorisou_experience_moderation_events",{method:"POST",body:JSON.stringify({project_id:PROJECT_ID,experience_id:id,actor_account_id:admin,action,reason})}); await event(admin,"moderated",id,{action}); }
export const newIdempotencyKey=()=>randomUUID();
