import "server-only";
import { randomUUID } from "crypto";
const PROJECT_ID="yorisou";
type Row=Record<string,unknown>;
function cfg(){const url=process.env.SUPABASE_URL?.replace(/\/$/,""),key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("recommendation_store_not_configured");return{url,key};}
async function req(path:string,init:RequestInit={}){const{url,key}=cfg();const r=await fetch(`${url}/rest/v1/${path}`,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",...(init.headers||{})},cache:"no-store"});if(!r.ok)throw new Error(`recommendation_store_failed:${r.status}`);return r;}
const event=async(owner:string,type:string,set?:string,item?:string,metadata:Row={})=>req("yorisou_recommendation_events",{method:"POST",body:JSON.stringify({project_id:PROJECT_ID,owner_account_id:owner,recommendation_set_id:set||null,recommendation_item_id:item||null,event_type:type,metadata})});
export type RecommendationRequest={stateTags?:string[];source?:"private_state"|"saved_result"|"reflection"|"experience_card"|"web_return";privateNote?:string;area?:string};
function cleanTags(input:unknown){return Array.isArray(input)?input.filter((x):x is string=>typeof x==="string"&&x.length>0&&x.length<=80).slice(0,8):[];}
function safeRequest(input:RecommendationRequest){const tags=cleanTags(input.stateTags);if(input.privateNote)throw new Error("private_note_requires_explicit_selection_route");if(input.area&&input.area.length>80)throw new Error("invalid_broad_area");return{tags,source:input.source||"private_state",area:input.area||null};}
function reason(tags:string[],type:string){const tag=tags[0]||"今の状態";return type==="experience_card"?`今の状態で見えている「${tag}」に近い、匿名で共有された体験として表示しています。`:`今の状態で見えている「${tag}」に近い、小さく試せる選択肢として表示しています。`;}
export async function createRecommendationSet(owner:string,input:RecommendationRequest,requestKey:string){if(!/^[A-Za-z0-9._:-]{1,200}$/.test(owner)||requestKey.length<16||requestKey.length>200)throw new Error("invalid_recommendation_request");const context=safeRequest(input);const existing=((await (await req(`yorisou_recommendation_sets?select=id&owner_account_id=eq.${encodeURIComponent(owner)}&request_key=eq.${encodeURIComponent(requestKey)}&limit=1`)).json())as Row[])[0];if(existing)return getRecommendationSet(owner,String(existing.id));await event(owner,"recommendation_requested",undefined,undefined,{source:context.source,tags:context.tags});const resources=(await (await req("yorisou_resources?select=*&lifecycle_status=eq.active&verification_status=in.(editorial_seed,url_checked,metadata_checked,reviewed)&commercial_status=in.(yorisou_owned,public_resource,organic_external)&or=(expires_at.is.null,expires_at.gt.now())&order=last_verified_at.desc&limit=5")).json())as Row[];const cards=(await (await req(`yorisou_experience_cards?select=id,state_context,visibility,provenance&visibility=in.(ANONYMOUS_SHARED,SIMILAR_STATE_ONLY)&moderation_status=eq.published&searchable=eq.true&withdrawn_at=is.null&deleted_at=is.null&owner_account_id=neq.${encodeURIComponent(owner)}&limit=2`)).json())as Row[];const hidden=new Set(((await (await req(`yorisou_recommendation_actions?select=recommendation_item_id&owner_account_id=eq.${encodeURIComponent(owner)}&action=eq.hidden&limit=100`)).json())as Row[]).map(x=>String(x.recommendation_item_id)));const set=((await (await req("yorisou_recommendation_sets",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({project_id:PROJECT_ID,owner_account_id:owner,request_key:requestKey,request_context:{source:context.source,area:context.area},inputs_used:{state_tags:context.tags},excluded_inputs:["raw_private_notes","identity","precise_location"],policy_version:"recommendation-graph-v1"})})).json())as Row[])[0];if(!set)throw new Error("recommendation_set_create_failed");const candidates=[...cards.map(c=>({experience_id:c.id,object_type:"experience_card",reason:reason(context.tags,"experience_card"),disclosure:"匿名で共有された体験です。専門的な指示ではありません。"})),...resources.map(r=>({resource_id:r.id,object_type:"resource",reason:reason(context.tags,"resource"),disclosure:r.commercial_status==="yorisou_owned"?"YORISOUの案内です。任意の選択肢です。":"公的・外部の公開情報です。利用条件はリンク先で確認してください。"}))].slice(0,5);let rank=0;for(const candidate of candidates){rank++;const row=((await (await req("yorisou_recommendation_items",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({project_id:PROJECT_ID,recommendation_set_id:set.id,rank,...candidate,ranking_factors:{eligibility:true,state_tags:context.tags,freshness:true,commercial_after_relevance:true}})})).json())as Row[])[0];if(row&&!hidden.has(String(row.id)))await event(owner,"recommendation_viewed",String(set.id),String(row.id));}
await event(owner,"recommendation_set_created",String(set.id),undefined,{count:candidates.length});return getRecommendationSet(owner,String(set.id));}
export async function getRecommendationSet(owner:string,id:string){const set=((await (await req(`yorisou_recommendation_sets?select=*&id=eq.${encodeURIComponent(id)}&owner_account_id=eq.${encodeURIComponent(owner)}&status=eq.completed&limit=1`)).json())as Row[])[0];if(!set)throw new Error("recommendation_not_found");const items=(await (await req(`yorisou_recommendation_items?select=*,yorisou_resources(*),yorisou_experience_cards(id,state_context,situation,limitations,provenance)&recommendation_set_id=eq.${encodeURIComponent(id)}&lifecycle_status=eq.active&order=rank.asc`)).json())as Row[];return{set,items};}
export async function actionRecommendation(owner:string,itemId:string,action:string,key:string,note?:string){const allowed=["saved","try_intent","tried","helpful","not_helpful","not_relevant","hidden","reported","reason_viewed","resource_opened"];if(!allowed.includes(action))throw new Error("invalid_recommendation_action");const item=((await (await req(`yorisou_recommendation_items?select=id,recommendation_set_id& id=eq.${encodeURIComponent(itemId)}&limit=1`.replace("& id","&id"))).json())as Row[])[0];if(!item)throw new Error("recommendation_item_not_found");await req("rpc/record_yorisou_recommendation_action",{method:"POST",body:JSON.stringify({p_item_id:itemId,p_owner:owner,p_action:action,p_idempotency_key:key,p_note:note||null})});const events:Record<string,string>={saved:"recommendation_saved",try_intent:"recommendation_try_intent",tried:"recommendation_tried",helpful:"recommendation_helpful",not_relevant:"recommendation_not_relevant",hidden:"recommendation_hidden",reported:"recommendation_reported",reason_viewed:"recommendation_reason_viewed",resource_opened:"resource_opened",not_helpful:"outcome_review_completed"};await event(owner,events[action],String(item.recommendation_set_id),itemId);return{ok:true};}
export async function reportRecommendation(owner:string,itemId:string,reason:string){if(!["unsafe","misleading","stale","unavailable","undisclosed_commercial","other"].includes(reason))throw new Error("invalid_recommendation_report");await req("yorisou_recommendation_reports",{method:"POST",headers:{Prefer:"resolution=merge-duplicates"},body:JSON.stringify({project_id:PROJECT_ID,owner_account_id:owner,recommendation_item_id:itemId,reason})});return actionRecommendation(owner,itemId,"reported",randomUUID());}
export async function createReturn(owner:string,setId:string,when:"tomorrow"|"three_days"|"week"|"none"){if(when==="none")return{ok:true};const days=when==="tomorrow"?1:when==="three_days"?3:7;await req("yorisou_recommendation_returns",{method:"POST",body:JSON.stringify({project_id:PROJECT_ID,owner_account_id:owner,recommendation_set_id:setId,next_check_in_at:new Date(Date.now()+days*86400000).toISOString(),return_path:"/recommendations"})});await event(owner,"state_refresh_completed",setId);return{ok:true};}
