"use client";

import { useEffect, useState } from "react";

type State = { reflections: Array<{ id: string; content: { headline: string; current_state_summary: string; visible_patterns: Array<{ title: string; description: string; basis: string }>; reflection_questions: string[]; small_next_steps: Array<{ title: string; description: string }>; limitations: string } }>; memories: Array<{ id: string; content: string; memory_type: string }>; recommendations: Array<{ id: string; title: string; description: string; reason: string; status: string }>; checkIns: Array<{ id: string; suggested_for: string | null }> };

export default function PrivateStatePanel({ resultId }: { resultId: string }) {
  const [state, setState] = useState<State | null>(null); const [loading, setLoading] = useState(false); const [note, setNote] = useState(""); const [error, setError] = useState<string | null>(null);
  const load = () => fetch(`/api/private-state?resultId=${encodeURIComponent(resultId)}`).then(async (r) => { if (!r.ok) throw new Error("読み込めませんでした"); setState((await r.json() as { state: State }).state); }).catch((e) => setError(e instanceof Error ? e.message : "読み込めませんでした"));
  useEffect(() => { load(); }, [resultId]);
  const act = async (body: Record<string, unknown>) => { setError(null); const r = await fetch("/api/private-state", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ resultId, ...body }) }); if (!r.ok) { setError("保存できませんでした。"); return; } setState((await r.json() as { state: State }).state); };
  const generate = async () => { setLoading(true); setError(null); const r = await fetch("/api/private-state/reflections", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ savedResultId: resultId }) }); setLoading(false); if (!r.ok) { setError("今はAIの振り返りを作成できませんでした。結果そのものは変わりません。"); return; } setState((await r.json() as { state: State }).state); };
  const reflection = state?.reflections[0];
  return <section className="mt-8 border-t border-[rgba(23,59,53,0.12)] pt-7"><p className="service-kicker">わたしの今</p><h2 className="display-serif mt-2 text-2xl">結果を、今の自分を見る参考に</h2><p className="mt-3 text-sm leading-7 text-[#5F5750]">AIの振り返りは任意です。診断や結論ではなく、合う部分だけを参考にしてください。</p>
    {!reflection ? <button type="button" onClick={generate} disabled={loading} className="btn mt-5 rounded-full px-5 py-3 disabled:opacity-50">{loading ? "振り返りを準備しています…" : "AIの振り返りを見る"}</button> : <div className="mt-6 rounded-2xl bg-[#F3FAF6] p-5"><p className="text-xs font-semibold text-[#49615B]">AIによる私的な振り返り</p><h3 className="mt-2 text-xl font-semibold">{reflection.content.headline}</h3><p className="mt-3 leading-8">{reflection.content.current_state_summary}</p><div className="mt-5 grid gap-3">{reflection.content.visible_patterns.map((item) => <div key={item.title} className="rounded-xl bg-white/80 p-4"><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm leading-7">{item.description}</p><p className="mt-2 text-xs text-[#5F5750]">見た要素: {item.basis}</p></div>)}</div><p className="mt-4 text-sm text-[#5F5750]">{reflection.content.limitations}</p><button type="button" onClick={() => act({ action: "withdraw", reflectionId: reflection.id })} className="mt-4 text-sm text-[#9b3a34] underline">この振り返りを取り下げる</button></div>}
    <div className="mt-6"><h3 className="font-semibold">小さな次の一歩</h3><div className="mt-3 grid gap-3">{state?.recommendations.map((item) => <div key={item.id} className="rounded-xl border border-[rgba(23,59,53,0.12)] p-4"><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm leading-7">{item.description}</p><p className="mt-2 text-xs text-[#5F5750]">理由: {item.reason}</p><div className="mt-3 flex flex-wrap gap-2">{[["saved","保存"],["try","試す"],["tried","試した"],["helpful","役立った"],["not_relevant","今は違う"]].map(([status,label]) => <button key={status} type="button" onClick={() => act({ action: "recommendation", recommendationId: item.id, status })} className="rounded-full border px-3 py-1 text-xs">{label}</button>)}</div></div>)}</div></div>
    <div className="mt-6 rounded-xl border border-[rgba(23,59,53,0.12)] p-4"><h3 className="font-semibold">自分のメモ</h3><textarea value={note} onChange={(e) => setNote(e.target.value)} maxLength={2000} placeholder="今の自分の言葉で残せます" className="mt-3 min-h-24 w-full rounded-lg border p-3 text-sm" /><button type="button" onClick={() => { if (note.trim()) { act({ action: "memory", content: note, memoryType: "user_note" }); setNote(""); } }} className="mt-2 rounded-full border px-4 py-2 text-sm">メモを保存</button>{state?.memories.map((item) => <p key={item.id} className="mt-3 text-sm text-[#5F5750]">{item.content}</p>)}</div>
    <div className="mt-6"><p className="font-semibold">また振り返る目安</p><div className="mt-2 flex flex-wrap gap-2">{[["tomorrow","明日"],["three_days","3日後"],["week","1週間後"],["none","今は決めない"]].map(([when,label]) => <button key={when} type="button" onClick={() => act({ action: "check_in", when })} className="rounded-full border px-4 py-2 text-sm">{label}</button>)}</div></div>{error ? <p className="mt-4 text-sm text-[#9b3a34]">{error}</p> : null}</section>;
}
