import type { T6Question, T6QuestionOption } from "./t6Types";

const FIVE_POINT_OPTIONS: T6QuestionOption[] = [
  { id: "1", label: "ほとんど当てはまらない" },
  { id: "2", label: "あまり当てはまらない" },
  { id: "3", label: "どちらともいえない" },
  { id: "4", label: "少し当てはまる" },
  { id: "5", label: "かなり当てはまる" },
];

function makeFivePointQuestion(
  id: string,
  section: T6Question["section"],
  prompt: string,
  primaryDimension: T6Question["primaryDimension"],
  secondaryDimension: T6Question["secondaryDimension"],
  direction: string,
  reverse: boolean,
  sensitivity: T6Question["sensitivity"],
): T6Question {
  return {
    id,
    section,
    prompt,
    format: "5-point",
    options: FIVE_POINT_OPTIONS,
    primaryDimension,
    secondaryDimension,
    direction,
    reverse,
    sensitivity,
  };
}

function makeAbQuestion(
  id: string,
  section: T6Question["section"],
  prompt: string,
  leftLabel: string,
  rightLabel: string,
  primaryDimension: T6Question["primaryDimension"],
  secondaryDimension: T6Question["secondaryDimension"],
  direction: string,
  reverse: boolean,
): T6Question {
  return {
    id,
    section,
    prompt,
    format: "AB",
    options: [
      { id: "A", label: leftLabel },
      { id: "B", label: rightLabel },
      { id: "3", label: "どちらともいえない" },
    ],
    primaryDimension,
    secondaryDimension,
    direction,
    reverse,
    sensitivity: "low",
  };
}

export const T6_CURRENT_STATE_QUESTION_BANK: T6Question[] = [
  makeFivePointQuestion(
    "S1Q01",
    "State Load",
    "予定が変わっても、わりとすぐに動き直せる。",
    "pace_orientation",
    "load_sensitivity",
    "high = faster shift",
    false,
    "low",
  ),
  makeAbQuestion(
    "S1Q04",
    "State Load",
    "急いで返すより、少し整えてから返したい。",
    "すぐ返すほうが楽",
    "整えてから返すほうが楽",
    "pace_orientation",
    "processing_style",
    "B = slower pace",
    true,
  ),
  makeFivePointQuestion(
    "S1Q07",
    "State Load",
    "やることが重なると、頭の中が散らかりやすい。",
    "load_sensitivity",
    "clarity_stability",
    "high = higher load",
    false,
    "low",
  ),
  makeFivePointQuestion(
    "S1Q10",
    "State Load",
    "予定が重なっても、順番が見えると少し楽になる。",
    "load_sensitivity",
    "structure_need",
    "high = load eased by order",
    false,
    "low",
  ),
  makeFivePointQuestion(
    "S2Q01",
    "Clarity and Direction",
    "やることが多くても、何から始めるかは見えやすい。",
    "clarity_stability",
    "direction_grip",
    "high = stable clarity",
    false,
    "low",
  ),
  makeFivePointQuestion(
    "S2Q06",
    "Clarity and Direction",
    "少し時間を置くと、自分の考えが見えやすくなる。",
    "clarity_stability",
    "processing_style",
    "high = clarity after pause",
    false,
    "low",
  ),
  makeFivePointQuestion(
    "S2Q07",
    "Clarity and Direction",
    "進む方向が決まると、多少の迷いは気になりにくい。",
    "direction_grip",
    "clarity_stability",
    "high = strong direction",
    false,
    "low",
  ),
  makeFivePointQuestion(
    "S2Q09",
    "Clarity and Direction",
    "何を優先するかが決まると、動きやすくなる。",
    "direction_grip",
    "structure_need",
    "high = direction through priority",
    false,
    "low",
  ),
  makeFivePointQuestion(
    "S3Q01",
    "Structure and Autonomy",
    "順番や流れが見えると、安心して進めやすい。",
    "structure_need",
    "direction_grip",
    "high = high structure need",
    false,
    "low",
  ),
  makeAbQuestion(
    "S3Q05",
    "Structure and Autonomy",
    "自由に進めるより、ある程度の枠があるほうが楽だ。",
    "自由に進めたい",
    "枠があるほうが楽",
    "structure_need",
    "autonomy_preference",
    "B = high structure",
    false,
  ),
  makeFivePointQuestion(
    "S3Q07",
    "Structure and Autonomy",
    "自分で決められる余白があると、力を出しやすい。",
    "autonomy_preference",
    "structure_need",
    "high = autonomy",
    false,
    "low",
  ),
  makeFivePointQuestion(
    "S3Q09",
    "Structure and Autonomy",
    "途中の進め方は、自分で調整できるほうが合っている。",
    "autonomy_preference",
    "pace_orientation",
    "high = autonomy",
    false,
    "low",
  ),
  makeFivePointQuestion(
    "S4Q01",
    "Processing and Expression",
    "何かを感じたとき、まず自分の中で整理したくなる。",
    "processing_style",
    "expression_style",
    "high = internal processing",
    false,
    "low",
  ),
  makeFivePointQuestion(
    "S4Q04",
    "Processing and Expression",
    "返事をする前に、少し考える時間がほしい。",
    "processing_style",
    "pace_orientation",
    "high = internal processing",
    false,
    "low",
  ),
  makeFivePointQuestion(
    "S4Q07",
    "Processing and Expression",
    "自分の考えは、わりと率直に外へ出せる。",
    "expression_style",
    "processing_style",
    "high = direct expression",
    false,
    "low",
  ),
  makeFivePointQuestion(
    "S4Q12",
    "Processing and Expression",
    "伝える内容だけでなく、伝え方の温度も気になりやすい。",
    "expression_style",
    "reassurance_style",
    "high = cautious expression",
    true,
    "low",
  ),
  makeFivePointQuestion(
    "S5Q01",
    "Distance and Reassurance",
    "近い関係でも、自分の時間はしっかり残したい。",
    "distance_preference",
    "autonomy_preference",
    "high = more distance",
    false,
    "low",
  ),
  makeFivePointQuestion(
    "S5Q06",
    "Distance and Reassurance",
    "関係を保つには、ほどよい間が必要だと感じる。",
    "distance_preference",
    "support_preference",
    "high = distance",
    false,
    "low",
  ),
  makeFivePointQuestion(
    "S5Q07",
    "Distance and Reassurance",
    "ひと言でも受け止めてもらえると、落ち着きやすい。",
    "reassurance_style",
    "support_preference",
    "high = reassurance useful",
    false,
    "low",
  ),
  makeAbQuestion(
    "S5Q09",
    "Distance and Reassurance",
    "安心する言葉より、次の動きが見えるほうが助かることがある。",
    "安心する言葉がほしい",
    "次の動きが見えると助かる",
    "reassurance_style",
    "direction_grip",
    "B = practical reassurance",
    false,
  ),
  makeFivePointQuestion(
    "S6Q01",
    "Reset and Support",
    "乱れたあと、まず一人で整える時間がほしくなる。",
    "reset_mode",
    "distance_preference",
    "high = solo reset",
    false,
    "low",
  ),
  makeFivePointQuestion(
    "S6Q03",
    "Reset and Support",
    "落ち着くには、順番を立て直すのが助けになる。",
    "reset_mode",
    "structure_need",
    "high = structure reset",
    false,
    "low",
  ),
  makeFivePointQuestion(
    "S6Q07",
    "Reset and Support",
    "困ったとき、具体的に手伝ってもらえると助かる。",
    "support_preference",
    "structure_need",
    "high = practical support",
    false,
    "low",
  ),
  makeFivePointQuestion(
    "S6Q08",
    "Reset and Support",
    "そっと見守ってもらうほうが、動きやすいことがある。",
    "support_preference",
    "distance_preference",
    "high = space-based support",
    false,
    "low",
  ),
];

export const T6_24Q_CANDIDATE_IDS = T6_CURRENT_STATE_QUESTION_BANK.map((question) => question.id);
