// POR-1 — the frozen promotion source gate must be able to fail.
//
// The gate's whole claim is that 101…108 are still exactly what their source produces. A gate that
// cannot fail makes that claim unfalsifiable, which is worse than not having it — it reads as
// assurance. So each case here breaks exactly one thing in a COPY and drives the shipped CLI over
// it. Nothing about the compiler or the verifier is reimplemented.
//
// The mutable-Preview control is the one that matters most: it is the situation that actually
// occurred. Live Preview received 202608050002 and stopped being a valid compiler source, and the
// point of freezing was that the committed source keeps regenerating the promotion set regardless of
// what the live database does next.

import assert from "node:assert/strict";
import test from "node:test";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { cpSync, mkdtempSync, readFileSync, writeFileSync, rmSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const CHECKER = join(ROOT, "scripts", "por1", "check-promotion-source.mjs");
const MANIFEST_REL = "supabase/contracts/sources/por1-promotion-source-manifest.json";

function runChecker(manifestRel = MANIFEST_REL) {
  const r = spawnSync(process.execPath, [CHECKER, "--manifest", manifestRel], {
    cwd: ROOT,
    encoding: "utf8",
  });
  return { status: r.status, stdout: r.stdout ?? "", stderr: r.stderr ?? "" };
}

/**
 * A full copy of the frozen source trio inside a temp directory, wired through a manifest whose
 * paths point back at it. `mutate` gets the chance to break one thing before the gate runs.
 */
function withMutatedSource(mutate) {
  // Inside the repository root on purpose: the checker resolves manifest paths against ROOT, so a
  // fixture in the system temp directory cannot be addressed relatively. Removed in `finally`.
  const dir = mkdtempSync(join(ROOT, ".por1-source-control-"));
  const rel = (p) => join(dir, p);
  try {
    const manifest = JSON.parse(readFileSync(join(ROOT, MANIFEST_REL), "utf8"));
    cpSync(join(ROOT, manifest.preview.path), rel("preview.json"));
    cpSync(join(ROOT, manifest.production.path), rel("production.json"));

    // Paths must remain repository-relative, because the checker resolves them against ROOT. The
    // temp copies are therefore addressed by a relative path from ROOT.
    const relFromRoot = (abs) => abs.slice(ROOT.length + 1);
    manifest.preview.path = relFromRoot(rel("preview.json"));
    manifest.production.path = relFromRoot(rel("production.json"));

    mutate({ dir, manifest, previewPath: rel("preview.json"), productionPath: rel("production.json") });

    const manifestPath = rel("manifest.json");
    writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + "\n");
    return runChecker(relFromRoot(manifestPath));
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

// ── the positive control ────────────────────────────────────────────────────

test("the committed frozen source regenerates 101-108 and the contract byte for byte", () => {
  const { status, stdout, stderr } = runChecker();
  assert.equal(status, 0, `the committed source must pass; stderr:\n${stderr}`);
  assert.match(stdout, /"failures": 0/);
  assert.match(stdout, /"migrations": 8/);
});

// ── A. byte corruption in a frozen catalogue ────────────────────────────────

test("A: one changed byte in a frozen catalogue fails the gate", () => {
  const { status, stderr } = withMutatedSource(({ previewPath }) => {
    const parsed = JSON.parse(readFileSync(previewPath, "utf8"));
    // Change a real function body hash — the kind of edit that would silently alter what the
    // compiler emits.
    parsed.functions[0].hash = "0".repeat(64);
    writeFileSync(previewPath, JSON.stringify(parsed, null, 2) + "\n");
  });
  assert.notEqual(status, 0, "a corrupted source must not be accepted");
  assert.match(stderr, /sha256|REGENERATED BYTES DIFFER/);
});

// ── B. manifest digest corruption ───────────────────────────────────────────

test("B: a wrong recorded digest fails the gate", () => {
  const { status, stderr } = withMutatedSource(({ manifest }) => {
    manifest.preview.sha256 = "f".repeat(64);
  });
  assert.notEqual(status, 0);
  assert.match(stderr, /sha256 .* ≠ manifest/);
});

// ── C. the mutable post-overlay Preview — the situation that actually happened ──

test("C: the post-202608050002 live Preview state is not accepted as the frozen source", () => {
  const { status, stderr } = withMutatedSource(({ previewPath }) => {
    const parsed = JSON.parse(readFileSync(previewPath, "utf8"));
    // Synthesise the overlay's defining effect: the weak owner-only signature is gone and the
    // four-argument, job-bound entry point exists. This is what live Preview looks like now.
    const weak = "yorisou_account_deletion_erase_database(p_owner_account_id text)";
    const idx = parsed.functions.findIndex((f) => f.signature === weak);
    assert.notEqual(idx, -1, "the frozen source must still be the PRE-parity state");
    parsed.functions[idx] = {
      ...parsed.functions[idx],
      signature:
        "yorisou_account_deletion_erase_database(p_job_id uuid, p_owner_account_id text, p_executor_token_hash text, p_executor_generation integer)",
      identity_args:
        "p_job_id uuid, p_owner_account_id text, p_executor_token_hash text, p_executor_generation integer",
      hash: "1".repeat(64),
    };
    writeFileSync(previewPath, JSON.stringify(parsed, null, 2) + "\n");
  });
  assert.notEqual(status, 0, "live mutable Preview must not be able to become the compiler authority");
  assert.match(stderr, /sha256|REGENERATED BYTES DIFFER|compiler refused/);

  // And the committed source is unaffected by whatever the live database now holds.
  assert.equal(runChecker().status, 0, "the frozen source still regenerates the promotion set");
});

// ── D. a promoted object missing from the source ────────────────────────────

test("D: removing a promoted object from the source fails the gate", () => {
  const { status, stderr } = withMutatedSource(({ previewPath, manifest }) => {
    const parsed = JSON.parse(readFileSync(previewPath, "utf8"));
    const before = parsed.functions.length;
    parsed.functions = parsed.functions.filter((f) => !f.name.startsWith("yorisou_line_activity"));
    assert.ok(parsed.functions.length < before, "the fixture must actually remove something");
    const text = JSON.stringify(parsed, null, 2) + "\n";
    writeFileSync(previewPath, text);
    // Re-record the digest and counts TRUTHFULLY for the mutated file, so the hash check passes and
    // the failure is attributable to the missing object rather than to tampering detection firing
    // first. This is the harder version of the control: the source is internally consistent and
    // still cannot regenerate the promotion set.
    manifest.preview.sha256 = createHash("sha256").update(text).digest("hex");
    manifest.preview.objectCounts = {
      tables: parsed.tables.length,
      functions: parsed.functions.length,
      sequences: parsed.sequences.length,
      triggers: parsed.triggers.length,
    };
  });
  assert.notEqual(status, 0, "a source missing promoted objects must not regenerate the set");
  assert.match(stderr, /REGENERATED BYTES DIFFER|compiler refused|did not emit/);
});

// ── the source's own boundaries ─────────────────────────────────────────────

test("109-111 and the final contract are declared outside this source", () => {
  const manifest = JSON.parse(readFileSync(join(ROOT, MANIFEST_REL), "utf8"));
  for (const version of ["202608010109", "202608010110", "202608010111"]) {
    assert.ok(
      manifest.outsideThisSource.migrations.includes(version),
      `${version} is a hand-written overlay, not an output of this source`,
    );
    assert.ok(!(version in manifest.compiler.expectedMigrationDigests));
  }
  assert.equal(manifest.outsideThisSource.contract, "supabase/contracts/por1-final-promoted-contract.json");
});

test("the manifest states plainly that this is a frozen source, not a replay", () => {
  const manifest = JSON.parse(readFileSync(join(ROOT, MANIFEST_REL), "utf8"));
  assert.equal(manifest.sourceKind, "frozen_catalogue_source");
  assert.match(
    manifest.truth,
    /not represented as a replay of the complete Preview migration history/,
    "the Preview lineage is not linearly replayable and the manifest must not imply otherwise",
  );
  assert.ok(existsSync(join(ROOT, manifest.preview.path)));
  assert.ok(existsSync(join(ROOT, manifest.production.path)));
});
