"use client";
import { useEffect,useState } from "react";

type Card={id:string;state_context:string;situation:string;action_tried:string;perceived_outcome:string;limitations:string;may_fit:string;may_not_fit:string;visibility:string;provenance:string;ai_assistance_status:string;moderation_status?:string;why_shown?:string};
type Form={stateContext:string;situation:string;actionTried:string;perceivedOutcome:string;limitations:string;mayFit:string;mayNotFit:string;visibility:"PRIVATE"|"INVITE_ONLY"|"ANONYMOUS_SHARED"|"SIMILAR_STATE_ONLY";previewConfirmed:boolean;aiAssistanceStatus:"none"|"accepted"|"rejected";sourceSavedResultId?:string|null};
const empty:Form={stateContext:"",situation:"",actionTried:"",perceivedOutcome:"",limitations:"",mayFit:"",mayNotFit:"",visibility:"PRIVATE",previewConfirmed:false,aiAssistanceStatus:"none",sourceSavedResultId:null};
const fields:Array<[keyof Form,string,string,number]>=[["stateContext","今の状態や背景","例: 少し疲れていて、急がず整えたい時期でした。",1200],["situation","何が起きていたか","個人や場所を特定できる情報は書かないでください。",3000],["actionTried","試したこと","自分が実際に試した行動を記します。",3000],["perceivedOutcome","自分にはどう感じられたか","効果の保証ではなく、自分の受け取り方として書きます。",3000],["limitations","条件や限界","合わなかった点、分からない点、前提を書きます。",2000],["mayFit","合うかもしれない人・場面","限定的な可能性として書きます。",1200],["mayNotFit","合わないかもしれない人・場面","無理に勧めないための境界を書きます。",1200]];
function toForm(card:Card):Form{return{stateContext:card.state_context,situation:card.situation,actionTried:card.action_tried,perceivedOutcome:card.perceived_outcome,limitations:card.limitations,mayFit:card.may_fit,mayNotFit:card.may_not_fit,visibility:card.visibility as Form["visibility"],previewConfirmed:true,aiAssistanceStatus:card.ai_assistance_status as Form["aiAssistanceStatus"]};}
export default function ExperienceHub(){const[form,setForm]=useState<Form>(empty),[own,setOwn]=useState<Card[]>([]),[discover,setDiscover]=useState<Card[]>([]),[preview,setPreview]=useState(false),[editing,setEditing]=useState<string|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);const load=async()=>{const[a,b]=await Promise.all([fetch("/api/experiences"),fetch("/api/experiences?mode=discover")]);if(a.ok)setOwn((await a.json()).experiences);if(b.ok)setDiscover((await b.json()).experiences);};useEffect(()=>{const source=new URLSearchParams(window.location.search).get("source");Promise.resolve().then(()=>{if(source)setForm(current=>({...current,sourceSavedResultId:source}));return load();}).catch(()=>setMessage("読み込みに失敗しました。"));},[]);
const submit=async()=>{setBusy(true);setMessage("");const body={...form,previewConfirmed:preview&&form.previewConfirmed};const r=await fetch(editing?`/api/experiences/${editing}`:"/api/experiences",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setBusy(false);if(!r.ok){setMessage("内容、同意、または個人情報の可能性を確認してください。");return;}setForm(empty);setPreview(false);setEditing(null);setMessage(form.visibility==="PRIVATE"?"非公開の下書きを保存しました。":"体験カードを共有しました。");await load();};
const structure=async()=>{setBusy(true);const r=await fetch("/api/experiences",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"structure",card:form})});setBusy(false);if(!r.ok){setMessage("今はAI整理を利用できません。元の文章は変わっていません。");return;}const c=(await r.json()).candidate;setForm({...form,stateContext:c.stateContext,situation:c.situation,actionTried:c.actionTried,perceivedOutcome:c.perceivedOutcome,limitations:c.limitations,mayFit:c.mayFit,mayNotFit:c.mayNotFit,aiAssistanceStatus:"accepted"});setMessage("AI整理案を反映しました。内容を確認し、自由に編集できます。");};
const action=async(id:string,value:string,extra:Record<string,unknown>={})=>{await fetch("/api/experiences",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:value==="report"||value==="block"?value:"interact",id,value,idempotencyKey:crypto.randomUUID(),...extra})});setMessage("反映しました。");};
const invite=async(id:string)=>{const r=await fetch("/api/experiences",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"invite",id})});if(!r.ok)return setMessage("招待リンクを作れませんでした。");const data=await r.json();setMessage(`${location.origin}/experiences/invite/${data.invite.token}（${new Date(data.invite.expiresAt).toLocaleDateString("ja-JP")}まで）`);};
return <main className="min-h-screen bg-[var(--bg)]"><div className="container py-8"><section className="mx-auto max-w-[48rem] rounded-[1.5rem] bg-white/90 p-5 sm:p-8"><p className="service-kicker">体験カード</p><h1 className="display-serif mt-2 text-3xl">体験を、静かに整理して届ける</h1><p className="mt-3 text-sm leading-7 text-[#5F5750]">投稿ではなく、自分の体験を条件や限界と一緒に残す場所です。実名、勤務先、住所、連絡先、他の人が分かる情報は含めないでください。</p>
<div className="mt-7 grid gap-5">{fields.map(([key,label,hint,max])=><label key={String(key)} className="block"><span className="text-sm font-semibold">{label}</span><span className="mt-1 block text-xs leading-5 text-[#6F625C]">{hint}</span><textarea value={String(form[key])} onChange={e=>setForm({...form,[key]:e.target.value})} maxLength={max} className="mt-2 min-h-24 w-full rounded-xl border border-[#D8D0C8] bg-white p-3 text-sm leading-7"/></label>)}</div>
<div className="mt-6 rounded-xl bg-[#F3FAF6] p-4"><p className="text-sm font-semibold">AIで文章を整理する（任意）</p><p className="mt-1 text-xs leading-6 text-[#5F5750]">選んだ下書きだけを整理し、個人を特定しやすい表現を減らします。事実の追加や自動公開はしません。</p><button type="button" onClick={structure} disabled={busy} className="mt-3 rounded-full border px-4 py-2 text-sm">整理案を作る</button></div>
<label className="mt-6 block text-sm font-semibold">公開範囲<select value={form.visibility} onChange={e=>setForm({...form,visibility:e.target.value as Form["visibility"],previewConfirmed:false})} className="mt-2 w-full rounded-xl border p-3"><option value="PRIVATE">非公開（自分だけ）</option><option value="INVITE_ONLY">招待リンクだけ</option><option value="ANONYMOUS_SHARED">匿名で共有</option><option value="SIMILAR_STATE_ONLY">近い関心の人に限定表示</option></select></label><p className="mt-2 text-xs leading-6 text-[#5F5750]">初期値は非公開です。匿名共有でも安全確認のため内部では所有者との関係を保持します。公開検索や仮名プロフィールは有効にしません。</p>
<button type="button" onClick={()=>setPreview(true)} className="mt-5 rounded-full border px-5 py-3 text-sm">共有前の表示を確認</button>{preview?<div className="mt-5 rounded-2xl border p-5"><p className="text-xs font-semibold text-[#49615B]">共有候補プレビュー</p><h2 className="mt-2 text-xl font-semibold">{form.stateContext||"状態や背景"}</h2><p className="mt-3 text-sm leading-7">{form.situation}</p><dl className="mt-4 grid gap-3 text-sm"><div><dt className="font-semibold">試したこと</dt><dd>{form.actionTried}</dd></div><div><dt className="font-semibold">感じた結果</dt><dd>{form.perceivedOutcome}</dd></div><div><dt className="font-semibold">限界</dt><dd>{form.limitations}</dd></div></dl>{form.visibility!=="PRIVATE"?<label className="mt-5 flex gap-3 text-sm"><input type="checkbox" checked={form.previewConfirmed} onChange={e=>setForm({...form,previewConfirmed:e.target.checked})}/><span>第三者の個人情報を含まず、この範囲で共有することに同意します。</span></label>:null}</div>:null}
<div className="mt-6 flex flex-wrap gap-3"><button type="button" onClick={submit} disabled={busy} className="btn rounded-full px-5 py-3">{form.visibility==="PRIVATE"?"下書きを保存":"この範囲で共有"}</button><button type="button" onClick={()=>{setForm(empty);setEditing(null);setPreview(false);}} className="rounded-full border px-5 py-3 text-sm">下書きを破棄</button></div>{message?<p className="mt-4 text-sm text-[#49615B]">{message}</p>:null}
<section className="mt-10 border-t pt-7"><h2 className="text-xl font-semibold">自分の体験カード</h2><div className="mt-4 grid gap-3">{own.map(card=><article key={card.id} className="rounded-xl border p-4"><p className="font-semibold">{card.state_context}</p><p className="mt-1 text-xs">{card.visibility}・{card.provenance}</p><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>{setEditing(card.id);setForm(toForm(card));scrollTo({top:0,behavior:"smooth"});}} className="text-sm underline">編集</button>{card.visibility==="INVITE_ONLY"?<button onClick={()=>invite(card.id)} className="text-sm underline">招待リンクを作る</button>:null}<button onClick={()=>fetch(`/api/experiences/${card.id}`,{method:"DELETE"}).then(load)} className="text-sm underline">取り下げ</button><button onClick={()=>confirm("完全に削除しますか？")&&fetch(`/api/experiences/${card.id}?mode=delete`,{method:"DELETE"}).then(load)} className="text-sm text-[#9b3a34] underline">削除</button></div></article>)}</div></section>
<section className="mt-10 border-t pt-7"><h2 className="text-xl font-semibold">今読める体験</h2><p className="mt-2 text-sm text-[#5F5750]">人気順ではなく、最大20件の有限な候補です。</p><div className="mt-4 grid gap-4">{discover.map(card=><article key={card.id} className="rounded-2xl bg-[#F7FBF8] p-5"><p className="text-xs text-[#49615B]">{card.why_shown}</p><h3 className="mt-2 font-semibold">{card.state_context}</h3><p className="mt-3 text-sm leading-7">{card.situation}</p><p className="mt-3 text-sm"><b>試したこと:</b> {card.action_tried}</p><p className="mt-2 text-sm"><b>感じた結果:</b> {card.perceived_outcome}</p><p className="mt-2 text-sm"><b>限界:</b> {card.limitations}</p><p className="mt-3 text-xs text-[#5F5750]">出所: {card.provenance==="ai_organized"?"本人の文章をAIで整理":"本人が作成"}</p><div className="mt-4 flex flex-wrap gap-2">{[["save","保存"],["try","試す"],["tried","試した"],["helpful","役立った"],["not_relevant","今は違う"]].map(([v,l])=><button key={v} onClick={()=>action(card.id,v)} className="rounded-full border px-3 py-1 text-xs">{l}</button>)}<button onClick={()=>action(card.id,"report",{reason:"other"})} className="text-xs underline">報告</button><button onClick={()=>action(card.id,"block")} className="text-xs underline">この提供元を非表示</button></div></article>)}</div></section></section></div></main>}
