export type CanonicalDimension = {
  dimensionId: string;
  nameJa: string;
  definition: string;
  allowedSceneFamilies: string[];
  scoringNotes: string;
  neighborDriftGuard: string;
};

export const CANONICAL_DTE_DIMENSIONS: CanonicalDimension[] = [
  { dimensionId: "D01", nameJa: "朝の立ち上がり", definition: "How a person starts the day when the first hour still has room to set the tone.", allowedSceneFamilies: ["getting out of bed", "morning prep", "first coffee/tea", "first message", "opening the curtains"], scoringNotes: "Score the first movement, not the whole day.", neighborDriftGuard: "Avoid D02 prep drift and D12 late-day fatigue drift." },
  { dimensionId: "D02", nameJa: "出発前の段取り", definition: "How someone organizes the moments before leaving home.", allowedSceneFamilies: ["玄関まわり", "bag check", "wallet/keys", "leaving for errands", "leaving for appointments"], scoringNotes: "Judge whether the person wants order first or movement first.", neighborDriftGuard: "Avoid D08 threshold drift and D20 decision-habit drift." },
  { dimensionId: "D03", nameJa: "通院・買い物の切り替え", definition: "How someone shifts between a necessary appointment and a practical errand.", allowedSceneFamilies: ["clinic + supermarket", "pharmacy + store", "one-stop errands", "small outing bundles"], scoringNotes: "Keep it about switching and load, not illness or purchases.", neighborDriftGuard: "Avoid D04 shopping-priority drift and D13 schedule-change drift." },
  { dimensionId: "D04", nameJa: "買い物の優先付け", definition: "How someone decides what should go into the basket first or be left out.", allowedSceneFamilies: ["supermarket", "convenience store", "home supplies", "small shopping choices"], scoringNotes: "Look for whether the item sorts needs, not whether the person likes shopping.", neighborDriftGuard: "Avoid D03 errand-switching drift and D17 reward drift." },
  { dimensionId: "D05", nameJa: "雨の日の移動", definition: "How someone handles movement when rain adds friction.", allowedSceneFamilies: ["umbrella use", "slippery ground", "bag protection", "short trip", "local errands in rain"], scoringNotes: "Score weather adaptation, not weather liking.", neighborDriftGuard: "Avoid D08 threshold drift and D13 schedule-change drift." },
  { dimensionId: "D06", nameJa: "片付けと収納", definition: "How someone manages visible clutter and places items back into order.", allowedSceneFamilies: ["room tidying", "shelf/box use", "putting things away", "clearing surfaces"], scoringNotes: "Judge whether the person wants order now or later.", neighborDriftGuard: "Avoid D07 safety drift and D15 overload drift." },
  { dimensionId: "D07", nameJa: "家の中の安全確認", definition: "How someone notices and responds to small safety conditions at home.", allowedSceneFamilies: ["floor slips", "mats", "handholds", "lighting", "doorway safety", "daily home checks"], scoringNotes: "Score prevention style, not anxiety volume.", neighborDriftGuard: "Avoid D08 threshold drift and D19 reassurance drift." },
  { dimensionId: "D08", nameJa: "段差・階段・玄関", definition: "How someone handles thresholds, steps, and entry/exit friction.", allowedSceneFamilies: ["entrance step", "stairs", "doorway", "carrying items through thresholds"], scoringNotes: "Keep the scene body-level and local.", neighborDriftGuard: "Avoid D02 departure-prep drift and D05 rain drift." },
  { dimensionId: "D09", nameJa: "連絡・返事の温度", definition: "How someone chooses the tone and timing of replies in LINE-like communication.", allowedSceneFamilies: ["LINE reply", "text返事", "short check-in", "brief coordination"], scoringNotes: "Score tone and timing together.", neighborDriftGuard: "Avoid D10 family-help drift and D18 social-distance drift." },
  { dimensionId: "D10", nameJa: "家族への一言相談", definition: "How someone asks family for a small, practical piece of help or confirmation.", allowedSceneFamilies: ["asking one favor", "sharing a plan", "confirming timing", "small household coordination"], scoringNotes: "Judge whether the ask is small and natural.", neighborDriftGuard: "Avoid D09 reply drift and D15 load-stacking drift." },
  { dimensionId: "D11", nameJa: "ひとり時間の回復", definition: "How someone restores energy when alone and off duty.", allowedSceneFamilies: ["sitting alone", "tea break", "scrolling pause", "simple quiet reset", "short downtime"], scoringNotes: "Score whether the solitude restores.", neighborDriftGuard: "Avoid D12 late-day drift and D19 reassurance drift." },
  { dimensionId: "D12", nameJa: "夜の気力の残り方", definition: "How much usable energy remains by the end of the day.", allowedSceneFamilies: ["after dinner", "late evening", "final cleanup", "evening message", "night routine"], scoringNotes: "Score remaining usable energy, not total tiredness.", neighborDriftGuard: "Avoid D11 solitude drift and D14 failure-recovery drift." },
  { dimensionId: "D13", nameJa: "予定変更への耐性", definition: "How someone responds when a plan changes after it was already set.", allowedSceneFamilies: ["canceled appointment", "timing shift", "changed errands", "changed meeting time"], scoringNotes: "Judge response to change itself.", neighborDriftGuard: "Avoid D20 decision-habit drift and D02 departure-prep drift." },
  { dimensionId: "D14", nameJa: "失敗日の立て直し", definition: "How someone recovers after a day goes badly or a small mistake lands hard.", allowedSceneFamilies: ["missed errand", "wrong purchase", "small mistake", "awkward day", "disappointed day"], scoringNotes: "Score the reset move, not the size of the failure.", neighborDriftGuard: "Avoid D13 change drift and D17 reward drift." },
  { dimensionId: "D15", nameJa: "仕事と家事の同時進行", definition: "How someone handles two practical demands at once without losing rhythm.", allowedSceneFamilies: ["working while cooking", "chores during breaks", "juggling tasks", "daily load stacking"], scoringNotes: "Score concurrent-load handling, not how hard they work.", neighborDriftGuard: "Avoid D03 task-switching drift and D06 tidying drift." },
  { dimensionId: "D16", nameJa: "週末の過ごし方", definition: "How someone shapes the feel of an ordinary weekend.", allowedSceneFamilies: ["home weekend", "local outing", "slow errand day", "quiet reset day"], scoringNotes: "Score the weekend feel, not special holiday energy.", neighborDriftGuard: "Avoid D11 solitude drift and D17 reward drift." },
  { dimensionId: "D17", nameJa: "小さなご褒美の選び方", definition: "How someone chooses a small reward after effort or as a mood lift.", allowedSceneFamilies: ["snack choice", "drink choice", "short treat", "small purchase", "tiny self-care"], scoringNotes: "Keep it small and daily, not aspirational.", neighborDriftGuard: "Avoid D04 shopping-priority drift and D14 recovery drift." },
  { dimensionId: "D18", nameJa: "周囲との距離感", definition: "How someone keeps comfortable space with other people in daily life.", allowedSceneFamilies: ["neighbors", "LINE groups", "workplace/hobby distance", "small social encounters"], scoringNotes: "Score the space between self and others, not friendliness alone.", neighborDriftGuard: "Avoid D09 message-timing drift and D10 family-help drift." },
  { dimensionId: "D19", nameJa: "安心材料の集め方", definition: "How someone gathers reassurance before moving forward or settling down.", allowedSceneFamilies: ["checking notes", "confirming schedule", "asking once", "keeping reminders", "preparing backups"], scoringNotes: "Score how reassurance is collected and used.", neighborDriftGuard: "Avoid D07 hazard-check drift and D11 solitude drift." },
  { dimensionId: "D20", nameJa: "先送り/決断の癖", definition: "How someone tends to delay, decide, or keep decisions pending.", allowedSceneFamilies: ["small choice points", "tasks waiting", "later behavior", "ordinary errands"], scoringNotes: "Judge the pattern of closure, not correctness.", neighborDriftGuard: "Avoid D13 change-response drift and vague D21 action-threshold drift." },
  { dimensionId: "D21", nameJa: "動く vs 様子を見る", definition: "How someone chooses between acting now and watching a little longer.", allowedSceneFamilies: ["errands", "messages", "small chores", "social prompts", "timing decisions"], scoringNotes: "Keep the choice pressure visible.", neighborDriftGuard: "Avoid D20 generic delay drift and D13 post-change drift." },
];

export const CANONICAL_DIMENSION_IDS = CANONICAL_DTE_DIMENSIONS.map((dimension) => dimension.dimensionId);

export function getCanonicalDimension(dimensionId: string) {
  return CANONICAL_DTE_DIMENSIONS.find((dimension) => dimension.dimensionId === dimensionId) || null;
}

