export type CanonicalPersona = {
  personaId: string;
  workingName: string;
  shortLabelDirection: string;
  coreDefiningDimensions: string[];
  secondaryDimensions: string[];
  teaserDirection: string;
  shareCardDirection: string;
  deepReportExpansionDirection: string;
  distinctionNote: string;
  closestNeighborPersonas: string[];
};

export const CANONICAL_PERSONAS: CanonicalPersona[] = [
  { personaId: "P01", workingName: "朝型・段取り型", shortLabelDirection: "朝の最初の動きと出発準備を、順番よく整える", coreDefiningDimensions: ["D01", "D02"], secondaryDimensions: ["D20", "D21"], teaserDirection: "朝の立ち上がりと出発前の整え方が、その日の滑り方を決める。", shareCardDirection: "早起き / 段取り / ひと声 / ゆっくり始動", deepReportExpansionDirection: "起動速度, 段取り順, 早め判断", distinctionNote: "朝の起動と出発準備を同じ準備線に置き、後半の判断圧力から切り離す。", closestNeighborPersonas: ["P02", "P22"] },
  { personaId: "P02", workingName: "段取り型・慎重型", shortLabelDirection: "出発前に順番と変更耐性を先に見たい", coreDefiningDimensions: ["D02", "D13"], secondaryDimensions: ["D19", "D20"], teaserDirection: "段取りが決まると、変更にも少し落ち着いて向き合える。", shareCardDirection: "出発前チェック / 変更に強い / 様子見 / 慎重運用", deepReportExpansionDirection: "準備順, 変更耐性, 保留癖", distinctionNote: "出発準備を起点にしながら、変化への耐性を見せるため P01 から分離している。", closestNeighborPersonas: ["P01", "P13"] },
  { personaId: "P03", workingName: "実務型・体力優先型", shortLabelDirection: "用事の切り替えと負荷を、体力目線でさばく", coreDefiningDimensions: ["D03", "D15"], secondaryDimensions: ["D20"], teaserDirection: "通院や買い物の切り替えを、体力の残り方で見ている。", shareCardDirection: "実務 / 体力優先 / まとめて処理 / 負荷調整", deepReportExpansionDirection: "切替速度, 負荷配分, 同時進行", distinctionNote: "連続用事の切り替えと同時進行を、生活実務の中で測る。", closestNeighborPersonas: ["P15", "P23"] },
  { personaId: "P04", workingName: "生活実務型・気分回復型", shortLabelDirection: "買い物の実務と小さな気分回復を両立したい", coreDefiningDimensions: ["D04", "D17"], secondaryDimensions: ["D11"], teaserDirection: "カゴに入れる順番に、実用と気分の両方が出る。", shareCardDirection: "実用優先 / 気分も大事 / 小さなご褒美 / 生活実務", deepReportExpansionDirection: "優先順, 小回復, 実用と気分の両立", distinctionNote: "買い物判断を起点にしているので、片付け系や単純ご褒美系から離れている。", closestNeighborPersonas: ["P06", "P27"] },
  { personaId: "P05", workingName: "慎重型・負担回避型", shortLabelDirection: "雨や段差の負荷を見て、無理を減らしたい", coreDefiningDimensions: ["D05", "D08"], secondaryDimensions: ["D19"], teaserDirection: "雨の日や玄関まわりで、負担の少ない動き方を選ぶ。", shareCardDirection: "慎重 / 負担回避 / 安全第一 / 小さく動く", deepReportExpansionDirection: "摩擦感知, 移動慎重, 負担回避", distinctionNote: "天候摩擦と身体摩擦を、行き先より先に感じ取る人格。", closestNeighborPersonas: ["P07", "P24"] },
  { personaId: "P06", workingName: "整理型・見た目整え型", shortLabelDirection: "片付けの順番と置き場所で、見た目を整える", coreDefiningDimensions: ["D06", "D17"], secondaryDimensions: ["D11"], teaserDirection: "片付けの入り口が見えると、気分も少し整う。", shareCardDirection: "整理 / 置き場所 / 見た目整え / 半分だけでも進める", deepReportExpansionDirection: "整理順, 収納判断, 見た目の整い", distinctionNote: "収納と小さなご褒美が同居しても、起点はあくまで片付け。", closestNeighborPersonas: ["P04", "P27"] },
  { personaId: "P07", workingName: "安全優先型・慎重型", shortLabelDirection: "家の中の小さな危険と、先回りの確認を見ている", coreDefiningDimensions: ["D07", "D19"], secondaryDimensions: ["D08"], teaserDirection: "すべりや段差より先に、安心できる環境を整えたい。", shareCardDirection: "安全優先 / 確認 / 先回り / 低リスク", deepReportExpansionDirection: "安全確認, 事前チェック, 安心材料", distinctionNote: "安全確認を主軸にし、移動のしやすさとは切り離している。", closestNeighborPersonas: ["P05", "P24"] },
  { personaId: "P08", workingName: "慎重型・現実調整型", shortLabelDirection: "変化が来たとき、動くか様子を見るかを現実で調整する", coreDefiningDimensions: ["D13", "D21"], secondaryDimensions: ["D20"], teaserDirection: "予定が変わると、まず動くか待つかを現実で見直す。", shareCardDirection: "慎重 / 現実調整 / 動くか様子見るか / 低リスク判断", deepReportExpansionDirection: "変更対応, 先送り, 即応性", distinctionNote: "変更後の判断と、動くか待つかの境目をはっきり持っている。", closestNeighborPersonas: ["P13", "P20", "P21"] },
  { personaId: "P09", workingName: "連絡丁寧型・即返し型", shortLabelDirection: "返事の温度とスピードを、LINEでちょうどよく合わせる", coreDefiningDimensions: ["D09"], secondaryDimensions: ["D18"], teaserDirection: "連絡は、早さと温度の両方がちょうどよいと落ち着く。", shareCardDirection: "丁寧 / 即返し / LINE感 / 短く温かく", deepReportExpansionDirection: "返信温度, 返答速度, 連絡感覚", distinctionNote: "純粋な返信温度の基準点として機能する。", closestNeighborPersonas: ["P10", "P18", "P25"] },
  { personaId: "P10", workingName: "家族調整型・実務連絡型", shortLabelDirection: "家族に一言で伝え、実務の流れをそろえる", coreDefiningDimensions: ["D10", "D09"], secondaryDimensions: ["D15"], teaserDirection: "家族への一言相談で、実務の流れをやわらかくそろえる。", shareCardDirection: "家族調整 / 実務連絡 / 一声相談 / 手短に共有", deepReportExpansionDirection: "相談の短さ, 家族連絡, 実務橋渡し", distinctionNote: "家族向けの一言相談を中心に、単なる連絡返しとは分けている。", closestNeighborPersonas: ["P09", "P28"] },
  { personaId: "P11", workingName: "内向回復型・静養型", shortLabelDirection: "ひとりの静かな時間で、気力を戻す", coreDefiningDimensions: ["D11", "D12"], secondaryDimensions: ["D16"], teaserDirection: "静かな回復と夜の気力の残り方が、この人の調子を示す。", shareCardDirection: "静養 / 内向回復 / ひとり時間 / 夜は静かに", deepReportExpansionDirection: "回復余白, 夜の残量, 静かな戻し方", distinctionNote: "一人で戻る回復線を主軸にし、ご褒美や社交から離している。", closestNeighborPersonas: ["P12", "P17", "P26"] },
  { personaId: "P12", workingName: "夜型・省エネ型", shortLabelDirection: "夜に残る気力を見ながら、省エネで過ごす", coreDefiningDimensions: ["D12", "D11"], secondaryDimensions: ["D17"], teaserDirection: "夜の残り気力を、使い切らずに整えていく。", shareCardDirection: "夜型 / 省エネ / 余力管理 / 静かに終える", deepReportExpansionDirection: "夜残量, 省エネ, 余力管理", distinctionNote: "夜の残量と省エネ運用を主軸にした、静養系とは少し違う夜寄り人格。", closestNeighborPersonas: ["P11", "P26", "P29"] },
  { personaId: "P13", workingName: "柔軟型・慎重型", shortLabelDirection: "変わったあとも、無理なく着地する", coreDefiningDimensions: ["D13", "D20"], secondaryDimensions: ["D21"], teaserDirection: "予定が変わっても、決め急がずに着地を探す。", shareCardDirection: "柔軟 / 慎重 / 変化対応 / 先に様子を見る", deepReportExpansionDirection: "変更耐性, 保留癖, 着地判断", distinctionNote: "変更後の柔らかい着地が中心で、純粋な決断型とは違う。", closestNeighborPersonas: ["P02", "P08", "P20"] },
  { personaId: "P14", workingName: "回復型・整理型", shortLabelDirection: "失敗した日ほど、片付けと立て直しで戻す", coreDefiningDimensions: ["D14", "D06"], secondaryDimensions: ["D17"], teaserDirection: "失敗日の立て直しは、まず小さく片付くことから始まる。", shareCardDirection: "回復 / 整理 / 立て直し / 小さく戻す", deepReportExpansionDirection: "失敗回復, 整理回復, 再起動", distinctionNote: "失敗回復と整理回復を重ねるが、ご褒美系とは別に立てている。", closestNeighborPersonas: ["P06", "P17", "P27"] },
  { personaId: "P15", workingName: "多忙型・切替型", shortLabelDirection: "仕事と家事を、切り替えながら同時にさばく", coreDefiningDimensions: ["D03", "D15"], secondaryDimensions: ["D20"], teaserDirection: "用事の切り替えと同時進行が、この人の日常負荷になる。", shareCardDirection: "多忙 / 切替 / 同時進行 / 実務強め", deepReportExpansionDirection: "負荷調整, 切替速度, 多忙運用", distinctionNote: "通院・買い物の切り替えとは違い、同時進行そのものが主題。", closestNeighborPersonas: ["P03", "P23"] },
  { personaId: "P16", workingName: "回復型・交流型", shortLabelDirection: "落ちたあと、人との軽い交流で戻る", coreDefiningDimensions: ["D14", "D18"], secondaryDimensions: ["D09"], teaserDirection: "失敗した日でも、人との軽い距離があると戻りやすい。", shareCardDirection: "回復 / 交流 / 軽い接点 / 気を取り直す", deepReportExpansionDirection: "失敗後回復, 対人距離, 軽い交流", distinctionNote: "失敗回復を社交の後処理として扱い、単独回復と切り分ける。", closestNeighborPersonas: ["P14", "P18", "P31"] },
  { personaId: "P17", workingName: "回復後ご褒美型", shortLabelDirection: "失敗のあと、小さなご褒美で気持ちを点火し直す", coreDefiningDimensions: ["D14", "D17"], secondaryDimensions: ["D11"], teaserDirection: "失敗日の立て直しは、小さなご褒美で火をつけ直すと進みやすい。", shareCardDirection: "回復後ご褒美 / 小さく点火 / 気分整え / やり直し", deepReportExpansionDirection: "失敗回復, ご褒美選び, 点火回復", distinctionNote: "静養系ではなく、失敗後に小さなご褒美を挟んで再始動する点で分離している。", closestNeighborPersonas: ["P11", "P26", "P14"] },
  { personaId: "P18", workingName: "距離調整型・気遣い型", shortLabelDirection: "人との距離を、近すぎず遠すぎず整える", coreDefiningDimensions: ["D18", "D09"], secondaryDimensions: ["D10"], teaserDirection: "距離感と返事の温度を合わせると、場がやわらぐ。", shareCardDirection: "距離調整 / 気遣い / 無理しない接点 / 温度合わせ", deepReportExpansionDirection: "距離感, 気遣い, 接点調整", distinctionNote: "返事そのものより、相手との間合いをどう保つかが主題。", closestNeighborPersonas: ["P09", "P28", "P31"] },
  { personaId: "P19", workingName: "慎重型・確認型", shortLabelDirection: "安心材料を集めてから、次に進む", coreDefiningDimensions: ["D19", "D20"], secondaryDimensions: ["D07"], teaserDirection: "確認して安心してから進むので、急がずに見える。", shareCardDirection: "慎重 / 確認 / 安心材料 / 一度そろえる", deepReportExpansionDirection: "確認癖, 安心材料, 進行の保留", distinctionNote: "安心材料の集め方を主軸にし、決断の遅さは副次にとどめる。", closestNeighborPersonas: ["P24", "P30"] },
  { personaId: "P20", workingName: "決断型・保留型", shortLabelDirection: "決めるか保留するかを、最後にきちんと分けたい", coreDefiningDimensions: ["D20", "D21"], secondaryDimensions: ["D13"], teaserDirection: "決断と保留の境目が、この人の行動を分ける。", shareCardDirection: "決断 / 保留 / 境目に強い / 即断より整理", deepReportExpansionDirection: "決断速度, 保留管理, 行動境界", distinctionNote: "先送り癖の中でも、決める瞬間の線引きが主題。", closestNeighborPersonas: ["P13", "P21", "P19"] },
  { personaId: "P21", workingName: "即行動型・観察型", shortLabelDirection: "様子を見るより、まず動いて確かめたい", coreDefiningDimensions: ["D21", "D20"], secondaryDimensions: ["D13"], teaserDirection: "動くか様子を見るかで迷うなら、まず動く側に寄りやすい。", shareCardDirection: "即行動 / 観察後より先に動く / まず試す / 反応早め", deepReportExpansionDirection: "行動閾値, 即応, 様子見との距離", distinctionNote: "行動閾値の低さが主題で、決断の遅さとは逆方向に立つ。", closestNeighborPersonas: ["P08", "P20"] },
  { personaId: "P22", workingName: "朝型・回復型", shortLabelDirection: "朝の起動を、回復と一緒にゆっくり整える", coreDefiningDimensions: ["D01", "D11"], secondaryDimensions: ["D12"], teaserDirection: "朝の起動が回復と結びつくと、動き出しが軽くなる。", shareCardDirection: "朝型 / 回復 / ゆっくり始動 / 静かな起動", deepReportExpansionDirection: "朝の回復, 起動速度, 朝の余白", distinctionNote: "朝の起動に回復が混ざるため、純粋な朝型より柔らかい。", closestNeighborPersonas: ["P01", "P11", "P26"] },
  { personaId: "P23", workingName: "実務型・負荷調整型", shortLabelDirection: "実務の同時進行を、負荷に合わせて調整する", coreDefiningDimensions: ["D15", "D03"], secondaryDimensions: ["D12"], teaserDirection: "同時進行の中で、負荷調整ができるかが見える。", shareCardDirection: "実務 / 負荷調整 / 同時進行 / やりくり上手", deepReportExpansionDirection: "負荷調整, 切替, 実務運用", distinctionNote: "多忙型よりも、実務の負荷調整に少し重心を置く。", closestNeighborPersonas: ["P03", "P15", "P12"] },
  { personaId: "P24", workingName: "安全優先型・確認型", shortLabelDirection: "安全のために、確認を重ねてから進む", coreDefiningDimensions: ["D07", "D19"], secondaryDimensions: ["D08"], teaserDirection: "安全確認と安心材料がそろうと、次の一歩が出やすい。", shareCardDirection: "安全優先 / 確認 / 先に見る / 低リスク", deepReportExpansionDirection: "安全確認, 事前確認, 安心確認", distinctionNote: "安全優先の確認型として、一般的な慎重型と分けている。", closestNeighborPersonas: ["P05", "P07", "P19"] },
  { personaId: "P25", workingName: "グループ連絡・慎重返答型", shortLabelDirection: "週末や場の流れを見て、返事の温度を整える", coreDefiningDimensions: ["D09", "D16"], secondaryDimensions: ["D18"], teaserDirection: "返事の温度は、場の流れや週末の空気で少し変わる。", shareCardDirection: "グループ連絡 / 慎重返答 / 場の空気を見る / 遅れすぎない", deepReportExpansionDirection: "返信温度, 場の流れ, 週末の返答", distinctionNote: "ただの即返しではなく、場や週末のリズムを見て返す点で分離した。", closestNeighborPersonas: ["P09", "P18", "P31"] },
  { personaId: "P26", workingName: "夜型・回復型", shortLabelDirection: "夜の残量を見ながら、静かに回復する", coreDefiningDimensions: ["D12", "D11"], secondaryDimensions: ["D16"], teaserDirection: "夜に残った気力を、静かな回復で戻していく。", shareCardDirection: "夜型 / 回復 / 省エネ / 静かに戻す", deepReportExpansionDirection: "夜の残量, 回復, 静かな着地", distinctionNote: "夜の回復そのものを主軸にしているため、週末系よりも日常夜寄り。", closestNeighborPersonas: ["P11", "P12", "P29"] },
  { personaId: "P27", workingName: "気分回復型・整理型", shortLabelDirection: "小さなご褒美と片付けを合わせて、気分を整える", coreDefiningDimensions: ["D17", "D06"], secondaryDimensions: ["D11"], teaserDirection: "ご褒美を取るか片付けるかで、気分の戻り方が変わる。", shareCardDirection: "気分回復 / 整理 / 小さなご褒美 / 片付けと相性", deepReportExpansionDirection: "ご褒美, 整理, 気分の整え", distinctionNote: "回復を、片付けとご褒美の両方から支える人格。", closestNeighborPersonas: ["P04", "P06", "P14"] },
  { personaId: "P28", workingName: "気遣い型・家族調整型", shortLabelDirection: "家族との調整と人との間合いを、気遣いでそろえる", coreDefiningDimensions: ["D10", "D18"], secondaryDimensions: ["D09"], teaserDirection: "家族への一言と、相手との間合いの取り方が自然に結びつく。", shareCardDirection: "気遣い / 家族調整 / 間合い / 実務を荒らさない", deepReportExpansionDirection: "家族調整, 間合い, 気遣い", distinctionNote: "家族軸と距離軸の両方を持つが、連絡の速さそのものは主題ではない。", closestNeighborPersonas: ["P10", "P18", "P31"] },
  { personaId: "P29", workingName: "週末静養・省エネ型", shortLabelDirection: "週末は負荷を落として、静かに整える", coreDefiningDimensions: ["D16", "D11"], secondaryDimensions: ["D12"], teaserDirection: "週末の静養は、夜の省エネともつながっている。", shareCardDirection: "週末静養 / 省エネ / 静かに整える / 無理しない", deepReportExpansionDirection: "週末リズム, 低負荷, 静養運用", distinctionNote: "日常回復系ではなく、週末という時間帯を主軸にした省エネ人格。", closestNeighborPersonas: ["P11", "P26", "P12"] },
  { personaId: "P30", workingName: "現実調整・再段取り型", shortLabelDirection: "変更後に、事実をそろえて再段取りする", coreDefiningDimensions: ["D13", "D19"], secondaryDimensions: ["D20"], teaserDirection: "予定が変わったら、安心より先に事実をそろえて組み直す。", shareCardDirection: "現実調整 / 再段取り / 事実確認 / 落ち着いて組み直す", deepReportExpansionDirection: "変更後再計画, 事実整理, 仕切り直し", distinctionNote: "安心材料を集めるより、変更後の再段取りを先に進める点で分離した。", closestNeighborPersonas: ["P19", "P13", "P24"] },
  { personaId: "P31", workingName: "場づくり・交流調整型", shortLabelDirection: "グループや場の空気に合わせて、距離を配分する", coreDefiningDimensions: ["D18", "D16"], secondaryDimensions: ["D09"], teaserDirection: "場の空気と週末の流れが合うと、交流が無理なく続く。", shareCardDirection: "場づくり / 交流調整 / グループの空気 / 温度配分", deepReportExpansionDirection: "場の距離, 交流, コミュニティ運用", distinctionNote: "一対一の距離調整ではなく、場全体の距離配分を見ている。", closestNeighborPersonas: ["P18", "P28", "P25"] },
];

export const CANONICAL_PERSONA_IDS = CANONICAL_PERSONAS.map((persona) => persona.personaId);

export function getCanonicalPersona(personaId: string) {
  return CANONICAL_PERSONAS.find((persona) => persona.personaId === personaId) || null;
}

