-- POR-1 PROMOTION P8 — Whole-contract assertion — refuses the release rather than discovering a gap later
--
-- PRODUCTION_LINEAGE. Generated by scripts/por1/compile-promotion.mjs from the FINAL Preview
-- catalogue — not from the 24-migration Preview history. Only the last definition of a
-- `create or replace` chain is live, so promoting the history would promote bodies that were
-- already replaced, including the ones replaced because they were wrong.
--
-- Regenerate and verify with:  npm run por1:promotion-check
--
-- CONTENTS
--   tables 0 · sequences 0 · functions 0 · triggers 0
--
-- APPLY SEMANTICS
--   Every statement is guarded (`if not exists` / catalogue probe), so a partial failure can be
--   retried without a human reconstructing which half applied.
--
-- ROLLBACK CLASS
--   SCHEMA_REVERSIBLE_WHILE_FLAGS_OFF — additive only. Nothing here alters or drops an existing
--   Production object, so with the POR-1 capability controls unset these objects are inert: the
--   old application never names them. The Production incident response is to disable the
--   capability and roll back the application, NOT to drop the schema.
--
-- EXISTING-DATA IMPACT
--   None. No backfill, no column change to a populated table, no data movement.
--
-- LOCK CLASS
--   CREATE TABLE / CREATE INDEX on brand-new empty relations. No lock is taken on any table the
--   running application reads or writes.


-- The promotion is not "applied" because six files ran. It is applied when the contract is
-- present, correctly privileged, and closed to every role that must not reach it. Asserting that
-- here means an incomplete promotion fails at migration time — before any capability control is
-- turned on — instead of surfacing as a 500 during activation.

do $$
declare
  v_missing text;
  v_count int;
begin
  -- ── the 15 promoted tables ──
  select string_agg(t, ', ' order by t) into v_missing
    from unnest(array['yorisou_account_deletion_audit', 'yorisou_account_deletion_jobs', 'yorisou_account_deletion_manifests', 'yorisou_account_mutation_gates', 'yorisou_account_mutation_leases', 'yorisou_assessment_attempts', 'yorisou_assessment_results', 'yorisou_canonical_identity_links', 'yorisou_canonical_line_events', 'yorisou_canonical_line_subjects', 'yorisou_canonical_recommendation_actions', 'yorisou_canonical_recommendation_items', 'yorisou_canonical_recommendation_sets', 'yorisou_identity_provisioning_sagas', 'yorisou_interpretation_responses']) t
   where to_regclass('public.' || t) is null;
  if v_missing is not null then
    raise exception 'POR-1 promotion incomplete — missing table(s): %', v_missing;
  end if;

  -- ── row-level security ──
  select string_agg(c.relname, ', ' order by c.relname) into v_missing
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relname = any (array['yorisou_account_deletion_audit', 'yorisou_account_deletion_jobs', 'yorisou_account_deletion_manifests', 'yorisou_account_mutation_gates', 'yorisou_account_mutation_leases', 'yorisou_assessment_attempts', 'yorisou_assessment_results', 'yorisou_canonical_identity_links', 'yorisou_canonical_line_events', 'yorisou_canonical_line_subjects', 'yorisou_canonical_recommendation_actions', 'yorisou_canonical_recommendation_items', 'yorisou_canonical_recommendation_sets', 'yorisou_identity_provisioning_sagas', 'yorisou_interpretation_responses'])
     and not (c.relrowsecurity and c.relforcerowsecurity);
  if v_missing is not null then
    raise exception 'POR-1 promotion incomplete — RLS not enabled and forced on: %', v_missing;
  end if;

  -- ── the 75 promoted functions ──
  select count(*) into v_count
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.prokind = 'f' and p.proname like 'yorisou_%';
  if v_count < 87 then
    raise exception 'POR-1 promotion incomplete — expected at least % yorisou_* functions, found %',
      87, v_count;
  end if;

  -- ── every SECURITY DEFINER function has a fixed search_path ──
  select string_agg(p.proname, ', ' order by p.proname) into v_missing
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname like 'yorisou_%' and p.prosecdef
     and not coalesce(array_to_string(p.proconfig, ',') like '%search_path=%', false);
  if v_missing is not null then
    raise exception 'POR-1: SECURITY DEFINER without a fixed search_path: %', v_missing;
  end if;

  -- ── NOTHING promoted is reachable by an unauthenticated caller ──
  --
  -- PostgREST publishes public-schema functions as RPC under the anon key, so this is the
  -- difference between an internal routine and an internet-facing endpoint. It is asserted against
  -- has_function_privilege, which resolves PUBLIC inheritance — the exact thing that made two
  -- earlier revokes silently ineffective.
  if exists (select 1 from pg_roles where rolname = 'anon') then
    select string_agg(p.proname, ', ' order by p.proname) into v_missing
      from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.proname like 'yorisou_%' and p.prosecdef
       and has_function_privilege('anon', p.oid, 'EXECUTE');
    if v_missing is not null then
      raise exception 'POR-1: SECURITY DEFINER function(s) executable by anon: %', v_missing;
    end if;
  end if;

  -- ── and the internal lock helper stays internal ──
  if exists (select 1 from pg_roles where rolname = 'service_role')
     and exists (
       select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public' and p.proname = 'yorisou_line_subject_lock'
          and has_function_privilege('service_role', p.oid, 'EXECUTE')
     ) then
    raise exception 'POR-1: yorisou_line_subject_lock is a lock building block, not an entry point';
  end if;
end $$;

-- ── the Production families Preview could never exercise ─────────────────────
--
-- These exist in Production and NOT in Preview, so every green Preview deletion run skipped them
-- via `to_regclass` without ever touching them. In Production they are real, populated, and
-- owner-linked. This asserts the deletion plan still names each one; proving it actually erases
-- them is the job of the full-lineage rehearsal, and no assertion here can substitute for that.
do $$
declare
  v_src text;
  v_family text;
begin
  select string_agg(pg_get_functiondef(p.oid), E'\n') into v_src
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname like 'yorisou_account_deletion_%';

  foreach v_family in array array['yorisou_private_recommendations', 'yorisou_private_memory_items', 'yorisou_private_check_in_plans', 'yorisou_ai_reflections', 'yorisou_ai_runs', 'yorisou_test_results'] loop
    if to_regclass('public.' || v_family) is not null and position(v_family in v_src) = 0 then
      raise exception 'POR-1: Production family % exists but is named by no deletion function', v_family;
    end if;
  end loop;
end $$;
