-- Phase 1 foundation only. Do not apply to production without founder approval.
create table if not exists public.agent_runtime_tasks (
 id uuid primary key default gen_random_uuid(), project_id text not null default 'yorisou' check (project_id = 'yorisou'), agent_id text, workflow_type text not null, skill_id text, status text not null default 'queued' check (status in ('queued','scheduled','ready','claimed','running','waiting_for_review','retry_wait','completed','failed','cancelled','paused','dead_letter')), priority integer not null default 100, input_payload jsonb not null check (octet_length(input_payload::text) <= 65536), output_summary text, output_reference text, data_classification text not null check (data_classification in ('internal','sensitive','restricted')), approval_required boolean not null default false, scheduled_at timestamptz, available_at timestamptz not null default now(), claimed_at timestamptz, lease_expires_at timestamptz, started_at timestamptz, completed_at timestamptz, failed_at timestamptz, cancelled_at timestamptz, attempt_count integer not null default 0 check (attempt_count >= 0), maximum_attempts integer not null default 3 check (maximum_attempts between 1 and 10), timeout_seconds integer not null default 300 check (timeout_seconds between 1 and 3600), retry_policy jsonb not null default '{"strategy":"exponential","base_seconds":30}'::jsonb, idempotency_key text not null, cost_budget_cents integer not null default 0 check (cost_budget_cents >= 0), error_class text, error_summary text, parent_task_id uuid references public.agent_runtime_tasks(id), correlation_id text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(project_id,idempotency_key));
create index if not exists agent_runtime_tasks_claim_idx on public.agent_runtime_tasks (project_id,status,available_at,priority,id) where status in ('queued','scheduled','ready','retry_wait');
create table if not exists public.agent_runtime_task_attempts (id uuid primary key default gen_random_uuid(), task_id uuid not null references public.agent_runtime_tasks(id), project_id text not null check (project_id='yorisou'), attempt_number integer not null, previous_status text not null, next_status text not null, actor text not null, reason text not null, correlation_id text not null, lease_expires_at timestamptz, created_at timestamptz not null default now(), unique(task_id,attempt_number,next_status,created_at));
create table if not exists public.agent_runtime_artifacts (id uuid primary key default gen_random_uuid(), task_id uuid not null references public.agent_runtime_tasks(id), project_id text not null check (project_id='yorisou'), storage_uri text not null, sha256 text not null check (sha256 ~ '^[a-f0-9]{64}$'), data_classification text not null, created_at timestamptz not null default now());
create table if not exists public.agent_runtime_review_items (id uuid primary key default gen_random_uuid(), task_id uuid not null unique references public.agent_runtime_tasks(id), project_id text not null check (project_id='yorisou'), status text not null default 'pending' check (status in ('pending','approved','rejected','revision_requested','cancelled')), required_approver text not null default 'edward' check (required_approver='edward'), reason text not null, reviewer_id text, decision_reason text, decided_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.agent_runtime_pause_records (id uuid primary key default gen_random_uuid(), task_id uuid not null references public.agent_runtime_tasks(id), project_id text not null check (project_id='yorisou'), actor text not null, reason text not null, resumed_at timestamptz, created_at timestamptz not null default now());
alter table public.agent_runtime_tasks enable row level security; alter table public.agent_runtime_task_attempts enable row level security; alter table public.agent_runtime_artifacts enable row level security; alter table public.agent_runtime_review_items enable row level security; alter table public.agent_runtime_pause_records enable row level security;
-- No user-facing policies: only a server-side service role may mutate runtime records.
create or replace function public.enforce_yorisou_agent_runtime_transition() returns trigger language plpgsql as $$ begin
 if new.project_id <> 'yorisou' then raise exception 'project namespace forbidden'; end if;
 if new.status <> old.status and not ((old.status='queued' and new.status in ('ready','scheduled','paused','cancelled')) or (old.status='scheduled' and new.status in ('ready','paused','cancelled')) or (old.status='ready' and new.status in ('claimed','paused','cancelled')) or (old.status='claimed' and new.status in ('running','ready','paused','cancelled')) or (old.status='running' and new.status in ('completed','waiting_for_review','retry_wait','failed','paused','cancelled')) or (old.status='waiting_for_review' and new.status in ('ready','paused','cancelled')) or (old.status='retry_wait' and new.status in ('ready','failed','paused','cancelled')) or (old.status='failed' and new.status='dead_letter') or (old.status='paused' and new.status in ('ready','cancelled'))) then raise exception 'illegal runtime task transition: % -> %', old.status, new.status; end if;
 new.updated_at = now(); return new; end; $$;
create trigger agent_runtime_tasks_transition_guard before update on public.agent_runtime_tasks for each row execute function public.enforce_yorisou_agent_runtime_transition();
create or replace function public.recover_stale_yorisou_agent_runtime_tasks() returns integer language plpgsql security definer set search_path = public as $$ declare recovered integer; begin update public.agent_runtime_tasks set status = case when status='claimed' then 'ready' else 'retry_wait' end, available_at=now(), lease_expires_at=null, error_class='stale_lease', error_summary='Lease expired before task completion' where project_id='yorisou' and status in ('claimed','running') and lease_expires_at < now(); get diagnostics recovered = row_count; return recovered; end; $$;
create or replace function public.claim_yorisou_agent_runtime_tasks(p_worker_id text, p_lease_seconds integer default 60, p_batch_size integer default 1) returns setof public.agent_runtime_tasks language plpgsql security definer set search_path = public as $$ begin if p_batch_size < 1 or p_batch_size > 20 or p_lease_seconds < 1 or p_lease_seconds > 300 then raise exception 'invalid claim bounds'; end if; return query with candidates as (select id from public.agent_runtime_tasks where project_id='yorisou' and status in ('queued','scheduled','ready','retry_wait') and available_at <= now() order by priority asc, available_at asc, id for update skip locked limit p_batch_size) update public.agent_runtime_tasks t set status='claimed', claimed_at=now(), lease_expires_at=now() + make_interval(secs => p_lease_seconds), attempt_count=t.attempt_count+1, updated_at=now() from candidates where t.id=candidates.id returning t.*; end; $$;
revoke all on function public.claim_yorisou_agent_runtime_tasks(text,integer,integer) from public;
