-- POR-1 PROMOTION P1 — Canonical assessment attempts, results and interpretation responses
--
-- PRODUCTION_LINEAGE. Generated by scripts/por1/compile-promotion.mjs from the FINAL Preview
-- catalogue — not from the 24-migration Preview history. Only the last definition of a
-- `create or replace` chain is live, so promoting the history would promote bodies that were
-- already replaced, including the ones replaced because they were wrong.
--
-- Regenerate and verify with:  npm run por1:promotion-check
--
-- CONTENTS
--   tables 3 · sequences 1 · functions 11 · triggers 2
--
-- APPLY SEMANTICS
--   Every statement is guarded (`if not exists` / catalogue probe), so a partial failure can be
--   retried without a human reconstructing which half applied.
--
-- ROLLBACK CLASS
--   SCHEMA_REVERSIBLE_WHILE_FLAGS_OFF — additive only. Nothing here alters or drops an existing
--   Production object, so with the POR-1 capability controls unset these objects are inert: the
--   old application never names them. The Production incident response is to disable the
--   capability and roll back the application, NOT to drop the schema.
--
-- EXISTING-DATA IMPACT
--   None. No backfill, no column change to a populated table, no data movement.
--
-- LOCK CLASS
--   CREATE TABLE / CREATE INDEX on brand-new empty relations. No lock is taken on any table the
--   running application reads or writes.


-- ── sequences ──────────────────────────────────────────────────────────────

create sequence if not exists public.yorisou_interpretation_responses_seq as bigint increment by 1 start with 1 no cycle;
do $$ begin
  execute 'revoke all on sequence public.yorisou_interpretation_responses_seq from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on sequence public.yorisou_interpretation_responses_seq from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on sequence public.yorisou_interpretation_responses_seq from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant usage, select on sequence public.yorisou_interpretation_responses_seq to service_role';
  end if;
end $$;

-- ── functions required by the table definitions below ──────────────────────

CREATE OR REPLACE FUNCTION public.yorisou_jsonb_object_length(p jsonb)
 RETURNS integer
 LANGUAGE sql
 IMMUTABLE STRICT
AS $function$
  select count(*)::integer from jsonb_object_keys(p);
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_jsonb_object_length(p jsonb) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_jsonb_object_length(p jsonb) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_jsonb_object_length(p jsonb) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_jsonb_object_length(p jsonb) to service_role';
  end if;
end $$;

-- ── tables ─────────────────────────────────────────────────────────────────

-- yorisou_assessment_attempts

do $$
declare
  v_unexpected text;
begin
  if to_regclass('public.yorisou_assessment_attempts') is null then
    create table public.yorisou_assessment_attempts (
    id uuid default gen_random_uuid() not null,
    method_id text not null,
    method_version text not null,
    owner_account_id text,
    claim_token_hash text,
    status text default 'in_progress'::text not null,
    answers jsonb default '{}'::jsonb not null,
    answered_count integer default 0 not null,
    required_count integer not null,
    entry_source text,
    started_at timestamp with time zone default now() not null,
    updated_at timestamp with time zone default now() not null,
    completed_at timestamp with time zone,
    claimed_at timestamp with time zone,
    expires_at timestamp with time zone
    );
  else
    select string_agg(name, ', ' order by name) into v_unexpected from (
      select a.attname as name from pg_attribute a
       where a.attrelid = 'public.yorisou_assessment_attempts'::regclass and a.attnum > 0 and not a.attisdropped
         and a.attname <> all (array['id', 'method_id', 'method_version', 'owner_account_id', 'claim_token_hash', 'status', 'answers', 'answered_count', 'required_count', 'entry_source', 'started_at', 'updated_at', 'completed_at', 'claimed_at', 'expires_at'])
      union all
      select c.name from unnest(array['id', 'method_id', 'method_version', 'owner_account_id', 'claim_token_hash', 'status', 'answers', 'answered_count', 'required_count', 'entry_source', 'started_at', 'updated_at', 'completed_at', 'claimed_at', 'expires_at']) c(name)
       where not exists (
         select 1 from pg_attribute a
          where a.attrelid = 'public.yorisou_assessment_attempts'::regclass and a.attname = c.name
            and a.attnum > 0 and not a.attisdropped
       )
    ) s;
    if v_unexpected is not null then
      raise exception 'POR-1: yorisou_assessment_attempts already exists with a different shape (differing column(s): %). Refusing to promote onto it.', v_unexpected;
    end if;
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_assessment_attempts_answered_count_check' and conrelid = 'public.yorisou_assessment_attempts'::regclass) then
    alter table public.yorisou_assessment_attempts add constraint yorisou_assessment_attempts_answered_count_check CHECK ((answered_count >= 0));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_assessment_attempts_claim_consistency' and conrelid = 'public.yorisou_assessment_attempts'::regclass) then
    alter table public.yorisou_assessment_attempts add constraint yorisou_assessment_attempts_claim_consistency CHECK (((owner_account_id IS NULL) = (claimed_at IS NULL)));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_assessment_attempts_completed_consistency' and conrelid = 'public.yorisou_assessment_attempts'::regclass) then
    alter table public.yorisou_assessment_attempts add constraint yorisou_assessment_attempts_completed_consistency CHECK (((status = 'completed'::text) = (completed_at IS NOT NULL)));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_assessment_attempts_completed_requires_coverage' and conrelid = 'public.yorisou_assessment_attempts'::regclass) then
    alter table public.yorisou_assessment_attempts add constraint yorisou_assessment_attempts_completed_requires_coverage CHECK (((status <> 'completed'::text) OR (answered_count = required_count)));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_assessment_attempts_count_matches_answers' and conrelid = 'public.yorisou_assessment_attempts'::regclass) then
    alter table public.yorisou_assessment_attempts add constraint yorisou_assessment_attempts_count_matches_answers CHECK ((answered_count = yorisou_jsonb_object_length(answers)));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_assessment_attempts_count_within_required' and conrelid = 'public.yorisou_assessment_attempts'::regclass) then
    alter table public.yorisou_assessment_attempts add constraint yorisou_assessment_attempts_count_within_required CHECK ((answered_count <= required_count));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_assessment_attempts_method_id_check' and conrelid = 'public.yorisou_assessment_attempts'::regclass) then
    alter table public.yorisou_assessment_attempts add constraint yorisou_assessment_attempts_method_id_check CHECK ((method_id = 'imairo-120q'::text));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_assessment_attempts_pkey' and conrelid = 'public.yorisou_assessment_attempts'::regclass) then
    alter table public.yorisou_assessment_attempts add constraint yorisou_assessment_attempts_pkey PRIMARY KEY (id);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_assessment_attempts_required_count_check' and conrelid = 'public.yorisou_assessment_attempts'::regclass) then
    alter table public.yorisou_assessment_attempts add constraint yorisou_assessment_attempts_required_count_check CHECK ((required_count > 0));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_assessment_attempts_status_check' and conrelid = 'public.yorisou_assessment_attempts'::regclass) then
    alter table public.yorisou_assessment_attempts add constraint yorisou_assessment_attempts_status_check CHECK ((status = ANY (ARRAY['in_progress'::text, 'completed'::text, 'abandoned'::text])));
  end if;
end $$;

create index if not exists yorisou_assessment_attempts_claim_idx ON public.yorisou_assessment_attempts USING btree (claim_token_hash) WHERE (claim_token_hash IS NOT NULL);

create index if not exists yorisou_assessment_attempts_expiry_idx ON public.yorisou_assessment_attempts USING btree (expires_at) WHERE ((expires_at IS NOT NULL) AND (owner_account_id IS NULL));

create index if not exists yorisou_assessment_attempts_owner_idx ON public.yorisou_assessment_attempts USING btree (owner_account_id, started_at DESC) WHERE (owner_account_id IS NOT NULL);

alter table public.yorisou_assessment_attempts enable row level security;

alter table public.yorisou_assessment_attempts force row level security;

revoke all on table public.yorisou_assessment_attempts from public;
do $$ begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on table public.yorisou_assessment_attempts from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on table public.yorisou_assessment_attempts from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant select on table public.yorisou_assessment_attempts to service_role';
  end if;
end $$;

-- yorisou_assessment_results

do $$
declare
  v_unexpected text;
begin
  if to_regclass('public.yorisou_assessment_results') is null then
    create table public.yorisou_assessment_results (
    id uuid default gen_random_uuid() not null,
    attempt_id uuid not null,
    owner_account_id text,
    method_id text not null,
    method_version text not null,
    scoring_version text,
    result_schema_version text,
    result_id text,
    overlay_id text,
    dimension_output jsonb default '{}'::jsonb not null,
    original_result_id text,
    visibility text default 'private'::text not null,
    produced_at timestamp with time zone default now() not null,
    deleted_at timestamp with time zone
    );
  else
    select string_agg(name, ', ' order by name) into v_unexpected from (
      select a.attname as name from pg_attribute a
       where a.attrelid = 'public.yorisou_assessment_results'::regclass and a.attnum > 0 and not a.attisdropped
         and a.attname <> all (array['id', 'attempt_id', 'owner_account_id', 'method_id', 'method_version', 'scoring_version', 'result_schema_version', 'result_id', 'overlay_id', 'dimension_output', 'original_result_id', 'visibility', 'produced_at', 'deleted_at'])
      union all
      select c.name from unnest(array['id', 'attempt_id', 'owner_account_id', 'method_id', 'method_version', 'scoring_version', 'result_schema_version', 'result_id', 'overlay_id', 'dimension_output', 'original_result_id', 'visibility', 'produced_at', 'deleted_at']) c(name)
       where not exists (
         select 1 from pg_attribute a
          where a.attrelid = 'public.yorisou_assessment_results'::regclass and a.attname = c.name
            and a.attnum > 0 and not a.attisdropped
       )
    ) s;
    if v_unexpected is not null then
      raise exception 'POR-1: yorisou_assessment_results already exists with a different shape (differing column(s): %). Refusing to promote onto it.', v_unexpected;
    end if;
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_assessment_results_attempt_id_fkey' and conrelid = 'public.yorisou_assessment_results'::regclass) then
    alter table public.yorisou_assessment_results add constraint yorisou_assessment_results_attempt_id_fkey FOREIGN KEY (attempt_id) REFERENCES yorisou_assessment_attempts(id) ON DELETE CASCADE;
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_assessment_results_attempt_unique' and conrelid = 'public.yorisou_assessment_results'::regclass) then
    alter table public.yorisou_assessment_results add constraint yorisou_assessment_results_attempt_unique UNIQUE (attempt_id);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_assessment_results_lifecycle_shape' and conrelid = 'public.yorisou_assessment_results'::regclass) then
    alter table public.yorisou_assessment_results add constraint yorisou_assessment_results_lifecycle_shape CHECK ((((deleted_at IS NULL) AND (result_id IS NOT NULL) AND (original_result_id IS NOT NULL)) OR ((deleted_at IS NOT NULL) AND (result_id IS NULL) AND (original_result_id IS NULL) AND (overlay_id IS NULL) AND (owner_account_id IS NULL) AND (dimension_output = '{}'::jsonb))));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_assessment_results_pkey' and conrelid = 'public.yorisou_assessment_results'::regclass) then
    alter table public.yorisou_assessment_results add constraint yorisou_assessment_results_pkey PRIMARY KEY (id);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_assessment_results_visibility_check' and conrelid = 'public.yorisou_assessment_results'::regclass) then
    alter table public.yorisou_assessment_results add constraint yorisou_assessment_results_visibility_check CHECK ((visibility = ANY (ARRAY['private'::text, 'link_shared'::text])));
  end if;
end $$;

create index if not exists yorisou_assessment_results_owner_idx ON public.yorisou_assessment_results USING btree (owner_account_id, produced_at DESC) WHERE ((owner_account_id IS NOT NULL) AND (deleted_at IS NULL));

alter table public.yorisou_assessment_results enable row level security;

alter table public.yorisou_assessment_results force row level security;

revoke all on table public.yorisou_assessment_results from public;
do $$ begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on table public.yorisou_assessment_results from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on table public.yorisou_assessment_results from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant select on table public.yorisou_assessment_results to service_role';
  end if;
end $$;

-- yorisou_interpretation_responses

do $$
declare
  v_unexpected text;
begin
  if to_regclass('public.yorisou_interpretation_responses') is null then
    create table public.yorisou_interpretation_responses (
    id uuid default gen_random_uuid() not null,
    result_row_id uuid not null,
    owner_account_id text not null,
    response_type text not null,
    corrected_result_id text,
    reason_code text,
    supersedes_response_id uuid,
    recommendation_use_permitted boolean default true not null,
    continuity_use_permitted boolean default true not null,
    source text default 'web'::text not null,
    created_at timestamp with time zone default now() not null,
    intent_nonce uuid,
    sequence_no bigint default nextval('yorisou_interpretation_responses_seq'::regclass) not null
    );
  else
    select string_agg(name, ', ' order by name) into v_unexpected from (
      select a.attname as name from pg_attribute a
       where a.attrelid = 'public.yorisou_interpretation_responses'::regclass and a.attnum > 0 and not a.attisdropped
         and a.attname <> all (array['id', 'result_row_id', 'owner_account_id', 'response_type', 'corrected_result_id', 'reason_code', 'supersedes_response_id', 'recommendation_use_permitted', 'continuity_use_permitted', 'source', 'created_at', 'intent_nonce', 'sequence_no'])
      union all
      select c.name from unnest(array['id', 'result_row_id', 'owner_account_id', 'response_type', 'corrected_result_id', 'reason_code', 'supersedes_response_id', 'recommendation_use_permitted', 'continuity_use_permitted', 'source', 'created_at', 'intent_nonce', 'sequence_no']) c(name)
       where not exists (
         select 1 from pg_attribute a
          where a.attrelid = 'public.yorisou_interpretation_responses'::regclass and a.attname = c.name
            and a.attnum > 0 and not a.attisdropped
       )
    ) s;
    if v_unexpected is not null then
      raise exception 'POR-1: yorisou_interpretation_responses already exists with a different shape (differing column(s): %). Refusing to promote onto it.', v_unexpected;
    end if;
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_interpretation_responses_correction_shape' and conrelid = 'public.yorisou_interpretation_responses'::regclass) then
    alter table public.yorisou_interpretation_responses add constraint yorisou_interpretation_responses_correction_shape CHECK (((response_type = 'corrected'::text) = (corrected_result_id IS NOT NULL)));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_interpretation_responses_pkey' and conrelid = 'public.yorisou_interpretation_responses'::regclass) then
    alter table public.yorisou_interpretation_responses add constraint yorisou_interpretation_responses_pkey PRIMARY KEY (id);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_interpretation_responses_reason_code_check' and conrelid = 'public.yorisou_interpretation_responses'::regclass) then
    alter table public.yorisou_interpretation_responses add constraint yorisou_interpretation_responses_reason_code_check CHECK (((reason_code IS NULL) OR (reason_code = ANY (ARRAY['not_me_now'::text, 'partly_true'::text, 'changed_recently'::text, 'wrong_emphasis'::text, 'other_bounded'::text]))));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_interpretation_responses_response_type_check' and conrelid = 'public.yorisou_interpretation_responses'::regclass) then
    alter table public.yorisou_interpretation_responses add constraint yorisou_interpretation_responses_response_type_check CHECK ((response_type = ANY (ARRAY['confirmed'::text, 'corrected'::text, 'rejected'::text, 'deferred'::text])));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_interpretation_responses_result_row_id_fkey' and conrelid = 'public.yorisou_interpretation_responses'::regclass) then
    alter table public.yorisou_interpretation_responses add constraint yorisou_interpretation_responses_result_row_id_fkey FOREIGN KEY (result_row_id) REFERENCES yorisou_assessment_results(id) ON DELETE CASCADE;
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_interpretation_responses_source_check' and conrelid = 'public.yorisou_interpretation_responses'::regclass) then
    alter table public.yorisou_interpretation_responses add constraint yorisou_interpretation_responses_source_check CHECK ((source = ANY (ARRAY['web'::text, 'line'::text, 'import'::text])));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_interpretation_responses_supersedes_response_id_fkey' and conrelid = 'public.yorisou_interpretation_responses'::regclass) then
    alter table public.yorisou_interpretation_responses add constraint yorisou_interpretation_responses_supersedes_response_id_fkey FOREIGN KEY (supersedes_response_id) REFERENCES yorisou_interpretation_responses(id);
  end if;
end $$;

create unique index if not exists yorisou_interpretation_responses_intent_idem ON public.yorisou_interpretation_responses USING btree (result_row_id, owner_account_id, intent_nonce) WHERE (intent_nonce IS NOT NULL);

create index if not exists yorisou_interpretation_responses_latest ON public.yorisou_interpretation_responses USING btree (result_row_id, sequence_no DESC);

create index if not exists yorisou_interpretation_responses_owner_idx ON public.yorisou_interpretation_responses USING btree (owner_account_id, created_at DESC);

create index if not exists yorisou_interpretation_responses_result_idx ON public.yorisou_interpretation_responses USING btree (result_row_id, created_at DESC);

alter table public.yorisou_interpretation_responses enable row level security;

alter table public.yorisou_interpretation_responses force row level security;

revoke all on table public.yorisou_interpretation_responses from public;
do $$ begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on table public.yorisou_interpretation_responses from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on table public.yorisou_interpretation_responses from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant select on table public.yorisou_interpretation_responses to service_role';
  end if;
end $$;

-- ── functions ──────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.yorisou_interpretation_supersedes_same_result()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
declare v_other uuid;
begin
  if new.supersedes_response_id is null then return new; end if;
  select result_row_id into v_other from public.yorisou_interpretation_responses
   where id = new.supersedes_response_id;
  if v_other is null or v_other <> new.result_row_id then
    raise exception 'response_supersession_cross_result';
  end if;
  return new;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_interpretation_supersedes_same_result() from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_interpretation_supersedes_same_result() from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_interpretation_supersedes_same_result() from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_interpretation_supersedes_same_result() to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_interpretation_responses_append_only()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  if tg_op = 'DELETE'
     and coalesce(current_setting('yorisou.erasure_context', true), '') = old.result_row_id::text then
    return old;  -- governed erasure of exactly this result
  end if;
  raise exception 'yorisou_interpretation_responses_is_append_only';
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_interpretation_responses_append_only() from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_interpretation_responses_append_only() from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_interpretation_responses_append_only() from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_interpretation_responses_append_only() to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_interpretation_respond(p_result_row_id uuid, p_owner_account_id text, p_response_type text, p_corrected_result_id text DEFAULT NULL::text, p_reason_code text DEFAULT NULL::text, p_source text DEFAULT 'web'::text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_owner text; v_deleted timestamptz; v_prev uuid; v_id uuid; v_permit boolean;
begin
  select r.owner_account_id, r.deleted_at into v_owner, v_deleted
    from public.yorisou_assessment_results r where r.id = p_result_row_id;
  if not found then raise exception 'result_not_found'; end if;
  -- An erased result can never receive new responses.
  if v_deleted is not null then raise exception 'result_erased'; end if;
  if v_owner is null or v_owner <> p_owner_account_id then raise exception 'result_not_owned'; end if;

  select id into v_prev from public.yorisou_interpretation_responses
   where result_row_id = p_result_row_id order by created_at desc limit 1;

  -- ONLY an explicit confirmation or correction permits downstream use.
  -- rejected AND deferred both withhold it; silence never grants it.
  v_permit := p_response_type in ('confirmed','corrected');

  insert into public.yorisou_interpretation_responses
    (result_row_id, owner_account_id, response_type, corrected_result_id, reason_code,
     supersedes_response_id, recommendation_use_permitted, continuity_use_permitted, source)
  values
    (p_result_row_id, p_owner_account_id, p_response_type, p_corrected_result_id, p_reason_code,
     v_prev, v_permit, v_permit, p_source)
  returning id into v_id;
  return v_id;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_interpretation_respond(p_result_row_id uuid, p_owner_account_id text, p_response_type text, p_corrected_result_id text, p_reason_code text, p_source text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_interpretation_respond(p_result_row_id uuid, p_owner_account_id text, p_response_type text, p_corrected_result_id text, p_reason_code text, p_source text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_interpretation_respond(p_result_row_id uuid, p_owner_account_id text, p_response_type text, p_corrected_result_id text, p_reason_code text, p_source text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_interpretation_respond(p_result_row_id uuid, p_owner_account_id text, p_response_type text, p_corrected_result_id text, p_reason_code text, p_source text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_interpretation_respond(p_result_row_id uuid, p_owner_account_id text, p_response_type text, p_corrected_result_id text DEFAULT NULL::text, p_reason_code text DEFAULT NULL::text, p_source text DEFAULT 'web'::text, p_intent_nonce uuid DEFAULT NULL::uuid)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_owner text; v_deleted timestamptz; v_prev uuid; v_id uuid; v_permit boolean;
        v_existing public.yorisou_interpretation_responses%rowtype;
begin
  select r.owner_account_id, r.deleted_at into v_owner, v_deleted
    from public.yorisou_assessment_results r where r.id = p_result_row_id;
  if not found then raise exception 'result_not_found'; end if;
  if v_deleted is not null then raise exception 'result_erased'; end if;
  if v_owner is null or v_owner <> p_owner_account_id then raise exception 'result_not_owned'; end if;

  if p_intent_nonce is not null then
    select * into v_existing from public.yorisou_interpretation_responses
     where result_row_id = p_result_row_id
       and owner_account_id = p_owner_account_id
       and intent_nonce = p_intent_nonce;
    if found then
      if v_existing.response_type      is distinct from p_response_type
         or v_existing.corrected_result_id is distinct from p_corrected_result_id
         or v_existing.reason_code     is distinct from p_reason_code
         or v_existing.source          is distinct from p_source then
        raise exception 'interpretation_intent_conflict';
      end if;
      return v_existing.id;
    end if;
  end if;

  select id into v_prev from public.yorisou_interpretation_responses
   where result_row_id = p_result_row_id order by sequence_no desc limit 1;

  v_permit := p_response_type in ('confirmed','corrected');

  begin
    insert into public.yorisou_interpretation_responses
      (result_row_id, owner_account_id, response_type, corrected_result_id, reason_code,
       supersedes_response_id, recommendation_use_permitted, continuity_use_permitted, source,
       intent_nonce)
    values
      (p_result_row_id, p_owner_account_id, p_response_type, p_corrected_result_id, p_reason_code,
       v_prev, v_permit, v_permit, p_source, p_intent_nonce)
    returning id into v_id;
  exception when unique_violation then
    select * into v_existing from public.yorisou_interpretation_responses
     where result_row_id = p_result_row_id
       and owner_account_id = p_owner_account_id
       and intent_nonce = p_intent_nonce;
    if not found then raise; end if;
    if v_existing.response_type      is distinct from p_response_type
       or v_existing.corrected_result_id is distinct from p_corrected_result_id
       or v_existing.reason_code     is distinct from p_reason_code
       or v_existing.source          is distinct from p_source then
      raise exception 'interpretation_intent_conflict';
    end if;
    return v_existing.id;
  end;

  return v_id;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_interpretation_respond(p_result_row_id uuid, p_owner_account_id text, p_response_type text, p_corrected_result_id text, p_reason_code text, p_source text, p_intent_nonce uuid) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_interpretation_respond(p_result_row_id uuid, p_owner_account_id text, p_response_type text, p_corrected_result_id text, p_reason_code text, p_source text, p_intent_nonce uuid) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_interpretation_respond(p_result_row_id uuid, p_owner_account_id text, p_response_type text, p_corrected_result_id text, p_reason_code text, p_source text, p_intent_nonce uuid) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_interpretation_respond(p_result_row_id uuid, p_owner_account_id text, p_response_type text, p_corrected_result_id text, p_reason_code text, p_source text, p_intent_nonce uuid) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_attempt_start(p_method_id text, p_method_version text, p_required_count integer, p_claim_token_hash text, p_entry_source text DEFAULT NULL::text, p_ttl_hours integer DEFAULT 72)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_id uuid;
begin
  if p_claim_token_hash is null or length(p_claim_token_hash) < 32 then
    raise exception 'attempt_claim_token_required';
  end if;
  insert into public.yorisou_assessment_attempts
    (method_id, method_version, required_count, claim_token_hash, entry_source, expires_at)
  values
    (p_method_id, p_method_version, p_required_count, p_claim_token_hash, p_entry_source,
     now() + make_interval(hours => greatest(0, coalesce(p_ttl_hours, 72))))
  returning id into v_id;
  return v_id;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_attempt_start(p_method_id text, p_method_version text, p_required_count integer, p_claim_token_hash text, p_entry_source text, p_ttl_hours integer) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_attempt_start(p_method_id text, p_method_version text, p_required_count integer, p_claim_token_hash text, p_entry_source text, p_ttl_hours integer) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_attempt_start(p_method_id text, p_method_version text, p_required_count integer, p_claim_token_hash text, p_entry_source text, p_ttl_hours integer) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_attempt_start(p_method_id text, p_method_version text, p_required_count integer, p_claim_token_hash text, p_entry_source text, p_ttl_hours integer) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_attempt_save_progress(p_attempt_id uuid, p_claim_token_hash text, p_owner_account_id text, p_answers jsonb, p_answered_count integer)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_rows integer;
begin
  update public.yorisou_assessment_attempts a
     set answers = p_answers, answered_count = p_answered_count, updated_at = now()
   where a.id = p_attempt_id
     and a.status = 'in_progress'
     and (
       (a.owner_account_id is null and a.claim_token_hash is not null
        and a.claim_token_hash = p_claim_token_hash
        and (a.expires_at is null or a.expires_at > now()))   -- expiry enforced here
       or (a.owner_account_id is not null and a.owner_account_id = p_owner_account_id)
     );
  get diagnostics v_rows = row_count;
  if v_rows = 0 then
    -- Distinguish expiry so the UI can explain it rather than showing a generic failure.
    if exists (select 1 from public.yorisou_assessment_attempts a
                where a.id = p_attempt_id and a.owner_account_id is null
                  and a.expires_at is not null and a.expires_at <= now()) then
      raise exception 'attempt_expired';
    end if;
    raise exception 'attempt_not_found_or_not_writable';
  end if;
  return p_answered_count;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_attempt_save_progress(p_attempt_id uuid, p_claim_token_hash text, p_owner_account_id text, p_answers jsonb, p_answered_count integer) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_attempt_save_progress(p_attempt_id uuid, p_claim_token_hash text, p_owner_account_id text, p_answers jsonb, p_answered_count integer) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_attempt_save_progress(p_attempt_id uuid, p_claim_token_hash text, p_owner_account_id text, p_answers jsonb, p_answered_count integer) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_attempt_save_progress(p_attempt_id uuid, p_claim_token_hash text, p_owner_account_id text, p_answers jsonb, p_answered_count integer) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_attempt_complete(p_attempt_id uuid, p_claim_token_hash text, p_owner_account_id text, p_answers jsonb, p_answered_count integer, p_result_id text, p_overlay_id text, p_dimension_output jsonb, p_scoring_version text, p_result_schema_version text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_attempt public.yorisou_assessment_attempts%rowtype; v_existing uuid; v_result_row uuid;
begin
  -- CANONICAL ENVELOPE GUARD: exactly one key, exactly the approved version.
  if p_dimension_output is null
     or jsonb_typeof(p_dimension_output) <> 'object'
     or (select count(*) from jsonb_object_keys(p_dimension_output)) <> 1
     or p_dimension_output->>'v' is distinct from 'pds-v1' then
    raise exception 'assessment_persisted_envelope_invalid';
  end if;

  select * into v_attempt from public.yorisou_assessment_attempts a
   where a.id = p_attempt_id
     and (
       (a.owner_account_id is null and a.claim_token_hash is not null and a.claim_token_hash = p_claim_token_hash)
       or (a.owner_account_id is not null and a.owner_account_id = p_owner_account_id)
     )
   for update;
  if not found then raise exception 'attempt_not_found_or_not_writable'; end if;

  select r.id into v_existing from public.yorisou_assessment_results r where r.attempt_id = p_attempt_id;
  if v_existing is not null then return v_existing; end if;

  if v_attempt.owner_account_id is null
     and v_attempt.expires_at is not null and v_attempt.expires_at <= now() then
    raise exception 'attempt_expired';
  end if;
  if p_answered_count < v_attempt.required_count then raise exception 'attempt_incomplete_coverage'; end if;

  update public.yorisou_assessment_attempts
     set answers = p_answers, answered_count = p_answered_count,
         status = 'completed', completed_at = now(), updated_at = now()
   where id = p_attempt_id;

  insert into public.yorisou_assessment_results
    (attempt_id, owner_account_id, method_id, method_version, scoring_version,
     result_schema_version, result_id, overlay_id, dimension_output, original_result_id)
  values
    (p_attempt_id, v_attempt.owner_account_id, v_attempt.method_id, v_attempt.method_version,
     p_scoring_version, p_result_schema_version, p_result_id, p_overlay_id,
     p_dimension_output, p_result_id)
  returning id into v_result_row;
  return v_result_row;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_attempt_complete(p_attempt_id uuid, p_claim_token_hash text, p_owner_account_id text, p_answers jsonb, p_answered_count integer, p_result_id text, p_overlay_id text, p_dimension_output jsonb, p_scoring_version text, p_result_schema_version text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_attempt_complete(p_attempt_id uuid, p_claim_token_hash text, p_owner_account_id text, p_answers jsonb, p_answered_count integer, p_result_id text, p_overlay_id text, p_dimension_output jsonb, p_scoring_version text, p_result_schema_version text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_attempt_complete(p_attempt_id uuid, p_claim_token_hash text, p_owner_account_id text, p_answers jsonb, p_answered_count integer, p_result_id text, p_overlay_id text, p_dimension_output jsonb, p_scoring_version text, p_result_schema_version text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_attempt_complete(p_attempt_id uuid, p_claim_token_hash text, p_owner_account_id text, p_answers jsonb, p_answered_count integer, p_result_id text, p_overlay_id text, p_dimension_output jsonb, p_scoring_version text, p_result_schema_version text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_attempt_claim(p_attempt_id uuid, p_claim_token_hash text, p_owner_account_id text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_attempt public.yorisou_assessment_attempts%rowtype;
        v_result uuid;
begin
  if p_owner_account_id is null or length(p_owner_account_id) = 0 then
    raise exception 'claim_owner_required';
  end if;

  select * into v_attempt from public.yorisou_assessment_attempts a
   where a.id = p_attempt_id for update;
  if not found then raise exception 'attempt_not_found'; end if;

  -- Already claimed by this same account -> idempotent success.
  if v_attempt.owner_account_id is not null then
    if v_attempt.owner_account_id = p_owner_account_id then
      select r.id into v_result from public.yorisou_assessment_results r where r.attempt_id = p_attempt_id;
      return v_result;
    end if;
    raise exception 'attempt_already_claimed_by_another_owner';
  end if;

  if v_attempt.claim_token_hash is null or v_attempt.claim_token_hash <> p_claim_token_hash then
    raise exception 'claim_token_invalid';
  end if;
  if v_attempt.expires_at is not null and v_attempt.expires_at < now() then
    raise exception 'claim_token_expired';
  end if;

  update public.yorisou_assessment_attempts
     set owner_account_id = p_owner_account_id,
         claimed_at       = now(),
         claim_token_hash = null,   -- single use
         expires_at       = null,   -- claimed attempts do not expire
         updated_at       = now()
   where id = p_attempt_id;

  update public.yorisou_assessment_results
     set owner_account_id = p_owner_account_id
   where attempt_id = p_attempt_id
  returning id into v_result;

  return v_result;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_attempt_claim(p_attempt_id uuid, p_claim_token_hash text, p_owner_account_id text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_attempt_claim(p_attempt_id uuid, p_claim_token_hash text, p_owner_account_id text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_attempt_claim(p_attempt_id uuid, p_claim_token_hash text, p_owner_account_id text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_attempt_claim(p_attempt_id uuid, p_claim_token_hash text, p_owner_account_id text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_attempt_abandon(p_attempt_id uuid, p_claim_token_hash text, p_owner_account_id text, p_reason text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_rows integer;
begin
  if p_reason not in ('user_restarted','expired','erased') then
    raise exception 'attempt_abandon_reason_invalid';
  end if;
  update public.yorisou_assessment_attempts a
     set status = 'abandoned',
         answers = '{}'::jsonb,
         answered_count = 0,
         claim_token_hash = null,   -- the old credential can never be replayed
         completed_at = null,
         entry_source = p_reason,   -- bounded, non-identifying abandonment classification
         updated_at = now()
   where a.id = p_attempt_id
     and a.status = 'in_progress'
     and (
       (a.owner_account_id is null and a.claim_token_hash = p_claim_token_hash)
       or (a.owner_account_id is not null and a.owner_account_id = p_owner_account_id)
     );
  get diagnostics v_rows = row_count;
  return v_rows > 0;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_attempt_abandon(p_attempt_id uuid, p_claim_token_hash text, p_owner_account_id text, p_reason text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_attempt_abandon(p_attempt_id uuid, p_claim_token_hash text, p_owner_account_id text, p_reason text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_attempt_abandon(p_attempt_id uuid, p_claim_token_hash text, p_owner_account_id text, p_reason text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_attempt_abandon(p_attempt_id uuid, p_claim_token_hash text, p_owner_account_id text, p_reason text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_assessment_result_delete(p_result_row_id uuid, p_owner_account_id text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_rows integer;
begin
  update public.yorisou_assessment_results
     set deleted_at = now(), dimension_output = '{}'::jsonb
   where id = p_result_row_id and owner_account_id = p_owner_account_id and deleted_at is null;
  get diagnostics v_rows = row_count;
  return v_rows > 0;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_assessment_result_delete(p_result_row_id uuid, p_owner_account_id text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_assessment_result_delete(p_result_row_id uuid, p_owner_account_id text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_assessment_result_delete(p_result_row_id uuid, p_owner_account_id text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_assessment_result_delete(p_result_row_id uuid, p_owner_account_id text) to service_role';
  end if;
end $$;

-- ── triggers ───────────────────────────────────────────────────────────────

do $$ begin
  if not exists (
    select 1 from pg_trigger t join pg_class c on c.oid = t.tgrelid
     where c.relname = 'yorisou_interpretation_responses' and t.tgname = 'yorisou_interpretation_responses_no_update' and not t.tgisinternal
  ) then
    execute 'create trigger yorisou_interpretation_responses_no_update BEFORE DELETE OR UPDATE ON public.yorisou_interpretation_responses FOR EACH ROW EXECUTE FUNCTION yorisou_interpretation_responses_append_only()';
  end if;
end $$;

do $$ begin
  if not exists (
    select 1 from pg_trigger t join pg_class c on c.oid = t.tgrelid
     where c.relname = 'yorisou_interpretation_responses' and t.tgname = 'yorisou_interpretation_supersedes_guard' and not t.tgisinternal
  ) then
    execute 'create trigger yorisou_interpretation_supersedes_guard BEFORE INSERT ON public.yorisou_interpretation_responses FOR EACH ROW EXECUTE FUNCTION yorisou_interpretation_supersedes_same_result()';
  end if;
end $$;
