-- POR-1 PROMOTION P2 — Canonical recommendation sets, items and actions
--
-- PRODUCTION_LINEAGE. Generated by scripts/por1/compile-promotion.mjs from the FINAL Preview
-- catalogue — not from the 24-migration Preview history. Only the last definition of a
-- `create or replace` chain is live, so promoting the history would promote bodies that were
-- already replaced, including the ones replaced because they were wrong.
--
-- Regenerate and verify with:  npm run por1:promotion-check
--
-- CONTENTS
--   tables 3 · sequences 1 · functions 3 · triggers 0
--
-- APPLY SEMANTICS
--   Every statement is guarded (`if not exists` / catalogue probe), so a partial failure can be
--   retried without a human reconstructing which half applied.
--
-- ROLLBACK CLASS
--   SCHEMA_REVERSIBLE_WHILE_FLAGS_OFF — additive only. Nothing here alters or drops an existing
--   Production object, so with the POR-1 capability controls unset these objects are inert: the
--   old application never names them. The Production incident response is to disable the
--   capability and roll back the application, NOT to drop the schema.
--
-- EXISTING-DATA IMPACT
--   None. No backfill, no column change to a populated table, no data movement.
--
-- LOCK CLASS
--   CREATE TABLE / CREATE INDEX on brand-new empty relations. No lock is taken on any table the
--   running application reads or writes.


-- ── sequences ──────────────────────────────────────────────────────────────

create sequence if not exists public.yorisou_recommendation_actions_seq as bigint increment by 1 start with 1 no cycle;
do $$ begin
  execute 'revoke all on sequence public.yorisou_recommendation_actions_seq from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on sequence public.yorisou_recommendation_actions_seq from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on sequence public.yorisou_recommendation_actions_seq from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant usage, select on sequence public.yorisou_recommendation_actions_seq to service_role';
  end if;
end $$;

-- ── tables ─────────────────────────────────────────────────────────────────

-- yorisou_canonical_recommendation_sets

create table if not exists public.yorisou_canonical_recommendation_sets (
  id uuid default gen_random_uuid() not null,
  result_row_id uuid not null,
  owner_account_id text not null,
  accepted_result_id text not null,
  original_result_id text,
  eligibility_basis text not null,
  content_version text not null,
  source_surface text not null,
  generated_at timestamp with time zone default now() not null,
  lifecycle_state text default 'active'::text not null,
  created_at timestamp with time zone default now() not null
);

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_recommendation_sets_eligibility_basis_check' and conrelid = 'public.yorisou_canonical_recommendation_sets'::regclass) then
    alter table public.yorisou_canonical_recommendation_sets add constraint yorisou_canonical_recommendation_sets_eligibility_basis_check CHECK ((eligibility_basis = ANY (ARRAY['confirmed'::text, 'corrected'::text])));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_recommendation_sets_lifecycle_state_check' and conrelid = 'public.yorisou_canonical_recommendation_sets'::regclass) then
    alter table public.yorisou_canonical_recommendation_sets add constraint yorisou_canonical_recommendation_sets_lifecycle_state_check CHECK ((lifecycle_state = ANY (ARRAY['active'::text, 'superseded'::text, 'withdrawn'::text])));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_recommendation_sets_pkey' and conrelid = 'public.yorisou_canonical_recommendation_sets'::regclass) then
    alter table public.yorisou_canonical_recommendation_sets add constraint yorisou_canonical_recommendation_sets_pkey PRIMARY KEY (id);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_recommendation_sets_result_row_id_fkey' and conrelid = 'public.yorisou_canonical_recommendation_sets'::regclass) then
    alter table public.yorisou_canonical_recommendation_sets add constraint yorisou_canonical_recommendation_sets_result_row_id_fkey FOREIGN KEY (result_row_id) REFERENCES yorisou_assessment_results(id) ON DELETE CASCADE;
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_recommendation_sets_source_surface_check' and conrelid = 'public.yorisou_canonical_recommendation_sets'::regclass) then
    alter table public.yorisou_canonical_recommendation_sets add constraint yorisou_canonical_recommendation_sets_source_surface_check CHECK ((source_surface = ANY (ARRAY['result'::text, 'recommendations'::text, 'graph'::text, 'private_state'::text, 'line'::text])));
  end if;
end $$;

create index if not exists yorisou_canonical_recommendation_sets_owner ON public.yorisou_canonical_recommendation_sets USING btree (owner_account_id, result_row_id, generated_at DESC);

alter table public.yorisou_canonical_recommendation_sets enable row level security;

alter table public.yorisou_canonical_recommendation_sets force row level security;

revoke all on table public.yorisou_canonical_recommendation_sets from public;
do $$ begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on table public.yorisou_canonical_recommendation_sets from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on table public.yorisou_canonical_recommendation_sets from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant select on table public.yorisou_canonical_recommendation_sets to service_role';
  end if;
end $$;

-- yorisou_canonical_recommendation_items

create table if not exists public.yorisou_canonical_recommendation_items (
  id uuid default gen_random_uuid() not null,
  set_id uuid not null,
  owner_account_id text not null,
  result_row_id uuid not null,
  rank integer not null,
  recommendation_key text not null,
  object_type text not null,
  source_class text not null,
  commercial_status text not null,
  reason_code text not null,
  limitations_code text not null,
  created_at timestamp with time zone default now() not null
);

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_recommendation_items_commercial_status_check' and conrelid = 'public.yorisou_canonical_recommendation_items'::regclass) then
    alter table public.yorisou_canonical_recommendation_items add constraint yorisou_canonical_recommendation_items_commercial_status_check CHECK ((commercial_status = ANY (ARRAY['none'::text, 'disclosed_sponsored'::text, 'disclosed_affiliate'::text])));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_recommendation_items_object_type_check' and conrelid = 'public.yorisou_canonical_recommendation_items'::regclass) then
    alter table public.yorisou_canonical_recommendation_items add constraint yorisou_canonical_recommendation_items_object_type_check CHECK ((object_type = ANY (ARRAY['resource'::text, 'experience_card'::text, 'internal_route'::text])));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_recommendation_items_pkey' and conrelid = 'public.yorisou_canonical_recommendation_items'::regclass) then
    alter table public.yorisou_canonical_recommendation_items add constraint yorisou_canonical_recommendation_items_pkey PRIMARY KEY (id);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_recommendation_items_rank_check' and conrelid = 'public.yorisou_canonical_recommendation_items'::regclass) then
    alter table public.yorisou_canonical_recommendation_items add constraint yorisou_canonical_recommendation_items_rank_check CHECK (((rank >= 1) AND (rank <= 5)));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_recommendation_items_result_row_id_fkey' and conrelid = 'public.yorisou_canonical_recommendation_items'::regclass) then
    alter table public.yorisou_canonical_recommendation_items add constraint yorisou_canonical_recommendation_items_result_row_id_fkey FOREIGN KEY (result_row_id) REFERENCES yorisou_assessment_results(id) ON DELETE CASCADE;
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_recommendation_items_set_id_fkey' and conrelid = 'public.yorisou_canonical_recommendation_items'::regclass) then
    alter table public.yorisou_canonical_recommendation_items add constraint yorisou_canonical_recommendation_items_set_id_fkey FOREIGN KEY (set_id) REFERENCES yorisou_canonical_recommendation_sets(id) ON DELETE CASCADE;
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_recommendation_items_set_id_rank_key' and conrelid = 'public.yorisou_canonical_recommendation_items'::regclass) then
    alter table public.yorisou_canonical_recommendation_items add constraint yorisou_canonical_recommendation_items_set_id_rank_key UNIQUE (set_id, rank);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_recommendation_items_set_id_recommendation_ke' and conrelid = 'public.yorisou_canonical_recommendation_items'::regclass) then
    alter table public.yorisou_canonical_recommendation_items add constraint yorisou_canonical_recommendation_items_set_id_recommendation_ke UNIQUE (set_id, recommendation_key);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_recommendation_items_source_class_check' and conrelid = 'public.yorisou_canonical_recommendation_items'::regclass) then
    alter table public.yorisou_canonical_recommendation_items add constraint yorisou_canonical_recommendation_items_source_class_check CHECK ((source_class = ANY (ARRAY['yorisou_internal'::text, 'public_information'::text, 'partner_nonpaid'::text, 'partner_sponsored'::text])));
  end if;
end $$;

alter table public.yorisou_canonical_recommendation_items enable row level security;

alter table public.yorisou_canonical_recommendation_items force row level security;

revoke all on table public.yorisou_canonical_recommendation_items from public;
do $$ begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on table public.yorisou_canonical_recommendation_items from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on table public.yorisou_canonical_recommendation_items from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant select on table public.yorisou_canonical_recommendation_items to service_role';
  end if;
end $$;

-- yorisou_canonical_recommendation_actions

create table if not exists public.yorisou_canonical_recommendation_actions (
  id uuid default gen_random_uuid() not null,
  item_id uuid not null,
  set_id uuid not null,
  result_row_id uuid not null,
  owner_account_id text not null,
  action text not null,
  source_surface text not null,
  intent_nonce uuid,
  created_at timestamp with time zone default now() not null,
  sequence_no bigint default nextval('yorisou_recommendation_actions_seq'::regclass) not null
);

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_recommendation_actions_action_check' and conrelid = 'public.yorisou_canonical_recommendation_actions'::regclass) then
    alter table public.yorisou_canonical_recommendation_actions add constraint yorisou_canonical_recommendation_actions_action_check CHECK ((action = ANY (ARRAY['saved'::text, 'try_intent'::text, 'tried'::text, 'helpful'::text, 'not_helpful'::text, 'not_relevant'::text, 'hidden'::text, 'reported'::text, 'resource_opened'::text])));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_recommendation_actions_item_id_fkey' and conrelid = 'public.yorisou_canonical_recommendation_actions'::regclass) then
    alter table public.yorisou_canonical_recommendation_actions add constraint yorisou_canonical_recommendation_actions_item_id_fkey FOREIGN KEY (item_id) REFERENCES yorisou_canonical_recommendation_items(id) ON DELETE CASCADE;
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_recommendation_actions_pkey' and conrelid = 'public.yorisou_canonical_recommendation_actions'::regclass) then
    alter table public.yorisou_canonical_recommendation_actions add constraint yorisou_canonical_recommendation_actions_pkey PRIMARY KEY (id);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_recommendation_actions_result_row_id_fkey' and conrelid = 'public.yorisou_canonical_recommendation_actions'::regclass) then
    alter table public.yorisou_canonical_recommendation_actions add constraint yorisou_canonical_recommendation_actions_result_row_id_fkey FOREIGN KEY (result_row_id) REFERENCES yorisou_assessment_results(id) ON DELETE CASCADE;
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_recommendation_actions_set_id_fkey' and conrelid = 'public.yorisou_canonical_recommendation_actions'::regclass) then
    alter table public.yorisou_canonical_recommendation_actions add constraint yorisou_canonical_recommendation_actions_set_id_fkey FOREIGN KEY (set_id) REFERENCES yorisou_canonical_recommendation_sets(id) ON DELETE CASCADE;
  end if;
end $$;

create unique index if not exists yorisou_canonical_recommendation_actions_idem ON public.yorisou_canonical_recommendation_actions USING btree (item_id, owner_account_id, intent_nonce) WHERE (intent_nonce IS NOT NULL);

create index if not exists yorisou_canonical_recommendation_actions_owner ON public.yorisou_canonical_recommendation_actions USING btree (owner_account_id, result_row_id, created_at DESC);

create index if not exists yorisou_canonical_recommendation_actions_seq_idx ON public.yorisou_canonical_recommendation_actions USING btree (item_id, sequence_no DESC);

alter table public.yorisou_canonical_recommendation_actions enable row level security;

alter table public.yorisou_canonical_recommendation_actions force row level security;

revoke all on table public.yorisou_canonical_recommendation_actions from public;
do $$ begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on table public.yorisou_canonical_recommendation_actions from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on table public.yorisou_canonical_recommendation_actions from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant select on table public.yorisou_canonical_recommendation_actions to service_role';
  end if;
end $$;

-- ── functions ──────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.yorisou_canonical_recommendation_eligibility(p_result_row_id uuid, p_owner_account_id text)
 RETURNS TABLE(accepted_result_id text, original_result_id text, basis text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_res public.yorisou_assessment_results%rowtype; v_resp public.yorisou_interpretation_responses%rowtype;
begin
  select * into v_res from public.yorisou_assessment_results
   where id = p_result_row_id and owner_account_id = p_owner_account_id and deleted_at is null;
  if not found then raise exception 'result_not_found'; end if;

  if v_res.dimension_output is null
     or (select count(*) from jsonb_object_keys(v_res.dimension_output)) <> 1
     or v_res.dimension_output->>'v' is distinct from 'pds-v1' then
    raise exception 'result_envelope_invalid';
  end if;

  select * into v_resp from public.yorisou_interpretation_responses
   where result_row_id = p_result_row_id order by sequence_no desc limit 1;
  if not found then raise exception 'recommendation_not_permitted'; end if;
  if v_resp.response_type not in ('confirmed','corrected') then raise exception 'recommendation_not_permitted'; end if;
  if v_resp.recommendation_use_permitted is not true then raise exception 'recommendation_not_permitted'; end if;

  accepted_result_id := case when v_resp.response_type = 'corrected'
                             then v_resp.corrected_result_id else v_res.result_id end;
  if accepted_result_id is null then raise exception 'recommendation_not_permitted'; end if;
  original_result_id := v_res.original_result_id;
  basis := v_resp.response_type;
  return next;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_canonical_recommendation_eligibility(p_result_row_id uuid, p_owner_account_id text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_canonical_recommendation_eligibility(p_result_row_id uuid, p_owner_account_id text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_canonical_recommendation_eligibility(p_result_row_id uuid, p_owner_account_id text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_canonical_recommendation_eligibility(p_result_row_id uuid, p_owner_account_id text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_canonical_recommendation_act(p_item_id uuid, p_owner_account_id text, p_action text, p_source_surface text, p_intent_nonce uuid DEFAULT NULL::uuid, p_result_row_id uuid DEFAULT NULL::uuid)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_item public.yorisou_canonical_recommendation_items%rowtype;
        v_set public.yorisou_canonical_recommendation_sets%rowtype;
        v_existing public.yorisou_canonical_recommendation_actions%rowtype; v_id uuid;
begin
  select * into v_item from public.yorisou_canonical_recommendation_items
   where id = p_item_id and owner_account_id = p_owner_account_id;
  if not found then raise exception 'recommendation_item_not_found'; end if;

  select * into v_set from public.yorisou_canonical_recommendation_sets
   where id = v_item.set_id and owner_account_id = p_owner_account_id;
  if not found then raise exception 'recommendation_item_not_found'; end if;

  if p_result_row_id is not null then
    if v_item.result_row_id is distinct from p_result_row_id
       or v_set.result_row_id is distinct from p_result_row_id then
      raise exception 'recommendation_item_not_found';   -- concealed
    end if;
  end if;

  perform public.yorisou_canonical_recommendation_eligibility(v_item.result_row_id, p_owner_account_id);

  if p_intent_nonce is not null then
    select * into v_existing from public.yorisou_canonical_recommendation_actions
     where item_id = p_item_id and owner_account_id = p_owner_account_id
       and intent_nonce = p_intent_nonce;
    if found then
      -- A replay must be a replay of the SAME request. Returning the stored row for a different
      -- action would tell the caller their new choice succeeded when it was never recorded.
      if v_existing.action        is distinct from p_action
         or v_existing.source_surface is distinct from p_source_surface
         or v_existing.result_row_id  is distinct from v_item.result_row_id then
        raise exception 'recommendation_action_intent_conflict';
      end if;
      return v_existing.id;
    end if;
  end if;

  begin
    insert into public.yorisou_canonical_recommendation_actions
      (item_id, set_id, result_row_id, owner_account_id, action, source_surface, intent_nonce)
    values
      (p_item_id, v_item.set_id, v_item.result_row_id, p_owner_account_id, p_action,
       p_source_surface, p_intent_nonce)
    returning id into v_id;
  exception when unique_violation then
    -- Concurrent same-nonce request won. Re-read and apply the SAME comparison: a concurrent
    -- conflicting payload must not be absorbed just because it lost the race.
    select * into v_existing from public.yorisou_canonical_recommendation_actions
     where item_id = p_item_id and owner_account_id = p_owner_account_id
       and intent_nonce = p_intent_nonce;
    if not found then raise; end if;
    if v_existing.action        is distinct from p_action
       or v_existing.source_surface is distinct from p_source_surface
       or v_existing.result_row_id  is distinct from v_item.result_row_id then
      raise exception 'recommendation_action_intent_conflict';
    end if;
    return v_existing.id;
  end;

  return v_id;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_canonical_recommendation_act(p_item_id uuid, p_owner_account_id text, p_action text, p_source_surface text, p_intent_nonce uuid, p_result_row_id uuid) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_canonical_recommendation_act(p_item_id uuid, p_owner_account_id text, p_action text, p_source_surface text, p_intent_nonce uuid, p_result_row_id uuid) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_canonical_recommendation_act(p_item_id uuid, p_owner_account_id text, p_action text, p_source_surface text, p_intent_nonce uuid, p_result_row_id uuid) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_canonical_recommendation_act(p_item_id uuid, p_owner_account_id text, p_action text, p_source_surface text, p_intent_nonce uuid, p_result_row_id uuid) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_canonical_recommendation_materialize(p_result_row_id uuid, p_owner_account_id text, p_content_version text, p_source_surface text, p_items jsonb)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_e record; v_set uuid; v_item jsonb; v_rank integer := 0;
begin
  select * into v_e from public.yorisou_canonical_recommendation_eligibility(p_result_row_id, p_owner_account_id);

  select id into v_set from public.yorisou_canonical_recommendation_sets
   where result_row_id = p_result_row_id and owner_account_id = p_owner_account_id
     and accepted_result_id = v_e.accepted_result_id and content_version = p_content_version
     and lifecycle_state = 'active'
   order by generated_at desc limit 1;
  if v_set is not null then return v_set; end if;

  -- A change of accepted result supersedes earlier sets rather than deleting them: what was
  -- recommended under a previous self-understanding is part of the person's history.
  update public.yorisou_canonical_recommendation_sets set lifecycle_state = 'superseded'
   where result_row_id = p_result_row_id and owner_account_id = p_owner_account_id
     and lifecycle_state = 'active';

  insert into public.yorisou_canonical_recommendation_sets
    (result_row_id, owner_account_id, accepted_result_id, original_result_id,
     eligibility_basis, content_version, source_surface)
  values
    (p_result_row_id, p_owner_account_id, v_e.accepted_result_id, v_e.original_result_id,
     v_e.basis, p_content_version, p_source_surface)
  returning id into v_set;

  if jsonb_typeof(p_items) <> 'array' then raise exception 'recommendation_items_invalid'; end if;
  if jsonb_array_length(p_items) > 5 then raise exception 'recommendation_items_too_many'; end if;

  for v_item in select * from jsonb_array_elements(p_items) loop
    v_rank := v_rank + 1;
    insert into public.yorisou_canonical_recommendation_items
      (set_id, owner_account_id, result_row_id, rank, recommendation_key, object_type,
       source_class, commercial_status, reason_code, limitations_code)
    values
      (v_set, p_owner_account_id, p_result_row_id, v_rank,
       v_item->>'recommendationKey', v_item->>'objectType', v_item->>'sourceClass',
       coalesce(v_item->>'commercialStatus','none'), v_item->>'reasonCode', v_item->>'limitationsCode');
  end loop;

  return v_set;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_canonical_recommendation_materialize(p_result_row_id uuid, p_owner_account_id text, p_content_version text, p_source_surface text, p_items jsonb) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_canonical_recommendation_materialize(p_result_row_id uuid, p_owner_account_id text, p_content_version text, p_source_surface text, p_items jsonb) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_canonical_recommendation_materialize(p_result_row_id uuid, p_owner_account_id text, p_content_version text, p_source_surface text, p_items jsonb) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_canonical_recommendation_materialize(p_result_row_id uuid, p_owner_account_id text, p_content_version text, p_source_surface text, p_items jsonb) to service_role';
  end if;
end $$;
