-- POR-1 PROMOTION P4 — Canonical LINE subjects, events and the erasure barrier
--
-- PRODUCTION_LINEAGE. Generated by scripts/por1/compile-promotion.mjs from the FINAL Preview
-- catalogue — not from the 24-migration Preview history. Only the last definition of a
-- `create or replace` chain is live, so promoting the history would promote bodies that were
-- already replaced, including the ones replaced because they were wrong.
--
-- Regenerate and verify with:  npm run por1:promotion-check
--
-- CONTENTS
--   tables 2 · sequences 0 · functions 12 · triggers 0
--
-- APPLY SEMANTICS
--   Every statement is guarded (`if not exists` / catalogue probe), so a partial failure can be
--   retried without a human reconstructing which half applied.
--
-- ROLLBACK CLASS
--   SCHEMA_REVERSIBLE_WHILE_FLAGS_OFF — additive only. Nothing here alters or drops an existing
--   Production object, so with the POR-1 capability controls unset these objects are inert: the
--   old application never names them. The Production incident response is to disable the
--   capability and roll back the application, NOT to drop the schema.
--
-- EXISTING-DATA IMPACT
--   None. No backfill, no column change to a populated table, no data movement.
--
-- LOCK CLASS
--   CREATE TABLE / CREATE INDEX on brand-new empty relations. No lock is taken on any table the
--   running application reads or writes.


-- ── tables ─────────────────────────────────────────────────────────────────

-- yorisou_canonical_line_events

do $$
declare
  v_unexpected text;
begin
  if to_regclass('public.yorisou_canonical_line_events') is null then
    create table public.yorisou_canonical_line_events (
    line_event_id text not null,
    webhook_event_id text,
    line_subject_hash text not null,
    line_subject_id text,
    owner_account_id text,
    owner_fingerprint text,
    source_type text,
    event_type text not null,
    message_type text,
    message_text text,
    postback_data text,
    delivery_mode text,
    is_redelivery boolean default false not null,
    reply_token_present boolean default false not null,
    reply_status text default 'not_attempted'::text not null,
    reply_error text,
    event_timestamp timestamp with time zone,
    received_at timestamp with time zone default now() not null,
    retention_state text default 'active'::text not null,
    erased_at timestamp with time zone,
    created_at timestamp with time zone default now() not null,
    updated_at timestamp with time zone default now() not null
    );
  else
    select string_agg(name, ', ' order by name) into v_unexpected from (
      select a.attname as name from pg_attribute a
       where a.attrelid = 'public.yorisou_canonical_line_events'::regclass and a.attnum > 0 and not a.attisdropped
         and a.attname <> all (array['line_event_id', 'webhook_event_id', 'line_subject_hash', 'line_subject_id', 'owner_account_id', 'owner_fingerprint', 'source_type', 'event_type', 'message_type', 'message_text', 'postback_data', 'delivery_mode', 'is_redelivery', 'reply_token_present', 'reply_status', 'reply_error', 'event_timestamp', 'received_at', 'retention_state', 'erased_at', 'created_at', 'updated_at'])
      union all
      select c.name from unnest(array['line_event_id', 'webhook_event_id', 'line_subject_hash', 'line_subject_id', 'owner_account_id', 'owner_fingerprint', 'source_type', 'event_type', 'message_type', 'message_text', 'postback_data', 'delivery_mode', 'is_redelivery', 'reply_token_present', 'reply_status', 'reply_error', 'event_timestamp', 'received_at', 'retention_state', 'erased_at', 'created_at', 'updated_at']) c(name)
       where not exists (
         select 1 from pg_attribute a
          where a.attrelid = 'public.yorisou_canonical_line_events'::regclass and a.attname = c.name
            and a.attnum > 0 and not a.attisdropped
       )
    ) s;
    if v_unexpected is not null then
      raise exception 'POR-1: yorisou_canonical_line_events already exists with a different shape (differing column(s): %). Refusing to promote onto it.', v_unexpected;
    end if;
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_line_events_erased_is_empty_check' and conrelid = 'public.yorisou_canonical_line_events'::regclass) then
    alter table public.yorisou_canonical_line_events add constraint yorisou_canonical_line_events_erased_is_empty_check CHECK (((retention_state = 'active'::text) OR ((message_text IS NULL) AND (postback_data IS NULL) AND (reply_error IS NULL) AND (owner_account_id IS NULL) AND (line_subject_id IS NULL) AND (erased_at IS NOT NULL))));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_line_events_owner_digest_check' and conrelid = 'public.yorisou_canonical_line_events'::regclass) then
    alter table public.yorisou_canonical_line_events add constraint yorisou_canonical_line_events_owner_digest_check CHECK (((owner_fingerprint IS NULL) OR (owner_fingerprint ~ '^[0-9a-f]{64}$'::text)));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_line_events_pkey' and conrelid = 'public.yorisou_canonical_line_events'::regclass) then
    alter table public.yorisou_canonical_line_events add constraint yorisou_canonical_line_events_pkey PRIMARY KEY (line_event_id);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_line_events_reply_status_check' and conrelid = 'public.yorisou_canonical_line_events'::regclass) then
    alter table public.yorisou_canonical_line_events add constraint yorisou_canonical_line_events_reply_status_check CHECK ((reply_status = ANY (ARRAY['not_attempted'::text, 'sent'::text, 'failed'::text])));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_line_events_retention_check' and conrelid = 'public.yorisou_canonical_line_events'::regclass) then
    alter table public.yorisou_canonical_line_events add constraint yorisou_canonical_line_events_retention_check CHECK ((retention_state = ANY (ARRAY['active'::text, 'erased'::text])));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_line_events_subject_digest_check' and conrelid = 'public.yorisou_canonical_line_events'::regclass) then
    alter table public.yorisou_canonical_line_events add constraint yorisou_canonical_line_events_subject_digest_check CHECK ((line_subject_hash ~ '^[0-9a-f]{64}$'::text));
  end if;
end $$;

create index if not exists yorisou_canonical_line_events_owner_idx ON public.yorisou_canonical_line_events USING btree (owner_fingerprint) WHERE (owner_fingerprint IS NOT NULL);

create index if not exists yorisou_canonical_line_events_recent_idx ON public.yorisou_canonical_line_events USING btree (received_at DESC);

create index if not exists yorisou_canonical_line_events_subject_recent_idx ON public.yorisou_canonical_line_events USING btree (line_subject_hash, received_at DESC);

create unique index if not exists yorisou_canonical_line_events_webhook_event_id_key ON public.yorisou_canonical_line_events USING btree (webhook_event_id) WHERE (webhook_event_id IS NOT NULL);

alter table public.yorisou_canonical_line_events enable row level security;

alter table public.yorisou_canonical_line_events force row level security;

revoke all on table public.yorisou_canonical_line_events from public;
do $$ begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on table public.yorisou_canonical_line_events from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on table public.yorisou_canonical_line_events from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant delete, insert, references, select, trigger, truncate, update on table public.yorisou_canonical_line_events to service_role';
  end if;
end $$;

-- yorisou_canonical_line_subjects

do $$
declare
  v_unexpected text;
begin
  if to_regclass('public.yorisou_canonical_line_subjects') is null then
    create table public.yorisou_canonical_line_subjects (
    line_subject_hash text not null,
    state text default 'active'::text not null,
    owner_fingerprint text,
    erased_at timestamp with time zone,
    created_at timestamp with time zone default now() not null,
    updated_at timestamp with time zone default now() not null
    );
  else
    select string_agg(name, ', ' order by name) into v_unexpected from (
      select a.attname as name from pg_attribute a
       where a.attrelid = 'public.yorisou_canonical_line_subjects'::regclass and a.attnum > 0 and not a.attisdropped
         and a.attname <> all (array['line_subject_hash', 'state', 'owner_fingerprint', 'erased_at', 'created_at', 'updated_at'])
      union all
      select c.name from unnest(array['line_subject_hash', 'state', 'owner_fingerprint', 'erased_at', 'created_at', 'updated_at']) c(name)
       where not exists (
         select 1 from pg_attribute a
          where a.attrelid = 'public.yorisou_canonical_line_subjects'::regclass and a.attname = c.name
            and a.attnum > 0 and not a.attisdropped
       )
    ) s;
    if v_unexpected is not null then
      raise exception 'POR-1: yorisou_canonical_line_subjects already exists with a different shape (differing column(s): %). Refusing to promote onto it.', v_unexpected;
    end if;
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_line_subjects_digest_check' and conrelid = 'public.yorisou_canonical_line_subjects'::regclass) then
    alter table public.yorisou_canonical_line_subjects add constraint yorisou_canonical_line_subjects_digest_check CHECK ((line_subject_hash ~ '^[0-9a-f]{64}$'::text));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_line_subjects_erased_stamp_check' and conrelid = 'public.yorisou_canonical_line_subjects'::regclass) then
    alter table public.yorisou_canonical_line_subjects add constraint yorisou_canonical_line_subjects_erased_stamp_check CHECK (((state = 'active'::text) OR (erased_at IS NOT NULL)));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_line_subjects_owner_digest_check' and conrelid = 'public.yorisou_canonical_line_subjects'::regclass) then
    alter table public.yorisou_canonical_line_subjects add constraint yorisou_canonical_line_subjects_owner_digest_check CHECK (((owner_fingerprint IS NULL) OR (owner_fingerprint ~ '^[0-9a-f]{64}$'::text)));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_line_subjects_pkey' and conrelid = 'public.yorisou_canonical_line_subjects'::regclass) then
    alter table public.yorisou_canonical_line_subjects add constraint yorisou_canonical_line_subjects_pkey PRIMARY KEY (line_subject_hash);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_line_subjects_state_check' and conrelid = 'public.yorisou_canonical_line_subjects'::regclass) then
    alter table public.yorisou_canonical_line_subjects add constraint yorisou_canonical_line_subjects_state_check CHECK ((state = ANY (ARRAY['active'::text, 'erased'::text])));
  end if;
end $$;

create index if not exists yorisou_canonical_line_subjects_owner_idx ON public.yorisou_canonical_line_subjects USING btree (owner_fingerprint) WHERE (owner_fingerprint IS NOT NULL);

create index if not exists yorisou_canonical_line_subjects_state_idx ON public.yorisou_canonical_line_subjects USING btree (state);

alter table public.yorisou_canonical_line_subjects enable row level security;

alter table public.yorisou_canonical_line_subjects force row level security;

revoke all on table public.yorisou_canonical_line_subjects from public;
do $$ begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on table public.yorisou_canonical_line_subjects from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on table public.yorisou_canonical_line_subjects from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant delete, insert, references, select, trigger, truncate, update on table public.yorisou_canonical_line_subjects to service_role';
  end if;
end $$;

-- ── functions ──────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.yorisou_line_subject_state(p_line_subject_hash text)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select jsonb_build_object(
    'subject_hash', p_line_subject_hash,
    'state', coalesce((select s.state from public.yorisou_canonical_line_subjects s
                        where s.line_subject_hash = p_line_subject_hash), 'unknown'),
    'owner_fingerprint', (select s.owner_fingerprint from public.yorisou_canonical_line_subjects s
                           where s.line_subject_hash = p_line_subject_hash),
    'erased_at', (select s.erased_at from public.yorisou_canonical_line_subjects s
                   where s.line_subject_hash = p_line_subject_hash)
  );
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_line_subject_state(p_line_subject_hash text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_line_subject_state(p_line_subject_hash text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_line_subject_state(p_line_subject_hash text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_line_subject_state(p_line_subject_hash text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_line_subject_lock(p_line_subject_hash text, p_owner_fingerprint text DEFAULT NULL::text)
 RETURNS yorisou_canonical_line_subjects
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_subject public.yorisou_canonical_line_subjects%rowtype;
begin
  if p_line_subject_hash is null or p_line_subject_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'line_subject_hash_must_be_sha256_hex';
  end if;

  for i in 1..2 loop
    select * into v_subject
      from public.yorisou_canonical_line_subjects
     where line_subject_hash = p_line_subject_hash
       for update;
    if found then
      return v_subject;
    end if;

    begin
      insert into public.yorisou_canonical_line_subjects (line_subject_hash, owner_fingerprint)
      values (p_line_subject_hash, p_owner_fingerprint);
    exception when unique_violation then
      -- A concurrent inserter won. Loop once more; the select will now find and LOCK its row, which
      -- is what makes the two callers serial instead of both proceeding on an unlocked subject.
      null;
    end;
  end loop;

  select * into v_subject
    from public.yorisou_canonical_line_subjects
   where line_subject_hash = p_line_subject_hash
     for update;
  if not found then
    raise exception 'line_subject_state_unavailable';
  end if;
  return v_subject;
end $function$;

do $$ begin
  execute 'revoke all on function public.yorisou_line_subject_lock(p_line_subject_hash text, p_owner_fingerprint text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_line_subject_lock(p_line_subject_hash text, p_owner_fingerprint text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_line_subject_lock(p_line_subject_hash text, p_owner_fingerprint text) from authenticated';
  end if;
  -- deliberately NOT granted to service_role: an internal lock helper, not an entry point.
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_line_subject_erasure_residue(p_line_subject_hash text)
 RETURNS integer
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select (
    (select count(*)::int
       from public.yorisou_canonical_line_events
      where line_subject_hash = p_line_subject_hash and retention_state = 'active')
    +
    (select case when exists (
        select 1 from public.yorisou_canonical_line_subjects
         where line_subject_hash = p_line_subject_hash and state = 'erased')
      then 0 else 1 end)
  );
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_line_subject_erasure_residue(p_line_subject_hash text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_line_subject_erasure_residue(p_line_subject_hash text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_line_subject_erasure_residue(p_line_subject_hash text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_line_subject_erasure_residue(p_line_subject_hash text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_line_subject_erase(p_line_subject_hash text, p_owner_fingerprint text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_subject   public.yorisou_canonical_line_subjects%rowtype;
  v_erased    int;
  v_residue   int;
  v_already   boolean;
begin
  v_subject := public.yorisou_line_subject_lock(p_line_subject_hash, p_owner_fingerprint);
  v_already := v_subject.state = 'erased';

  update public.yorisou_canonical_line_subjects
     set state             = 'erased',
         erased_at         = coalesce(erased_at, now()),
         owner_fingerprint = coalesce(p_owner_fingerprint, owner_fingerprint),
         updated_at        = now()
   where line_subject_hash = p_line_subject_hash;

  update public.yorisou_canonical_line_events
     set retention_state   = 'erased',
         erased_at         = now(),
         message_text      = null,
         postback_data     = null,
         reply_error       = null,
         owner_account_id  = null,
         line_subject_id   = null,
         owner_fingerprint = coalesce(p_owner_fingerprint, owner_fingerprint),
         updated_at        = now()
   where line_subject_hash = p_line_subject_hash
     and retention_state = 'active';

  get diagnostics v_erased = row_count;

  select count(*)::int into v_residue
    from public.yorisou_canonical_line_events
   where line_subject_hash = p_line_subject_hash
     and retention_state = 'active';

  if v_residue <> 0 then
    -- Unreachable under the subject lock; asserted because a deletion that reports success over
    -- residue is the one failure mode this whole family exists to prevent.
    raise exception 'line_subject_erasure_residue';
  end if;

  return jsonb_build_object(
    'subject_state', 'erased',
    'events_erased', v_erased,
    'active_residue', 0,
    'already_erased', v_already
  );
end $function$;

do $$ begin
  execute 'revoke all on function public.yorisou_line_subject_erase(p_line_subject_hash text, p_owner_fingerprint text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_line_subject_erase(p_line_subject_hash text, p_owner_fingerprint text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_line_subject_erase(p_line_subject_hash text, p_owner_fingerprint text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_line_subject_erase(p_line_subject_hash text, p_owner_fingerprint text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_line_recent_subjects(p_limit integer DEFAULT 10)
 RETURNS SETOF yorisou_canonical_line_events
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select * from (
    select distinct on (line_subject_hash) *
      from public.yorisou_canonical_line_events
     where retention_state = 'active'
     order by line_subject_hash, received_at desc, line_event_id desc
  ) latest
  order by received_at desc, line_event_id desc
  limit greatest(1, coalesce(p_limit, 10));
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_line_recent_subjects(p_limit integer) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_line_recent_subjects(p_limit integer) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_line_recent_subjects(p_limit integer) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_line_recent_subjects(p_limit integer) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_line_events_recent(p_limit integer DEFAULT 100)
 RETURNS SETOF yorisou_canonical_line_events
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select * from public.yorisou_canonical_line_events
   where retention_state = 'active'
   order by received_at desc, line_event_id desc
   limit greatest(1, coalesce(p_limit, 100));
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_line_events_recent(p_limit integer) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_line_events_recent(p_limit integer) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_line_events_recent(p_limit integer) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_line_events_recent(p_limit integer) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_line_events_for_subject(p_line_subject_hash text, p_limit integer DEFAULT 100)
 RETURNS SETOF yorisou_canonical_line_events
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select * from public.yorisou_canonical_line_events
   where line_subject_hash = p_line_subject_hash
     and retention_state = 'active'
   order by received_at desc, line_event_id desc
   limit greatest(1, coalesce(p_limit, 100));
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_line_events_for_subject(p_line_subject_hash text, p_limit integer) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_line_events_for_subject(p_line_subject_hash text, p_limit integer) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_line_events_for_subject(p_line_subject_hash text, p_limit integer) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_line_events_for_subject(p_line_subject_hash text, p_limit integer) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_line_events_for_owner(p_owner_fingerprint text, p_limit integer DEFAULT 100)
 RETURNS SETOF yorisou_canonical_line_events
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select * from public.yorisou_canonical_line_events
   where owner_fingerprint = p_owner_fingerprint
     and retention_state = 'active'
   order by received_at desc, line_event_id desc
   limit greatest(1, coalesce(p_limit, 100));
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_line_events_for_owner(p_owner_fingerprint text, p_limit integer) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_line_events_for_owner(p_owner_fingerprint text, p_limit integer) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_line_events_for_owner(p_owner_fingerprint text, p_limit integer) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_line_events_for_owner(p_owner_fingerprint text, p_limit integer) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_line_event_record(p_line_event_id text, p_line_subject_hash text, p_event_type text, p_line_subject_id text DEFAULT NULL::text, p_webhook_event_id text DEFAULT NULL::text, p_owner_account_id text DEFAULT NULL::text, p_owner_fingerprint text DEFAULT NULL::text, p_source_type text DEFAULT NULL::text, p_message_type text DEFAULT NULL::text, p_message_text text DEFAULT NULL::text, p_postback_data text DEFAULT NULL::text, p_delivery_mode text DEFAULT NULL::text, p_is_redelivery boolean DEFAULT false, p_reply_token_present boolean DEFAULT false, p_reply_status text DEFAULT 'not_attempted'::text, p_reply_error text DEFAULT NULL::text, p_event_timestamp timestamp with time zone DEFAULT NULL::timestamp with time zone, p_received_at timestamp with time zone DEFAULT NULL::timestamp with time zone)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_subject  public.yorisou_canonical_line_subjects%rowtype;
  v_existing public.yorisou_canonical_line_events%rowtype;
  v_received timestamptz := coalesce(p_received_at, now());
begin
  if p_line_event_id is null or length(trim(p_line_event_id)) = 0 then
    raise exception 'line_event_id_required';
  end if;
  if p_line_subject_hash is null or p_line_subject_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'line_subject_hash_must_be_sha256_hex';
  end if;

  -- THE BARRIER. Locking the subject before touching any event row is what serializes a brand-new
  -- event id against a completed erasure. Without it the two transactions never contend, because
  -- they address different rows, and both succeed.
  v_subject := public.yorisou_line_subject_lock(p_line_subject_hash, p_owner_fingerprint);

  if v_subject.state = 'erased' then
    -- Absorbed. No row, no raw subject id, no message text, no postback data, no reply error.
    return jsonb_build_object('outcome', 'erased', 'line_event_id', p_line_event_id);
  end if;

  select * into v_existing
    from public.yorisou_canonical_line_events
   where line_event_id = p_line_event_id
     for update;

  if not found and p_webhook_event_id is not null then
    select * into v_existing
      from public.yorisou_canonical_line_events
     where webhook_event_id = p_webhook_event_id
       for update;
  end if;

  if found then
    if v_existing.line_subject_hash is distinct from p_line_subject_hash then
      raise exception 'line_event_identity_conflict';
    end if;

    if v_existing.retention_state = 'erased' then
      return jsonb_build_object('outcome', 'erased', 'line_event_id', v_existing.line_event_id);
    end if;

    update public.yorisou_canonical_line_events
       set reply_status        = coalesce(p_reply_status, reply_status),
           reply_error         = p_reply_error,
           reply_token_present = coalesce(p_reply_token_present, reply_token_present),
           message_text        = coalesce(p_message_text, message_text),
           is_redelivery       = is_redelivery or coalesce(p_is_redelivery, false),
           owner_account_id    = coalesce(p_owner_account_id, owner_account_id),
           owner_fingerprint   = coalesce(p_owner_fingerprint, owner_fingerprint),
           line_subject_id     = coalesce(p_line_subject_id, line_subject_id),
           updated_at          = now()
     where line_event_id = v_existing.line_event_id;

    if p_owner_fingerprint is not null and v_subject.owner_fingerprint is distinct from p_owner_fingerprint then
      update public.yorisou_canonical_line_subjects
         set owner_fingerprint = p_owner_fingerprint, updated_at = now()
       where line_subject_hash = p_line_subject_hash;
    end if;

    return jsonb_build_object('outcome', 'repeated', 'line_event_id', v_existing.line_event_id);
  end if;

  -- The handler is scoped to the INSERT alone rather than to the whole function. A plpgsql exception
  -- block is a subtransaction, and rolling the whole body back would also roll back the subject row
  -- this transaction may have just created — discarding the barrier's state to report a duplicate.
  begin
    insert into public.yorisou_canonical_line_events (
      line_event_id, webhook_event_id, line_subject_hash, line_subject_id, owner_account_id, owner_fingerprint,
      source_type, event_type, message_type, message_text, postback_data, delivery_mode,
      is_redelivery, reply_token_present, reply_status, reply_error, event_timestamp, received_at
    ) values (
      p_line_event_id, p_webhook_event_id, p_line_subject_hash, p_line_subject_id, p_owner_account_id, p_owner_fingerprint,
      p_source_type, p_event_type, p_message_type, p_message_text, p_postback_data, p_delivery_mode,
      coalesce(p_is_redelivery, false), coalesce(p_reply_token_present, false),
      coalesce(p_reply_status, 'not_attempted'), p_reply_error, p_event_timestamp, v_received
    );
  exception
    when unique_violation then
      -- Lost the insert race on `webhook_event_id`. The winner wrote the same event, so this is a
      -- repeat, not a failure — but only if it is genuinely the same subject.
      if exists (
        select 1 from public.yorisou_canonical_line_events
         where webhook_event_id = p_webhook_event_id
           and line_subject_hash is distinct from p_line_subject_hash
      ) then
        raise exception 'line_event_identity_conflict';
      end if;
      return jsonb_build_object('outcome', 'repeated', 'line_event_id', p_line_event_id);
  end;

  if p_owner_fingerprint is not null and v_subject.owner_fingerprint is distinct from p_owner_fingerprint then
    update public.yorisou_canonical_line_subjects
       set owner_fingerprint = p_owner_fingerprint, updated_at = now()
     where line_subject_hash = p_line_subject_hash;
  end if;

  return jsonb_build_object('outcome', 'recorded', 'line_event_id', p_line_event_id);
end $function$;

do $$ begin
  execute 'revoke all on function public.yorisou_line_event_record(p_line_event_id text, p_line_subject_hash text, p_event_type text, p_line_subject_id text, p_webhook_event_id text, p_owner_account_id text, p_owner_fingerprint text, p_source_type text, p_message_type text, p_message_text text, p_postback_data text, p_delivery_mode text, p_is_redelivery boolean, p_reply_token_present boolean, p_reply_status text, p_reply_error text, p_event_timestamp timestamp with time zone, p_received_at timestamp with time zone) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_line_event_record(p_line_event_id text, p_line_subject_hash text, p_event_type text, p_line_subject_id text, p_webhook_event_id text, p_owner_account_id text, p_owner_fingerprint text, p_source_type text, p_message_type text, p_message_text text, p_postback_data text, p_delivery_mode text, p_is_redelivery boolean, p_reply_token_present boolean, p_reply_status text, p_reply_error text, p_event_timestamp timestamp with time zone, p_received_at timestamp with time zone) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_line_event_record(p_line_event_id text, p_line_subject_hash text, p_event_type text, p_line_subject_id text, p_webhook_event_id text, p_owner_account_id text, p_owner_fingerprint text, p_source_type text, p_message_type text, p_message_text text, p_postback_data text, p_delivery_mode text, p_is_redelivery boolean, p_reply_token_present boolean, p_reply_status text, p_reply_error text, p_event_timestamp timestamp with time zone, p_received_at timestamp with time zone) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_line_event_record(p_line_event_id text, p_line_subject_hash text, p_event_type text, p_line_subject_id text, p_webhook_event_id text, p_owner_account_id text, p_owner_fingerprint text, p_source_type text, p_message_type text, p_message_text text, p_postback_data text, p_delivery_mode text, p_is_redelivery boolean, p_reply_token_present boolean, p_reply_status text, p_reply_error text, p_event_timestamp timestamp with time zone, p_received_at timestamp with time zone) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_line_activity_residue(p_line_subject_hash text)
 RETURNS integer
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select count(*)::int from public.yorisou_canonical_line_events
   where line_subject_hash = p_line_subject_hash and retention_state = 'active';
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_line_activity_residue(p_line_subject_hash text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_line_activity_residue(p_line_subject_hash text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_line_activity_residue(p_line_subject_hash text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_line_activity_residue(p_line_subject_hash text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_line_activity_inventory(p_line_subject_hash text)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select jsonb_build_object(
    'subject_hash', p_line_subject_hash,
    'subject_state', coalesce((select s.state from public.yorisou_canonical_line_subjects s
                                where s.line_subject_hash = p_line_subject_hash), 'unknown'),
    'owner_fingerprint', (select s.owner_fingerprint from public.yorisou_canonical_line_subjects s
                           where s.line_subject_hash = p_line_subject_hash),
    'active_events', (select count(*)::int from public.yorisou_canonical_line_events e
                       where e.line_subject_hash = p_line_subject_hash and e.retention_state = 'active'),
    'erased_events', (select count(*)::int from public.yorisou_canonical_line_events e
                       where e.line_subject_hash = p_line_subject_hash and e.retention_state = 'erased'),
    'latest_received_at', (select max(e.received_at) from public.yorisou_canonical_line_events e
                            where e.line_subject_hash = p_line_subject_hash and e.retention_state = 'active')
  );
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_line_activity_inventory(p_line_subject_hash text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_line_activity_inventory(p_line_subject_hash text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_line_activity_inventory(p_line_subject_hash text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_line_activity_inventory(p_line_subject_hash text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_line_activity_erase(p_line_subject_hash text, p_owner_fingerprint text DEFAULT NULL::text)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_result jsonb;
begin
  v_result := public.yorisou_line_subject_erase(p_line_subject_hash, p_owner_fingerprint);
  return (v_result ->> 'events_erased')::int;
end $function$;

do $$ begin
  execute 'revoke all on function public.yorisou_line_activity_erase(p_line_subject_hash text, p_owner_fingerprint text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_line_activity_erase(p_line_subject_hash text, p_owner_fingerprint text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_line_activity_erase(p_line_subject_hash text, p_owner_fingerprint text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_line_activity_erase(p_line_subject_hash text, p_owner_fingerprint text) to service_role';
  end if;
end $$;
