-- POR-1 PROMOTION P3 — Canonical identity links and the identity provisioning saga
--
-- PRODUCTION_LINEAGE. Generated by scripts/por1/compile-promotion.mjs from the FINAL Preview
-- catalogue — not from the 24-migration Preview history. Only the last definition of a
-- `create or replace` chain is live, so promoting the history would promote bodies that were
-- already replaced, including the ones replaced because they were wrong.
--
-- Regenerate and verify with:  npm run por1:promotion-check
--
-- CONTENTS
--   tables 2 · sequences 0 · functions 17 · triggers 0
--
-- APPLY SEMANTICS
--   Every statement is guarded (`if not exists` / catalogue probe), so a partial failure can be
--   retried without a human reconstructing which half applied.
--
-- ROLLBACK CLASS
--   SCHEMA_REVERSIBLE_WHILE_FLAGS_OFF — additive only. Nothing here alters or drops an existing
--   Production object, so with the POR-1 capability controls unset these objects are inert: the
--   old application never names them. The Production incident response is to disable the
--   capability and roll back the application, NOT to drop the schema.
--
-- EXISTING-DATA IMPACT
--   None. No backfill, no column change to a populated table, no data movement.
--
-- LOCK CLASS
--   CREATE TABLE / CREATE INDEX on brand-new empty relations. No lock is taken on any table the
--   running application reads or writes.


-- ── functions required by the table definitions below ──────────────────────

CREATE OR REPLACE FUNCTION public.yorisou_provisioning_stage_rank(p_stage text)
 RETURNS integer
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  select case p_stage
    when 'account_creation'   then 1
    when 'canonical_identity' then 2
    when 'session_binding'    then 3
    when 'verification'       then 4
    when 'finalizing'         then 5
    when 'completed'          then 6
    else null end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_provisioning_stage_rank(p_stage text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_provisioning_stage_rank(p_stage text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_provisioning_stage_rank(p_stage text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_provisioning_stage_rank(p_stage text) to service_role';
  end if;
end $$;

-- ── tables ─────────────────────────────────────────────────────────────────

-- yorisou_canonical_identity_links

do $$
declare
  v_unexpected text;
begin
  if to_regclass('public.yorisou_canonical_identity_links') is null then
    create table public.yorisou_canonical_identity_links (
    link_id uuid default gen_random_uuid() not null,
    owner_account_id text,
    owner_fingerprint text not null,
    link_kind text not null,
    link_digest text,
    link_state text default 'active'::text not null,
    contract_version text default 'por1-v1'::text not null,
    created_at timestamp with time zone default now() not null,
    updated_at timestamp with time zone default now() not null,
    erased_at timestamp with time zone
    );
  else
    select string_agg(name, ', ' order by name) into v_unexpected from (
      select a.attname as name from pg_attribute a
       where a.attrelid = 'public.yorisou_canonical_identity_links'::regclass and a.attnum > 0 and not a.attisdropped
         and a.attname <> all (array['link_id', 'owner_account_id', 'owner_fingerprint', 'link_kind', 'link_digest', 'link_state', 'contract_version', 'created_at', 'updated_at', 'erased_at'])
      union all
      select c.name from unnest(array['link_id', 'owner_account_id', 'owner_fingerprint', 'link_kind', 'link_digest', 'link_state', 'contract_version', 'created_at', 'updated_at', 'erased_at']) c(name)
       where not exists (
         select 1 from pg_attribute a
          where a.attrelid = 'public.yorisou_canonical_identity_links'::regclass and a.attname = c.name
            and a.attnum > 0 and not a.attisdropped
       )
    ) s;
    if v_unexpected is not null then
      raise exception 'POR-1: yorisou_canonical_identity_links already exists with a different shape (differing column(s): %). Refusing to promote onto it.', v_unexpected;
    end if;
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_canonical_identity_links_pkey' and conrelid = 'public.yorisou_canonical_identity_links'::regclass) then
    alter table public.yorisou_canonical_identity_links add constraint yorisou_canonical_identity_links_pkey PRIMARY KEY (link_id);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_identity_link_active_shape_check' and conrelid = 'public.yorisou_canonical_identity_links'::regclass) then
    alter table public.yorisou_canonical_identity_links add constraint yorisou_identity_link_active_shape_check CHECK (((link_state <> 'active'::text) OR ((owner_account_id IS NOT NULL) AND (link_digest IS NOT NULL))));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_identity_link_erased_shape_check' and conrelid = 'public.yorisou_canonical_identity_links'::regclass) then
    alter table public.yorisou_canonical_identity_links add constraint yorisou_identity_link_erased_shape_check CHECK (((link_state <> 'erased'::text) OR ((owner_account_id IS NULL) AND (link_digest IS NULL) AND (erased_at IS NOT NULL))));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_identity_link_hashed_kind_check' and conrelid = 'public.yorisou_canonical_identity_links'::regclass) then
    alter table public.yorisou_canonical_identity_links add constraint yorisou_identity_link_hashed_kind_check CHECK (((link_digest IS NULL) OR (link_kind <> ALL (ARRAY['email'::text, 'line_subject'::text])) OR (link_digest ~ '^[0-9a-f]{64}$'::text)));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_identity_link_kind_check' and conrelid = 'public.yorisou_canonical_identity_links'::regclass) then
    alter table public.yorisou_canonical_identity_links add constraint yorisou_identity_link_kind_check CHECK ((link_kind = ANY (ARRAY['email'::text, 'line_subject'::text, 'user_profile'::text, 'auth_identity'::text, 'provisioning'::text])));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_identity_link_opaque_kind_check' and conrelid = 'public.yorisou_canonical_identity_links'::regclass) then
    alter table public.yorisou_canonical_identity_links add constraint yorisou_identity_link_opaque_kind_check CHECK (((link_digest IS NULL) OR (link_kind = ANY (ARRAY['email'::text, 'line_subject'::text])) OR ((char_length(link_digest) >= 1) AND (char_length(link_digest) <= 200) AND (link_digest !~ '@'::text) AND (link_digest !~ '\s'::text))));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_identity_link_owner_digest_check' and conrelid = 'public.yorisou_canonical_identity_links'::regclass) then
    alter table public.yorisou_canonical_identity_links add constraint yorisou_identity_link_owner_digest_check CHECK ((owner_fingerprint ~ '^[0-9a-f]{64}$'::text));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_identity_link_state_check' and conrelid = 'public.yorisou_canonical_identity_links'::regclass) then
    alter table public.yorisou_canonical_identity_links add constraint yorisou_identity_link_state_check CHECK ((link_state = ANY (ARRAY['active'::text, 'erased'::text])));
  end if;
end $$;

create unique index if not exists yorisou_identity_link_active_unique ON public.yorisou_canonical_identity_links USING btree (link_kind, link_digest) WHERE (link_state = 'active'::text);

create index if not exists yorisou_identity_link_fingerprint_idx ON public.yorisou_canonical_identity_links USING btree (owner_fingerprint);

create index if not exists yorisou_identity_link_owner_idx ON public.yorisou_canonical_identity_links USING btree (owner_account_id) WHERE (link_state = 'active'::text);

alter table public.yorisou_canonical_identity_links enable row level security;

alter table public.yorisou_canonical_identity_links force row level security;

revoke all on table public.yorisou_canonical_identity_links from public;
do $$ begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on table public.yorisou_canonical_identity_links from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on table public.yorisou_canonical_identity_links from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant delete, insert, references, select, trigger, truncate, update on table public.yorisou_canonical_identity_links to service_role';
  end if;
end $$;

-- yorisou_identity_provisioning_sagas

do $$
declare
  v_unexpected text;
begin
  if to_regclass('public.yorisou_identity_provisioning_sagas') is null then
    create table public.yorisou_identity_provisioning_sagas (
    provisioning_key text not null,
    account_id text,
    owner_fingerprint text,
    session_fingerprint text,
    state text default 'requested'::text not null,
    provisioning_cursor text default 'account_creation'::text not null,
    contract_version text default 'por1-v1'::text not null,
    attempt_count integer default 0 not null,
    failure_class text,
    last_error_code text,
    executor_token_hash text,
    executor_generation integer default 0 not null,
    executor_claimed_at timestamp with time zone,
    executor_expires_at timestamp with time zone,
    requested_at timestamp with time zone default now() not null,
    completed_at timestamp with time zone,
    updated_at timestamp with time zone default now() not null
    );
  else
    select string_agg(name, ', ' order by name) into v_unexpected from (
      select a.attname as name from pg_attribute a
       where a.attrelid = 'public.yorisou_identity_provisioning_sagas'::regclass and a.attnum > 0 and not a.attisdropped
         and a.attname <> all (array['provisioning_key', 'account_id', 'owner_fingerprint', 'session_fingerprint', 'state', 'provisioning_cursor', 'contract_version', 'attempt_count', 'failure_class', 'last_error_code', 'executor_token_hash', 'executor_generation', 'executor_claimed_at', 'executor_expires_at', 'requested_at', 'completed_at', 'updated_at'])
      union all
      select c.name from unnest(array['provisioning_key', 'account_id', 'owner_fingerprint', 'session_fingerprint', 'state', 'provisioning_cursor', 'contract_version', 'attempt_count', 'failure_class', 'last_error_code', 'executor_token_hash', 'executor_generation', 'executor_claimed_at', 'executor_expires_at', 'requested_at', 'completed_at', 'updated_at']) c(name)
       where not exists (
         select 1 from pg_attribute a
          where a.attrelid = 'public.yorisou_identity_provisioning_sagas'::regclass and a.attname = c.name
            and a.attnum > 0 and not a.attisdropped
       )
    ) s;
    if v_unexpected is not null then
      raise exception 'POR-1: yorisou_identity_provisioning_sagas already exists with a different shape (differing column(s): %). Refusing to promote onto it.', v_unexpected;
    end if;
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_identity_provisioning_sagas_account_id_key' and conrelid = 'public.yorisou_identity_provisioning_sagas'::regclass) then
    alter table public.yorisou_identity_provisioning_sagas add constraint yorisou_identity_provisioning_sagas_account_id_key UNIQUE (account_id);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_identity_provisioning_sagas_attempt_count_check' and conrelid = 'public.yorisou_identity_provisioning_sagas'::regclass) then
    alter table public.yorisou_identity_provisioning_sagas add constraint yorisou_identity_provisioning_sagas_attempt_count_check CHECK ((attempt_count >= 0));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_identity_provisioning_sagas_last_error_code_check' and conrelid = 'public.yorisou_identity_provisioning_sagas'::regclass) then
    alter table public.yorisou_identity_provisioning_sagas add constraint yorisou_identity_provisioning_sagas_last_error_code_check CHECK (((last_error_code IS NULL) OR (char_length(last_error_code) <= 80)));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_identity_provisioning_sagas_pkey' and conrelid = 'public.yorisou_identity_provisioning_sagas'::regclass) then
    alter table public.yorisou_identity_provisioning_sagas add constraint yorisou_identity_provisioning_sagas_pkey PRIMARY KEY (provisioning_key);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_provisioning_account_bound_check' and conrelid = 'public.yorisou_identity_provisioning_sagas'::regclass) then
    alter table public.yorisou_identity_provisioning_sagas add constraint yorisou_provisioning_account_bound_check CHECK (((yorisou_provisioning_stage_rank(provisioning_cursor) < 2) OR (state = 'failed_terminal'::text) OR (account_id IS NOT NULL)));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_provisioning_completed_shape_check' and conrelid = 'public.yorisou_identity_provisioning_sagas'::regclass) then
    alter table public.yorisou_identity_provisioning_sagas add constraint yorisou_provisioning_completed_shape_check CHECK (((state <> 'completed'::text) OR ((provisioning_cursor = 'completed'::text) AND (account_id IS NOT NULL) AND (owner_fingerprint IS NOT NULL) AND (completed_at IS NOT NULL))));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_provisioning_cursor_check' and conrelid = 'public.yorisou_identity_provisioning_sagas'::regclass) then
    alter table public.yorisou_identity_provisioning_sagas add constraint yorisou_provisioning_cursor_check CHECK ((yorisou_provisioning_stage_rank(provisioning_cursor) IS NOT NULL));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_provisioning_failure_class_check' and conrelid = 'public.yorisou_identity_provisioning_sagas'::regclass) then
    alter table public.yorisou_identity_provisioning_sagas add constraint yorisou_provisioning_failure_class_check CHECK (((failure_class IS NULL) OR (failure_class = ANY (ARRAY['account_write_failed'::text, 'email_already_registered'::text, 'canonical_identity_failed'::text, 'foundation_transport_failed'::text, 'session_binding_failed'::text, 'verification_incomplete'::text, 'mutation_fence_denied'::text, 'account_absent_after_creation'::text, 'executor_lost'::text, 'unclassified'::text]))));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_provisioning_key_digest_check' and conrelid = 'public.yorisou_identity_provisioning_sagas'::regclass) then
    alter table public.yorisou_identity_provisioning_sagas add constraint yorisou_provisioning_key_digest_check CHECK ((provisioning_key ~ '^[0-9a-f]{64}$'::text));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_provisioning_owner_digest_check' and conrelid = 'public.yorisou_identity_provisioning_sagas'::regclass) then
    alter table public.yorisou_identity_provisioning_sagas add constraint yorisou_provisioning_owner_digest_check CHECK (((owner_fingerprint IS NULL) OR (owner_fingerprint ~ '^[0-9a-f]{64}$'::text)));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_provisioning_session_digest_check' and conrelid = 'public.yorisou_identity_provisioning_sagas'::regclass) then
    alter table public.yorisou_identity_provisioning_sagas add constraint yorisou_provisioning_session_digest_check CHECK (((session_fingerprint IS NULL) OR (session_fingerprint ~ '^[0-9a-f]{64}$'::text)));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_provisioning_state_check' and conrelid = 'public.yorisou_identity_provisioning_sagas'::regclass) then
    alter table public.yorisou_identity_provisioning_sagas add constraint yorisou_provisioning_state_check CHECK ((state = ANY (ARRAY['requested'::text, 'account_created'::text, 'canonical_identity_created'::text, 'session_bound'::text, 'completed'::text, 'failed_retryable'::text, 'failed_terminal'::text])));
  end if;
end $$;

create index if not exists yorisou_provisioning_cursor_idx ON public.yorisou_identity_provisioning_sagas USING btree (provisioning_cursor);

create index if not exists yorisou_provisioning_owner_idx ON public.yorisou_identity_provisioning_sagas USING btree (owner_fingerprint) WHERE (owner_fingerprint IS NOT NULL);

create index if not exists yorisou_provisioning_state_idx ON public.yorisou_identity_provisioning_sagas USING btree (state);

alter table public.yorisou_identity_provisioning_sagas enable row level security;

alter table public.yorisou_identity_provisioning_sagas force row level security;

revoke all on table public.yorisou_identity_provisioning_sagas from public;
do $$ begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on table public.yorisou_identity_provisioning_sagas from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on table public.yorisou_identity_provisioning_sagas from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant delete, insert, references, select, trigger, truncate, update on table public.yorisou_identity_provisioning_sagas to service_role';
  end if;
end $$;

-- ── functions ──────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.yorisou_provisioning_status(p_provisioning_key text)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select jsonb_build_object(
    'found', count(*) > 0,
    'state', max(state), 'cursor', max(provisioning_cursor),
    'accountId', max(account_id), 'failureClass', max(failure_class),
    'attemptCount', max(attempt_count), 'generation', max(executor_generation)
  )
  from public.yorisou_identity_provisioning_sagas
  where provisioning_key = p_provisioning_key;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_provisioning_status(p_provisioning_key text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_provisioning_status(p_provisioning_key text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_provisioning_status(p_provisioning_key text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_provisioning_status(p_provisioning_key text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_provisioning_state_for_cursor(p_cursor text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  select case p_cursor
    when 'account_creation'   then 'requested'
    when 'canonical_identity' then 'account_created'
    when 'session_binding'    then 'canonical_identity_created'
    -- Verification is READ-ONLY, so reaching it changes nothing about what exists: both it and
    -- finalizing describe a saga whose session is bound and whose completeness is unproven.
    when 'verification'       then 'session_bound'
    when 'finalizing'         then 'session_bound'
    when 'completed'          then 'completed'
    else null end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_provisioning_state_for_cursor(p_cursor text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_provisioning_state_for_cursor(p_cursor text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_provisioning_state_for_cursor(p_cursor text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_provisioning_state_for_cursor(p_cursor text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_provisioning_residue(p_account_id text DEFAULT NULL::text, p_owner_fingerprint text DEFAULT NULL::text)
 RETURNS integer
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select count(*)::int from public.yorisou_identity_provisioning_sagas
   where (p_account_id is not null and account_id = p_account_id)
      or (p_owner_fingerprint is not null and owner_fingerprint = p_owner_fingerprint);
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_provisioning_residue(p_account_id text, p_owner_fingerprint text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_provisioning_residue(p_account_id text, p_owner_fingerprint text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_provisioning_residue(p_account_id text, p_owner_fingerprint text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_provisioning_residue(p_account_id text, p_owner_fingerprint text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_provisioning_release(p_provisioning_key text, p_token_hash text, p_generation integer)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_rows int;
begin
  update public.yorisou_identity_provisioning_sagas
     set executor_token_hash = null, executor_expires_at = null, updated_at = now()
   where provisioning_key = p_provisioning_key
     and executor_token_hash = p_token_hash
     and executor_generation = p_generation
     and state not in ('completed','failed_terminal');
  get diagnostics v_rows = row_count;
  return v_rows > 0;
end $function$;

do $$ begin
  execute 'revoke all on function public.yorisou_provisioning_release(p_provisioning_key text, p_token_hash text, p_generation integer) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_provisioning_release(p_provisioning_key text, p_token_hash text, p_generation integer) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_provisioning_release(p_provisioning_key text, p_token_hash text, p_generation integer) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_provisioning_release(p_provisioning_key text, p_token_hash text, p_generation integer) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_provisioning_record_failure(p_provisioning_key text, p_token_hash text, p_generation integer, p_failure_class text, p_error_code text DEFAULT NULL::text, p_terminal boolean DEFAULT false)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_saga public.yorisou_identity_provisioning_sagas%rowtype;
begin
  select * into v_saga from public.yorisou_identity_provisioning_sagas
   where provisioning_key = p_provisioning_key for update;
  if not found then raise exception 'provisioning_saga_not_found'; end if;
  if v_saga.state = 'completed' then
    -- A completed provisioning cannot be un-completed by a late failure report from a lost attempt.
    return jsonb_build_object('state', v_saga.state, 'cursor', v_saga.provisioning_cursor);
  end if;
  if v_saga.executor_token_hash is distinct from p_token_hash
     or v_saga.executor_generation is distinct from p_generation then
    raise exception 'provisioning_executor_mismatch';
  end if;

  update public.yorisou_identity_provisioning_sagas
     set state           = case when p_terminal then 'failed_terminal' else 'failed_retryable' end,
         failure_class   = p_failure_class,
         last_error_code = left(coalesce(p_error_code, ''), 80),
         -- Released, so the retry does not have to outlive the TTL to take over.
         executor_token_hash = null,
         executor_expires_at = null,
         updated_at      = now()
   where provisioning_key = p_provisioning_key;

  return jsonb_build_object(
    'state', case when p_terminal then 'failed_terminal' else 'failed_retryable' end,
    'cursor', v_saga.provisioning_cursor
  );
end $function$;

do $$ begin
  execute 'revoke all on function public.yorisou_provisioning_record_failure(p_provisioning_key text, p_token_hash text, p_generation integer, p_failure_class text, p_error_code text, p_terminal boolean) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_provisioning_record_failure(p_provisioning_key text, p_token_hash text, p_generation integer, p_failure_class text, p_error_code text, p_terminal boolean) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_provisioning_record_failure(p_provisioning_key text, p_token_hash text, p_generation integer, p_failure_class text, p_error_code text, p_terminal boolean) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_provisioning_record_failure(p_provisioning_key text, p_token_hash text, p_generation integer, p_failure_class text, p_error_code text, p_terminal boolean) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_provisioning_purge_for_owner(p_account_id text DEFAULT NULL::text, p_owner_fingerprint text DEFAULT NULL::text)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_rows int;
begin
  if p_account_id is null and p_owner_fingerprint is null then
    raise exception 'provisioning_purge_target_required';
  end if;
  delete from public.yorisou_identity_provisioning_sagas
   where (p_account_id is not null and account_id = p_account_id)
      or (p_owner_fingerprint is not null and owner_fingerprint = p_owner_fingerprint);
  get diagnostics v_rows = row_count;
  return v_rows;
end $function$;

do $$ begin
  execute 'revoke all on function public.yorisou_provisioning_purge_for_owner(p_account_id text, p_owner_fingerprint text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_provisioning_purge_for_owner(p_account_id text, p_owner_fingerprint text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_provisioning_purge_for_owner(p_account_id text, p_owner_fingerprint text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_provisioning_purge_for_owner(p_account_id text, p_owner_fingerprint text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_provisioning_partial_inventory()
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select coalesce(jsonb_agg(row_to_json(t)), '[]'::jsonb) from (
    select state, provisioning_cursor as cursor, failure_class, count(*)::int as count
      from public.yorisou_identity_provisioning_sagas
     where state <> 'completed'
     group by state, provisioning_cursor, failure_class
     order by state, provisioning_cursor, failure_class
  ) t;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_provisioning_partial_inventory() from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_provisioning_partial_inventory() from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_provisioning_partial_inventory() from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_provisioning_partial_inventory() to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_provisioning_open(p_provisioning_key text, p_token_hash text, p_ttl_seconds integer DEFAULT 90)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_saga   public.yorisou_identity_provisioning_sagas%rowtype;
  v_locked boolean := false;
begin
  if p_provisioning_key is null or p_provisioning_key !~ '^[0-9a-f]{64}$' then
    raise exception 'provisioning_key_must_be_sha256_hex';
  end if;
  if p_token_hash is null or char_length(p_token_hash) < 32 then
    raise exception 'provisioning_executor_token_required';
  end if;
  if p_ttl_seconds is null or p_ttl_seconds < 5 or p_ttl_seconds > 600 then
    raise exception 'provisioning_executor_ttl_out_of_range';
  end if;

  -- Lock-or-create. The re-select after a lost insert race is not optional: `on conflict` returns no
  -- row, and proceeding without the lock is how two requests both believe they opened the saga.
  for i in 1..2 loop
    select * into v_saga from public.yorisou_identity_provisioning_sagas
     where provisioning_key = p_provisioning_key for update;
    if found then v_locked := true; exit; end if;
    begin
      insert into public.yorisou_identity_provisioning_sagas (provisioning_key) values (p_provisioning_key);
    exception when unique_violation then
      null;  -- a concurrent opener won; loop once more and LOCK its row
    end;
  end loop;
  if not v_locked then raise exception 'provisioning_saga_unavailable'; end if;

  -- Already done. A retry of a registration that succeeded is not a second registration; it is the
  -- same one, and it is finished. This is what makes "the response was lost" resolvable.
  if v_saga.state = 'completed' then
    return jsonb_build_object(
      'outcome', 'completed', 'claimed', false,
      'cursor', v_saga.provisioning_cursor, 'state', v_saga.state,
      'generation', v_saga.executor_generation, 'accountId', v_saga.account_id
    );
  end if;

  if v_saga.state = 'failed_terminal' then
    return jsonb_build_object(
      'outcome', 'failed_terminal', 'claimed', false,
      'cursor', v_saga.provisioning_cursor, 'state', v_saga.state,
      'failureClass', v_saga.failure_class, 'accountId', v_saga.account_id
    );
  end if;

  -- Someone else is driving and their claim has not lapsed. Two concurrent registrations for one
  -- email do not both proceed; the second is told the truth about why it is waiting.
  if v_saga.executor_token_hash is not null
     and v_saga.executor_token_hash <> p_token_hash
     and v_saga.executor_expires_at is not null
     and v_saga.executor_expires_at > now() then
    return jsonb_build_object(
      'outcome', 'in_progress', 'claimed', false,
      'cursor', v_saga.provisioning_cursor, 'state', v_saga.state,
      'generation', v_saga.executor_generation
    );
  end if;

  update public.yorisou_identity_provisioning_sagas
     set executor_token_hash = p_token_hash,
         executor_generation = v_saga.executor_generation + 1,
         executor_claimed_at = now(),
         executor_expires_at = now() + make_interval(secs => p_ttl_seconds),
         attempt_count       = v_saga.attempt_count + 1,
         -- A retryable failure is a note about the PREVIOUS attempt, never an instruction about
         -- where to start. The cursor is deliberately untouched.
         state               = case when v_saga.state = 'failed_retryable'
                                    then public.yorisou_provisioning_state_for_cursor(v_saga.provisioning_cursor)
                                    else v_saga.state end,
         updated_at          = now()
   where provisioning_key = p_provisioning_key;

  return jsonb_build_object(
    'outcome', 'claimed', 'claimed', true,
    'cursor', v_saga.provisioning_cursor,
    'state', public.yorisou_provisioning_state_for_cursor(v_saga.provisioning_cursor),
    'generation', v_saga.executor_generation + 1,
    'accountId', v_saga.account_id,
    'attemptCount', v_saga.attempt_count + 1,
    'resumed', v_saga.provisioning_cursor <> 'account_creation'
  );
end $function$;

do $$ begin
  execute 'revoke all on function public.yorisou_provisioning_open(p_provisioning_key text, p_token_hash text, p_ttl_seconds integer) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_provisioning_open(p_provisioning_key text, p_token_hash text, p_ttl_seconds integer) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_provisioning_open(p_provisioning_key text, p_token_hash text, p_ttl_seconds integer) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_provisioning_open(p_provisioning_key text, p_token_hash text, p_ttl_seconds integer) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_provisioning_complete_step(p_provisioning_key text, p_token_hash text, p_generation integer, p_expected_cursor text, p_next_cursor text, p_account_id text DEFAULT NULL::text, p_owner_fingerprint text DEFAULT NULL::text, p_session_fingerprint text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_saga public.yorisou_identity_provisioning_sagas%rowtype;
  v_next_state text;
begin
  select * into v_saga from public.yorisou_identity_provisioning_sagas
   where provisioning_key = p_provisioning_key for update;
  if not found then raise exception 'provisioning_saga_not_found'; end if;

  if v_saga.state in ('completed','failed_terminal') then
    raise exception 'provisioning_terminal_%', v_saga.state;
  end if;
  if v_saga.executor_token_hash is distinct from p_token_hash then
    raise exception 'provisioning_executor_mismatch';
  end if;
  if v_saga.executor_generation is distinct from p_generation then
    raise exception 'provisioning_executor_generation_stale';
  end if;
  if v_saga.provisioning_cursor is distinct from p_expected_cursor then
    raise exception 'provisioning_cursor_mismatch';
  end if;
  if public.yorisou_provisioning_stage_rank(p_next_cursor)
     is distinct from public.yorisou_provisioning_stage_rank(p_expected_cursor) + 1 then
    raise exception 'provisioning_cursor_illegal_transition';
  end if;

  -- The account binding is written once and is then immutable. A saga that changed which account it
  -- belonged to could bind a session to one account and complete another.
  if p_account_id is not null and v_saga.account_id is not null
     and v_saga.account_id is distinct from p_account_id then
    raise exception 'provisioning_account_rebind_refused';
  end if;

  v_next_state := public.yorisou_provisioning_state_for_cursor(p_next_cursor);

  update public.yorisou_identity_provisioning_sagas
     set provisioning_cursor = p_next_cursor,
         state               = v_next_state,
         account_id          = coalesce(v_saga.account_id, p_account_id),
         owner_fingerprint   = coalesce(v_saga.owner_fingerprint, p_owner_fingerprint),
         session_fingerprint = coalesce(p_session_fingerprint, v_saga.session_fingerprint),
         failure_class       = null,
         last_error_code     = null,
         completed_at        = case when v_next_state = 'completed' then now() else v_saga.completed_at end,
         updated_at          = now()
   where provisioning_key = p_provisioning_key;

  return jsonb_build_object(
    'cursor', p_next_cursor, 'state', v_next_state,
    'accountId', coalesce(v_saga.account_id, p_account_id)
  );
end $function$;

do $$ begin
  execute 'revoke all on function public.yorisou_provisioning_complete_step(p_provisioning_key text, p_token_hash text, p_generation integer, p_expected_cursor text, p_next_cursor text, p_account_id text, p_owner_fingerprint text, p_session_fingerprint text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_provisioning_complete_step(p_provisioning_key text, p_token_hash text, p_generation integer, p_expected_cursor text, p_next_cursor text, p_account_id text, p_owner_fingerprint text, p_session_fingerprint text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_provisioning_complete_step(p_provisioning_key text, p_token_hash text, p_generation integer, p_expected_cursor text, p_next_cursor text, p_account_id text, p_owner_fingerprint text, p_session_fingerprint text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_provisioning_complete_step(p_provisioning_key text, p_token_hash text, p_generation integer, p_expected_cursor text, p_next_cursor text, p_account_id text, p_owner_fingerprint text, p_session_fingerprint text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_provisioning_abandon(p_provisioning_key text, p_token_hash text, p_generation integer)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_saga public.yorisou_identity_provisioning_sagas%rowtype; v_rows int;
begin
  select * into v_saga from public.yorisou_identity_provisioning_sagas
   where provisioning_key = p_provisioning_key for update;
  if not found then return false; end if;
  if v_saga.account_id is not null then
    raise exception 'provisioning_abandon_refused_account_bound';
  end if;
  if v_saga.executor_token_hash is distinct from p_token_hash
     or v_saga.executor_generation is distinct from p_generation then
    raise exception 'provisioning_executor_mismatch';
  end if;

  delete from public.yorisou_identity_provisioning_sagas
   where provisioning_key = p_provisioning_key and account_id is null;
  get diagnostics v_rows = row_count;
  return v_rows > 0;
end $function$;

do $$ begin
  execute 'revoke all on function public.yorisou_provisioning_abandon(p_provisioning_key text, p_token_hash text, p_generation integer) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_provisioning_abandon(p_provisioning_key text, p_token_hash text, p_generation integer) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_provisioning_abandon(p_provisioning_key text, p_token_hash text, p_generation integer) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_provisioning_abandon(p_provisioning_key text, p_token_hash text, p_generation integer) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_identity_links_sync(p_owner_account_id text, p_owner_fingerprint text, p_links jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_link       jsonb;
  v_kind       text;
  v_digest     text;
  v_other      text;
  v_added      integer := 0;
  v_unchanged  integer := 0;
begin
  if p_owner_account_id is null or char_length(p_owner_account_id) = 0 then
    raise exception 'identity_link_owner_required';
  end if;
  if p_owner_fingerprint is null or p_owner_fingerprint !~ '^[0-9a-f]{64}$' then
    raise exception 'identity_link_owner_fingerprint_must_be_sha256_hex';
  end if;
  if p_links is null or jsonb_typeof(p_links) <> 'array' then
    raise exception 'identity_link_set_must_be_array';
  end if;

  perform 1 from public.yorisou_canonical_identity_links
   where owner_account_id = p_owner_account_id and link_state = 'active'
   for update;

  -- Validate the whole set BEFORE writing any of it. A partially applied identity set is a state no
  -- reader has a name for.
  for v_link in select * from jsonb_array_elements(p_links) loop
    v_kind   := v_link->>'kind';
    v_digest := v_link->>'digest';
    if v_kind is null or v_digest is null then
      raise exception 'identity_link_entry_requires_kind_and_digest';
    end if;
    if v_kind not in ('email','line_subject','user_profile','auth_identity','provisioning') then
      raise exception 'identity_link_kind_unknown:%', v_kind;
    end if;
    if v_kind in ('email','line_subject') and v_digest !~ '^[0-9a-f]{64}$' then
      raise exception 'identity_link_digest_must_be_sha256_hex:%', v_kind;
    end if;

    select owner_account_id into v_other
      from public.yorisou_canonical_identity_links
     where link_kind = v_kind and link_digest = v_digest and link_state = 'active'
     for update;
    if v_other is not null and v_other <> p_owner_account_id then
      raise exception 'identity_link_conflict:%', v_kind;
    end if;
  end loop;

  -- NO RETIREMENT HERE. Deliberately. See the header: the caller's link set comes from a read that
  -- can be stale, and retiring on absence lets that stale read destroy a true record.
  for v_link in select * from jsonb_array_elements(p_links) loop
    v_kind   := v_link->>'kind';
    v_digest := v_link->>'digest';
    if exists (
      select 1 from public.yorisou_canonical_identity_links
       where link_kind = v_kind and link_digest = v_digest
         and link_state = 'active' and owner_account_id = p_owner_account_id
    ) then
      v_unchanged := v_unchanged + 1;
      continue;
    end if;
    begin
      insert into public.yorisou_canonical_identity_links
        (owner_account_id, owner_fingerprint, link_kind, link_digest)
      values (p_owner_account_id, p_owner_fingerprint, v_kind, v_digest);
      v_added := v_added + 1;
    exception when unique_violation then
      select owner_account_id into v_other
        from public.yorisou_canonical_identity_links
       where link_kind = v_kind and link_digest = v_digest and link_state = 'active';
      if v_other is distinct from p_owner_account_id then
        raise exception 'identity_link_conflict:%', v_kind;
      end if;
      v_unchanged := v_unchanged + 1;
    end;
  end loop;

  return jsonb_build_object(
    'added', v_added, 'retired', 0, 'unchanged', v_unchanged,
    'active', (select count(*) from public.yorisou_canonical_identity_links
                where owner_account_id = p_owner_account_id and link_state = 'active')
  );
end $function$;

do $$ begin
  execute 'revoke all on function public.yorisou_identity_links_sync(p_owner_account_id text, p_owner_fingerprint text, p_links jsonb) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_identity_links_sync(p_owner_account_id text, p_owner_fingerprint text, p_links jsonb) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_identity_links_sync(p_owner_account_id text, p_owner_fingerprint text, p_links jsonb) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_identity_links_sync(p_owner_account_id text, p_owner_fingerprint text, p_links jsonb) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_identity_links_retire(p_owner_account_id text, p_link_kind text, p_link_digest text)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_owner   text;
  v_retired integer := 0;
begin
  if p_owner_account_id is null or char_length(p_owner_account_id) = 0 then
    raise exception 'identity_link_owner_required';
  end if;
  if p_link_kind is null or p_link_digest is null then
    raise exception 'identity_link_entry_requires_kind_and_digest';
  end if;

  select owner_account_id into v_owner
    from public.yorisou_canonical_identity_links
   where link_kind = p_link_kind and link_digest = p_link_digest and link_state = 'active'
   for update;

  if v_owner is null then return 0; end if;          -- already retired, or never held
  if v_owner <> p_owner_account_id then
    raise exception 'identity_link_conflict:%', p_link_kind;
  end if;

  update public.yorisou_canonical_identity_links
     set link_state = 'erased', owner_account_id = null, link_digest = null,
         erased_at = now(), updated_at = now()
   where link_kind = p_link_kind and link_digest = p_link_digest
     and link_state = 'active' and owner_account_id = p_owner_account_id;
  get diagnostics v_retired = row_count;
  return v_retired;
end $function$;

do $$ begin
  execute 'revoke all on function public.yorisou_identity_links_retire(p_owner_account_id text, p_link_kind text, p_link_digest text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_identity_links_retire(p_owner_account_id text, p_link_kind text, p_link_digest text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_identity_links_retire(p_owner_account_id text, p_link_kind text, p_link_digest text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_identity_links_retire(p_owner_account_id text, p_link_kind text, p_link_digest text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_identity_links_residue(p_owner_fingerprint text)
 RETURNS integer
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select count(*)::integer
    from public.yorisou_canonical_identity_links
   where owner_fingerprint = p_owner_fingerprint and link_state = 'active';
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_identity_links_residue(p_owner_fingerprint text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_identity_links_residue(p_owner_fingerprint text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_identity_links_residue(p_owner_fingerprint text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_identity_links_residue(p_owner_fingerprint text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_identity_links_for_owner(p_owner_account_id text)
 RETURNS TABLE(link_kind text, link_digest text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select link_kind, link_digest
    from public.yorisou_canonical_identity_links
   where owner_account_id = p_owner_account_id and link_state = 'active'
   order by link_kind, link_digest;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_identity_links_for_owner(p_owner_account_id text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_identity_links_for_owner(p_owner_account_id text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_identity_links_for_owner(p_owner_account_id text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_identity_links_for_owner(p_owner_account_id text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_identity_links_erase(p_owner_account_id text)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_erased integer := 0;
begin
  if p_owner_account_id is null or char_length(p_owner_account_id) = 0 then
    raise exception 'identity_link_owner_required';
  end if;

  perform 1 from public.yorisou_canonical_identity_links
   where owner_account_id = p_owner_account_id for update;

  update public.yorisou_canonical_identity_links
     set link_state = 'erased', owner_account_id = null, link_digest = null,
         erased_at = coalesce(erased_at, now()), updated_at = now()
   where owner_account_id = p_owner_account_id and link_state = 'active';
  get diagnostics v_erased = row_count;

  return v_erased;
end $function$;

do $$ begin
  execute 'revoke all on function public.yorisou_identity_links_erase(p_owner_account_id text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_identity_links_erase(p_owner_account_id text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_identity_links_erase(p_owner_account_id text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_identity_links_erase(p_owner_account_id text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_identity_link_owner(p_link_kind text, p_link_digest text)
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select owner_account_id
    from public.yorisou_canonical_identity_links
   where link_kind = p_link_kind and link_digest = p_link_digest and link_state = 'active'
   limit 1;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_identity_link_owner(p_link_kind text, p_link_digest text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_identity_link_owner(p_link_kind text, p_link_digest text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_identity_link_owner(p_link_kind text, p_link_digest text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_identity_link_owner(p_link_kind text, p_link_digest text) to service_role';
  end if;
end $$;
