-- Capability Package 5: owner-scoped experience cards and controlled discovery.
create table public.yorisou_experience_cards (
  id uuid primary key default gen_random_uuid(), project_id text not null default 'yorisou' check (project_id='yorisou'),
  owner_account_id text not null check (char_length(owner_account_id) between 1 and 200),
  source_saved_result_id uuid references public.yorisou_test_results(id) on delete set null,
  state_context text not null check (char_length(state_context) between 1 and 1200),
  situation text not null check (char_length(situation) between 1 and 3000), action_tried text not null check (char_length(action_tried) between 1 and 3000),
  perceived_outcome text not null check (char_length(perceived_outcome) between 1 and 3000), limitations text not null check (char_length(limitations) between 1 and 2000),
  may_fit text not null check (char_length(may_fit) between 1 and 1200), may_not_fit text not null check (char_length(may_not_fit) between 1 and 1200),
  visibility text not null default 'PRIVATE' check (visibility in ('PRIVATE','INVITE_ONLY','ANONYMOUS_SHARED','SIMILAR_STATE_ONLY','PSEUDONYMOUS_SHARED','PUBLIC_SAFE')),
  visibility_version integer not null default 1 check (visibility_version > 0), consented_at timestamptz, searchable boolean not null default false,
  audience_rule text not null default 'owner_only' check (audience_rule in ('owner_only','invite_token','anonymous_shared','similar_state_only')),
  moderation_status text not null default 'draft' check (moderation_status in ('draft','published','limited','removed')),
  provenance text not null default 'user_authored' check (provenance in ('user_authored','ai_organized')), ai_assistance_status text not null default 'none' check (ai_assistance_status in ('none','requested','accepted','rejected')),
  preview_confirmed_at timestamptz, published_at timestamptz, withdrawn_at timestamptz, deleted_at timestamptz, last_visibility_change_at timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint deferred_visibility_inactive check (visibility not in ('PSEUDONYMOUS_SHARED','PUBLIC_SAFE') or (searchable=false and moderation_status<>'published'))
);
create table public.yorisou_experience_visibility_events (id uuid primary key default gen_random_uuid(), project_id text not null default 'yorisou' check(project_id='yorisou'), experience_id uuid not null references public.yorisou_experience_cards(id) on delete cascade, owner_account_id text not null, from_visibility text, to_visibility text not null, consented_at timestamptz not null default now(), created_at timestamptz not null default now());
create table public.yorisou_experience_revisions (id uuid primary key default gen_random_uuid(), project_id text not null default 'yorisou' check(project_id='yorisou'), experience_id uuid not null references public.yorisou_experience_cards(id) on delete cascade, owner_account_id text not null, revision_number integer not null check(revision_number>0), content jsonb not null check(octet_length(content::text)<=24000), provenance text not null check(provenance in ('user_authored','ai_organized')), created_at timestamptz not null default now(), unique(experience_id,revision_number));
create table public.yorisou_experience_consents (id uuid primary key default gen_random_uuid(), project_id text not null default 'yorisou' check(project_id='yorisou'), experience_id uuid not null references public.yorisou_experience_cards(id) on delete cascade, owner_account_id text not null, visibility text not null, consent_version text not null default 'experience-share-v1', created_at timestamptz not null default now());
create table public.yorisou_experience_invites (id uuid primary key default gen_random_uuid(), project_id text not null default 'yorisou' check(project_id='yorisou'), experience_id uuid not null references public.yorisou_experience_cards(id) on delete cascade, owner_account_id text not null, token_hash text not null unique check(token_hash~'^[a-f0-9]{64}$'), expires_at timestamptz not null, revoked_at timestamptz, created_at timestamptz not null default now());
create table public.yorisou_experience_interactions (id uuid primary key default gen_random_uuid(), project_id text not null default 'yorisou' check(project_id='yorisou'), experience_id uuid not null references public.yorisou_experience_cards(id) on delete cascade, actor_account_id text not null, action text not null check(action in ('save','try','tried','helpful','not_relevant')), idempotency_key text not null check(char_length(idempotency_key) between 16 and 200), created_at timestamptz not null default now(), unique(experience_id,actor_account_id,action), unique(actor_account_id,idempotency_key));
create table public.yorisou_experience_reports (id uuid primary key default gen_random_uuid(), project_id text not null default 'yorisou' check(project_id='yorisou'), experience_id uuid not null references public.yorisou_experience_cards(id) on delete cascade, reporter_account_id text not null, reason text not null check(reason in ('unsafe','misleading','privacy','other')), note text check(note is null or char_length(note)<=1000), status text not null default 'open' check(status in ('open','resolved','dismissed')), created_at timestamptz not null default now(), unique(experience_id,reporter_account_id));
create table public.yorisou_experience_blocks (id uuid primary key default gen_random_uuid(), project_id text not null default 'yorisou' check(project_id='yorisou'), blocker_account_id text not null, blocked_owner_account_id text not null, created_at timestamptz not null default now(), unique(blocker_account_id,blocked_owner_account_id), check(blocker_account_id<>blocked_owner_account_id));
create table public.yorisou_experience_moderation_events (id uuid primary key default gen_random_uuid(), project_id text not null default 'yorisou' check(project_id='yorisou'), experience_id uuid not null references public.yorisou_experience_cards(id) on delete cascade, actor_account_id text not null, action text not null check(action in ('limit','remove','restore')), reason text not null check(char_length(reason) between 1 and 1000), created_at timestamptz not null default now());
create table public.yorisou_experience_events (id uuid primary key default gen_random_uuid(), project_id text not null default 'yorisou' check(project_id='yorisou'), experience_id uuid references public.yorisou_experience_cards(id) on delete cascade, actor_account_id text not null, event_type text not null check(event_type in ('draft_created','draft_updated','ai_structured','preview_confirmed','published','visibility_changed','discovered','interaction','reported','blocked','withdrawn','deleted','moderated')), metadata jsonb not null default '{}'::jsonb check(octet_length(metadata::text)<=4000), created_at timestamptz not null default now());
create index yorisou_experience_discovery_idx on public.yorisou_experience_cards(project_id,visibility,moderation_status,published_at desc) where deleted_at is null and withdrawn_at is null;
create index yorisou_experience_owner_idx on public.yorisou_experience_cards(owner_account_id,created_at desc);
alter table public.yorisou_experience_cards enable row level security; alter table public.yorisou_experience_visibility_events enable row level security; alter table public.yorisou_experience_revisions enable row level security; alter table public.yorisou_experience_consents enable row level security; alter table public.yorisou_experience_invites enable row level security; alter table public.yorisou_experience_interactions enable row level security; alter table public.yorisou_experience_reports enable row level security; alter table public.yorisou_experience_blocks enable row level security; alter table public.yorisou_experience_moderation_events enable row level security; alter table public.yorisou_experience_events enable row level security;
revoke all on table public.yorisou_experience_cards,public.yorisou_experience_visibility_events,public.yorisou_experience_revisions,public.yorisou_experience_consents,public.yorisou_experience_invites,public.yorisou_experience_interactions,public.yorisou_experience_reports,public.yorisou_experience_blocks,public.yorisou_experience_moderation_events,public.yorisou_experience_events from public;

create function public.record_yorisou_experience_interaction(p_experience_id uuid,p_actor_account_id text,p_action text,p_idempotency_key text)
returns uuid language plpgsql security definer set search_path=public as $$
declare v_id uuid;
begin
  if p_actor_account_id !~ '^[A-Za-z0-9._:-]{1,200}$' or p_action not in ('save','try','tried','helpful','not_relevant') or char_length(p_idempotency_key) not between 16 and 200 then raise exception 'invalid interaction input'; end if;
  if (select count(*) from public.yorisou_experience_interactions where actor_account_id=p_actor_account_id and created_at>now()-interval '1 hour') >= 60 then raise exception 'interaction rate limited'; end if;
  insert into public.yorisou_experience_interactions(project_id,experience_id,actor_account_id,action,idempotency_key) values('yorisou',p_experience_id,p_actor_account_id,p_action,p_idempotency_key) on conflict(actor_account_id,idempotency_key) do update set idempotency_key=excluded.idempotency_key returning id into v_id;
  return v_id;
end $$;
revoke all on function public.record_yorisou_experience_interaction(uuid,text,text,text) from public;
do $$ begin if exists(select 1 from pg_roles where rolname='anon') then execute 'revoke all on function public.record_yorisou_experience_interaction(uuid,text,text,text) from anon'; end if; if exists(select 1 from pg_roles where rolname='authenticated') then execute 'revoke all on function public.record_yorisou_experience_interaction(uuid,text,text,text) from authenticated'; end if; end $$;
grant execute on function public.record_yorisou_experience_interaction(uuid,text,text,text) to service_role;

create function public.enforce_yorisou_experience_card_rate() returns trigger language plpgsql security definer set search_path=public as $$
begin if (select count(*) from public.yorisou_experience_cards where owner_account_id=new.owner_account_id and created_at>now()-interval '1 hour')>=10 then raise exception 'experience card rate limited'; end if; return new; end $$;
create trigger yorisou_experience_card_rate before insert on public.yorisou_experience_cards for each row execute function public.enforce_yorisou_experience_card_rate();
create function public.enforce_yorisou_experience_report_rate() returns trigger language plpgsql security definer set search_path=public as $$
begin if (select count(*) from public.yorisou_experience_reports where reporter_account_id=new.reporter_account_id and created_at>now()-interval '1 hour')>=20 then raise exception 'experience report rate limited'; end if; return new; end $$;
create trigger yorisou_experience_report_rate before insert on public.yorisou_experience_reports for each row execute function public.enforce_yorisou_experience_report_rate();
revoke all on function public.enforce_yorisou_experience_card_rate(),public.enforce_yorisou_experience_report_rate() from public;
