-- POR-1 PROMOTION P6 — Account deletion jobs, frozen manifests, audit and the Production family erasure plan
--
-- PRODUCTION_LINEAGE. Generated by scripts/por1/compile-promotion.mjs from the FINAL Preview
-- catalogue — not from the 24-migration Preview history. Only the last definition of a
-- `create or replace` chain is live, so promoting the history would promote bodies that were
-- already replaced, including the ones replaced because they were wrong.
--
-- Regenerate and verify with:  npm run por1:promotion-check
--
-- CONTENTS
--   tables 3 · sequences 0 · functions 25 · triggers 0
--
-- APPLY SEMANTICS
--   Every statement is guarded (`if not exists` / catalogue probe), so a partial failure can be
--   retried without a human reconstructing which half applied.
--
-- ROLLBACK CLASS
--   SCHEMA_REVERSIBLE_WHILE_FLAGS_OFF — additive only. Nothing here alters or drops an existing
--   Production object, so with the POR-1 capability controls unset these objects are inert: the
--   old application never names them. The Production incident response is to disable the
--   capability and roll back the application, NOT to drop the schema.
--
-- EXISTING-DATA IMPACT
--   None. No backfill, no column change to a populated table, no data movement.
--
-- LOCK CLASS
--   CREATE TABLE / CREATE INDEX on brand-new empty relations. No lock is taken on any table the
--   running application reads or writes.


-- ── tables ─────────────────────────────────────────────────────────────────

-- yorisou_account_deletion_jobs

do $$
declare
  v_unexpected text;
begin
  if to_regclass('public.yorisou_account_deletion_jobs') is null then
    create table public.yorisou_account_deletion_jobs (
    id uuid default gen_random_uuid() not null,
    owner_account_id text,
    owner_fingerprint text not null,
    state text default 'requested'::text not null,
    contract_version text default 'por1-v1'::text not null,
    attempt_count integer default 0 not null,
    last_error_code text,
    legal_hold_reason text,
    requested_at timestamp with time zone default now() not null,
    verified_at timestamp with time zone,
    locked_at timestamp with time zone,
    completed_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    updated_at timestamp with time zone default now() not null,
    execution_cursor text,
    irreversible_started_at timestamp with time zone,
    mutation_gate_closed_at timestamp with time zone,
    executor_token_hash text,
    executor_generation integer default 0 not null,
    executor_claimed_at timestamp with time zone,
    executor_expires_at timestamp with time zone,
    terminal_deidentified_at timestamp with time zone,
    terminal_deidentification_reason text
    );
  else
    select string_agg(name, ', ' order by name) into v_unexpected from (
      select a.attname as name from pg_attribute a
       where a.attrelid = 'public.yorisou_account_deletion_jobs'::regclass and a.attnum > 0 and not a.attisdropped
         and a.attname <> all (array['id', 'owner_account_id', 'owner_fingerprint', 'state', 'contract_version', 'attempt_count', 'last_error_code', 'legal_hold_reason', 'requested_at', 'verified_at', 'locked_at', 'completed_at', 'cancelled_at', 'updated_at', 'execution_cursor', 'irreversible_started_at', 'mutation_gate_closed_at', 'executor_token_hash', 'executor_generation', 'executor_claimed_at', 'executor_expires_at', 'terminal_deidentified_at', 'terminal_deidentification_reason'])
      union all
      select c.name from unnest(array['id', 'owner_account_id', 'owner_fingerprint', 'state', 'contract_version', 'attempt_count', 'last_error_code', 'legal_hold_reason', 'requested_at', 'verified_at', 'locked_at', 'completed_at', 'cancelled_at', 'updated_at', 'execution_cursor', 'irreversible_started_at', 'mutation_gate_closed_at', 'executor_token_hash', 'executor_generation', 'executor_claimed_at', 'executor_expires_at', 'terminal_deidentified_at', 'terminal_deidentification_reason']) c(name)
       where not exists (
         select 1 from pg_attribute a
          where a.attrelid = 'public.yorisou_account_deletion_jobs'::regclass and a.attname = c.name
            and a.attnum > 0 and not a.attisdropped
       )
    ) s;
    if v_unexpected is not null then
      raise exception 'POR-1: yorisou_account_deletion_jobs already exists with a different shape (differing column(s): %). Refusing to promote onto it.', v_unexpected;
    end if;
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_deletion_jobs_attempt_count_check' and conrelid = 'public.yorisou_account_deletion_jobs'::regclass) then
    alter table public.yorisou_account_deletion_jobs add constraint yorisou_account_deletion_jobs_attempt_count_check CHECK ((attempt_count >= 0));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_deletion_jobs_cursor_check' and conrelid = 'public.yorisou_account_deletion_jobs'::regclass) then
    alter table public.yorisou_account_deletion_jobs add constraint yorisou_account_deletion_jobs_cursor_check CHECK (((execution_cursor IS NULL) OR (execution_cursor = ANY (ARRAY['mutation_draining'::text, 'lock_marker'::text, 'session_revocation'::text, 'database_erasure'::text, 'storage_erasure'::text, 'identity_erasure'::text, 'verifying'::text, 'finalizing'::text, 'completed'::text]))));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_deletion_jobs_executor_shape' and conrelid = 'public.yorisou_account_deletion_jobs'::regclass) then
    alter table public.yorisou_account_deletion_jobs add constraint yorisou_account_deletion_jobs_executor_shape CHECK (((executor_generation >= 0) AND ((executor_token_hash IS NULL) OR ((char_length(executor_token_hash) >= 32) AND (char_length(executor_token_hash) <= 128)))));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_deletion_jobs_last_error_code_check' and conrelid = 'public.yorisou_account_deletion_jobs'::regclass) then
    alter table public.yorisou_account_deletion_jobs add constraint yorisou_account_deletion_jobs_last_error_code_check CHECK (((last_error_code IS NULL) OR (char_length(last_error_code) <= 80)));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_deletion_jobs_legal_hold_reason_check' and conrelid = 'public.yorisou_account_deletion_jobs'::regclass) then
    alter table public.yorisou_account_deletion_jobs add constraint yorisou_account_deletion_jobs_legal_hold_reason_check CHECK (((legal_hold_reason IS NULL) OR (char_length(legal_hold_reason) <= 200)));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_deletion_jobs_owner_account_id_key' and conrelid = 'public.yorisou_account_deletion_jobs'::regclass) then
    alter table public.yorisou_account_deletion_jobs add constraint yorisou_account_deletion_jobs_owner_account_id_key UNIQUE (owner_account_id);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_deletion_jobs_owner_shape' and conrelid = 'public.yorisou_account_deletion_jobs'::regclass) then
    alter table public.yorisou_account_deletion_jobs add constraint yorisou_account_deletion_jobs_owner_shape CHECK (((owner_account_id IS NULL) = ((state = 'completed'::text) OR (terminal_deidentified_at IS NOT NULL))));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_deletion_jobs_pkey' and conrelid = 'public.yorisou_account_deletion_jobs'::regclass) then
    alter table public.yorisou_account_deletion_jobs add constraint yorisou_account_deletion_jobs_pkey PRIMARY KEY (id);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_deletion_jobs_state_check' and conrelid = 'public.yorisou_account_deletion_jobs'::regclass) then
    alter table public.yorisou_account_deletion_jobs add constraint yorisou_account_deletion_jobs_state_check CHECK ((state = ANY (ARRAY['requested'::text, 'identity_verified'::text, 'locked'::text, 'database_erasure'::text, 'storage_erasure'::text, 'identity_erasure'::text, 'verifying'::text, 'completed'::text, 'failed_retryable'::text, 'failed_terminal'::text, 'cancelled'::text, 'legal_hold'::text])));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_deletion_jobs_terminal_deid_reason' and conrelid = 'public.yorisou_account_deletion_jobs'::regclass) then
    alter table public.yorisou_account_deletion_jobs add constraint yorisou_account_deletion_jobs_terminal_deid_reason CHECK (((terminal_deidentification_reason IS NULL) OR (terminal_deidentification_reason = 'manifest_missing_pre_irreversible'::text)));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_deletion_jobs_terminal_deid_shape' and conrelid = 'public.yorisou_account_deletion_jobs'::regclass) then
    alter table public.yorisou_account_deletion_jobs add constraint yorisou_account_deletion_jobs_terminal_deid_shape CHECK (((terminal_deidentified_at IS NULL) OR ((state = 'failed_terminal'::text) AND (owner_account_id IS NULL) AND (irreversible_started_at IS NULL) AND (terminal_deidentification_reason IS NOT NULL) AND (owner_fingerprint IS NOT NULL))));
  end if;
end $$;

create index if not exists yorisou_account_deletion_jobs_fingerprint_idx ON public.yorisou_account_deletion_jobs USING btree (owner_fingerprint);

create index if not exists yorisou_account_deletion_jobs_state_idx ON public.yorisou_account_deletion_jobs USING btree (state);

alter table public.yorisou_account_deletion_jobs enable row level security;

alter table public.yorisou_account_deletion_jobs force row level security;

revoke all on table public.yorisou_account_deletion_jobs from public;
do $$ begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on table public.yorisou_account_deletion_jobs from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on table public.yorisou_account_deletion_jobs from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant delete, insert, references, select, trigger, truncate, update on table public.yorisou_account_deletion_jobs to service_role';
  end if;
end $$;

-- yorisou_account_deletion_manifests

do $$
declare
  v_unexpected text;
begin
  if to_regclass('public.yorisou_account_deletion_manifests') is null then
    create table public.yorisou_account_deletion_manifests (
    job_id uuid not null,
    contract_version text default 'por1-manifest-v1'::text not null,
    payload jsonb not null,
    created_at timestamp with time zone default now() not null
    );
  else
    select string_agg(name, ', ' order by name) into v_unexpected from (
      select a.attname as name from pg_attribute a
       where a.attrelid = 'public.yorisou_account_deletion_manifests'::regclass and a.attnum > 0 and not a.attisdropped
         and a.attname <> all (array['job_id', 'contract_version', 'payload', 'created_at'])
      union all
      select c.name from unnest(array['job_id', 'contract_version', 'payload', 'created_at']) c(name)
       where not exists (
         select 1 from pg_attribute a
          where a.attrelid = 'public.yorisou_account_deletion_manifests'::regclass and a.attname = c.name
            and a.attnum > 0 and not a.attisdropped
       )
    ) s;
    if v_unexpected is not null then
      raise exception 'POR-1: yorisou_account_deletion_manifests already exists with a different shape (differing column(s): %). Refusing to promote onto it.', v_unexpected;
    end if;
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_deletion_manifests_bounded' and conrelid = 'public.yorisou_account_deletion_manifests'::regclass) then
    alter table public.yorisou_account_deletion_manifests add constraint yorisou_account_deletion_manifests_bounded CHECK ((pg_column_size(payload) <= 65536));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_deletion_manifests_job_id_fkey' and conrelid = 'public.yorisou_account_deletion_manifests'::regclass) then
    alter table public.yorisou_account_deletion_manifests add constraint yorisou_account_deletion_manifests_job_id_fkey FOREIGN KEY (job_id) REFERENCES yorisou_account_deletion_jobs(id) ON DELETE CASCADE;
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_deletion_manifests_pkey' and conrelid = 'public.yorisou_account_deletion_manifests'::regclass) then
    alter table public.yorisou_account_deletion_manifests add constraint yorisou_account_deletion_manifests_pkey PRIMARY KEY (job_id);
  end if;
end $$;

alter table public.yorisou_account_deletion_manifests enable row level security;

alter table public.yorisou_account_deletion_manifests force row level security;

revoke all on table public.yorisou_account_deletion_manifests from public;
do $$ begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on table public.yorisou_account_deletion_manifests from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on table public.yorisou_account_deletion_manifests from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant delete, insert, references, select, trigger, truncate, update on table public.yorisou_account_deletion_manifests to service_role';
  end if;
end $$;

-- yorisou_account_deletion_audit

do $$
declare
  v_unexpected text;
begin
  if to_regclass('public.yorisou_account_deletion_audit') is null then
    create table public.yorisou_account_deletion_audit (
    id uuid default gen_random_uuid() not null,
    job_id uuid not null,
    stage text not null,
    outcome text not null,
    detail jsonb default '{}'::jsonb not null,
    created_at timestamp with time zone default now() not null
    );
  else
    select string_agg(name, ', ' order by name) into v_unexpected from (
      select a.attname as name from pg_attribute a
       where a.attrelid = 'public.yorisou_account_deletion_audit'::regclass and a.attnum > 0 and not a.attisdropped
         and a.attname <> all (array['id', 'job_id', 'stage', 'outcome', 'detail', 'created_at'])
      union all
      select c.name from unnest(array['id', 'job_id', 'stage', 'outcome', 'detail', 'created_at']) c(name)
       where not exists (
         select 1 from pg_attribute a
          where a.attrelid = 'public.yorisou_account_deletion_audit'::regclass and a.attname = c.name
            and a.attnum > 0 and not a.attisdropped
       )
    ) s;
    if v_unexpected is not null then
      raise exception 'POR-1: yorisou_account_deletion_audit already exists with a different shape (differing column(s): %). Refusing to promote onto it.', v_unexpected;
    end if;
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_deletion_audit_detail_is_bounded' and conrelid = 'public.yorisou_account_deletion_audit'::regclass) then
    alter table public.yorisou_account_deletion_audit add constraint yorisou_account_deletion_audit_detail_is_bounded CHECK ((pg_column_size(detail) <= 4096));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_deletion_audit_job_id_fkey' and conrelid = 'public.yorisou_account_deletion_audit'::regclass) then
    alter table public.yorisou_account_deletion_audit add constraint yorisou_account_deletion_audit_job_id_fkey FOREIGN KEY (job_id) REFERENCES yorisou_account_deletion_jobs(id) ON DELETE CASCADE;
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_deletion_audit_outcome_check' and conrelid = 'public.yorisou_account_deletion_audit'::regclass) then
    alter table public.yorisou_account_deletion_audit add constraint yorisou_account_deletion_audit_outcome_check CHECK ((outcome = ANY (ARRAY['ok'::text, 'skipped'::text, 'failed'::text])));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_deletion_audit_pkey' and conrelid = 'public.yorisou_account_deletion_audit'::regclass) then
    alter table public.yorisou_account_deletion_audit add constraint yorisou_account_deletion_audit_pkey PRIMARY KEY (id);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_deletion_audit_stage_check' and conrelid = 'public.yorisou_account_deletion_audit'::regclass) then
    alter table public.yorisou_account_deletion_audit add constraint yorisou_account_deletion_audit_stage_check CHECK (((char_length(stage) >= 1) AND (char_length(stage) <= 60)));
  end if;
end $$;

create index if not exists yorisou_account_deletion_audit_job_idx ON public.yorisou_account_deletion_audit USING btree (job_id, created_at);

alter table public.yorisou_account_deletion_audit enable row level security;

alter table public.yorisou_account_deletion_audit force row level security;

revoke all on table public.yorisou_account_deletion_audit from public;
do $$ begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on table public.yorisou_account_deletion_audit from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on table public.yorisou_account_deletion_audit from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant delete, insert, references, select, trigger, truncate, update on table public.yorisou_account_deletion_audit to service_role';
  end if;
end $$;

-- ── functions ──────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_verify_database(p_owner_account_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_tables text[] := array[
    'yorisou_test_results','yorisou_ai_reflections','yorisou_ai_runs',
    'yorisou_daily_state_records','yorisou_values_assessments',
    'yorisou_private_check_in_plans','yorisou_private_memory_items','yorisou_private_recommendations',
    'yorisou_experience_cards','yorisou_recommendation_sets','yorisou_recommendation_actions',
    'yorisou_canonical_recommendation_sets','yorisou_canonical_recommendation_items',
    'yorisou_canonical_recommendation_actions','yorisou_assessment_attempts',
    'yorisou_account_deletion_requests'
  ];
  v_t text; v_n bigint; v_left jsonb := '{}'::jsonb;
begin
  foreach v_t in array v_tables loop
    if to_regclass('public.' || v_t) is null then continue; end if;
    execute format('select count(*) from public.%I where owner_account_id = $1', v_t)
      into v_n using p_owner_account_id;
    if v_n > 0 then v_left := v_left || jsonb_build_object(v_t, v_n); end if;
  end loop;

  -- Results may survive ONLY as content-free tombstones, and a tombstone has no owner by contract.
  if to_regclass('public.yorisou_assessment_results') is not null then
    select count(*) into v_n from public.yorisou_assessment_results
     where owner_account_id = p_owner_account_id;
    if v_n > 0 then v_left := v_left || jsonb_build_object('yorisou_assessment_results_owned', v_n); end if;
  end if;

  return v_left;   -- '{}' means clean
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_verify_database(p_owner_account_id text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_verify_database(p_owner_account_id text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_verify_database(p_owner_account_id text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_verify_database(p_owner_account_id text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_state_for_cursor(p_cursor text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  select case p_cursor
    when 'mutation_draining'  then 'identity_verified'
    when 'lock_marker'        then 'locked'
    when 'session_revocation' then 'locked'
    when 'database_erasure'   then 'database_erasure'
    when 'storage_erasure'    then 'storage_erasure'
    when 'identity_erasure'   then 'identity_erasure'
    when 'verifying'          then 'verifying'
    when 'finalizing'         then 'verifying'
    when 'completed'          then 'completed'
    else null
  end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_state_for_cursor(p_cursor text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_state_for_cursor(p_cursor text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_state_for_cursor(p_cursor text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_state_for_cursor(p_cursor text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_stage_rank(p_stage text)
 RETURNS integer
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  select case p_stage
    when 'mutation_draining'  then 1
    when 'lock_marker'        then 2
    when 'session_revocation' then 3
    when 'database_erasure'   then 4
    when 'storage_erasure'    then 5
    when 'identity_erasure'   then 6
    when 'verifying'          then 7
    when 'finalizing'         then 8
    when 'completed'          then 9
    else null
  end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_stage_rank(p_stage text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_stage_rank(p_stage text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_stage_rank(p_stage text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_stage_rank(p_stage text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_resume_state(p_owner_account_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_job public.yorisou_account_deletion_jobs%rowtype; v_now timestamptz := now();
begin
  select * into v_job from public.yorisou_account_deletion_jobs
   where owner_account_id = p_owner_account_id;
  if not found then return jsonb_build_object('state', 'none'); end if;

  return jsonb_build_object(
    'state', v_job.state,
    'cursor', v_job.execution_cursor,
    'irreversible', v_job.irreversible_started_at is not null,
    'attemptCount', v_job.attempt_count,
    'lastErrorCode', v_job.last_error_code,
    'executorHeld', v_job.executor_token_hash is not null
                    and v_job.executor_expires_at is not null
                    and v_job.executor_expires_at > v_now,
    'executorGeneration', v_job.executor_generation,
    'hasManifest', exists (select 1 from public.yorisou_account_deletion_manifests where job_id = v_job.id)
  );
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_resume_state(p_owner_account_id text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_resume_state(p_owner_account_id text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_resume_state(p_owner_account_id text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_resume_state(p_owner_account_id text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_require_executor(p_owner_account_id text, p_token_hash text, p_generation integer)
 RETURNS yorisou_account_deletion_jobs
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_job public.yorisou_account_deletion_jobs%rowtype;
begin
  select * into v_job from public.yorisou_account_deletion_jobs
   where owner_account_id = p_owner_account_id for update;
  if not found then raise exception 'account_deletion_job_not_found'; end if;

  if v_job.executor_token_hash is null or v_job.executor_token_hash <> p_token_hash then
    raise exception 'account_deletion_executor_not_owner';
  end if;
  if v_job.executor_generation <> p_generation then
    raise exception 'account_deletion_executor_stale_generation';
  end if;
  if v_job.executor_expires_at is null or v_job.executor_expires_at <= now() then
    raise exception 'account_deletion_executor_lease_expired';
  end if;
  return v_job;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_require_executor(p_owner_account_id text, p_token_hash text, p_generation integer) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_require_executor(p_owner_account_id text, p_token_hash text, p_generation integer) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_require_executor(p_owner_account_id text, p_token_hash text, p_generation integer) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_require_executor(p_owner_account_id text, p_token_hash text, p_generation integer) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_record_retryable_error(p_owner_account_id text, p_token_hash text, p_generation integer, p_error_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_job public.yorisou_account_deletion_jobs%rowtype;
begin
  v_job := public.yorisou_account_deletion_require_executor(p_owner_account_id, p_token_hash, p_generation);

  update public.yorisou_account_deletion_jobs
     set state           = 'failed_retryable',
         last_error_code = left(coalesce(p_error_code, 'unknown'), 80),
         attempt_count   = attempt_count + 1,
         -- execution_cursor is NOT touched. That is the point.
         updated_at      = now()
   where id = v_job.id
  returning * into v_job;

  insert into public.yorisou_account_deletion_audit (job_id, stage, outcome, detail)
  values (v_job.id, coalesce(v_job.execution_cursor, 'unknown'), 'failed',
          jsonb_build_object('retryable', true, 'generation', p_generation));

  return jsonb_build_object(
    'cursor', v_job.execution_cursor,
    'attemptCount', v_job.attempt_count,
    'irreversible', v_job.irreversible_started_at is not null
  );
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_record_retryable_error(p_owner_account_id text, p_token_hash text, p_generation integer, p_error_code text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_record_retryable_error(p_owner_account_id text, p_token_hash text, p_generation integer, p_error_code text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_record_retryable_error(p_owner_account_id text, p_token_hash text, p_generation integer, p_error_code text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_record_retryable_error(p_owner_account_id text, p_token_hash text, p_generation integer, p_error_code text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_mutation_gate_status(p_owner_account_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_state text; v_gen integer; v_active integer;
begin
  select gate_state, generation into v_state, v_gen
    from public.yorisou_account_mutation_gates where owner_account_id = p_owner_account_id;
  select count(*) into v_active from public.yorisou_account_mutation_leases
   where owner_account_id = p_owner_account_id and released_at is null and drained_at is null;
  return jsonb_build_object(
    'gateState', coalesce(v_state, 'open'),
    'generation', coalesce(v_gen, 1),
    'activeLeases', v_active
  );
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_mutation_gate_status(p_owner_account_id text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_mutation_gate_status(p_owner_account_id text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_mutation_gate_status(p_owner_account_id text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_mutation_gate_status(p_owner_account_id text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_mark_cursor(p_owner_account_id text, p_cursor text, p_irreversible boolean DEFAULT false)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  raise exception 'account_deletion_mark_cursor_retired_use_complete_step';
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_mark_cursor(p_owner_account_id text, p_cursor text, p_irreversible boolean) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_mark_cursor(p_owner_account_id text, p_cursor text, p_irreversible boolean) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_mark_cursor(p_owner_account_id text, p_cursor text, p_irreversible boolean) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_mark_cursor(p_owner_account_id text, p_cursor text, p_irreversible boolean) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_manifest_put(p_owner_account_id text, p_token_hash text, p_generation integer, p_payload jsonb)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_job public.yorisou_account_deletion_jobs%rowtype;
begin
  v_job := public.yorisou_account_deletion_require_executor(p_owner_account_id, p_token_hash, p_generation);

  if v_job.irreversible_started_at is not null then
    raise exception 'account_deletion_manifest_frozen';
  end if;
  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception 'account_deletion_manifest_invalid';
  end if;

  insert into public.yorisou_account_deletion_manifests (job_id, payload)
  values (v_job.id, p_payload)
  on conflict (job_id) do nothing;   -- immutable: a second write is a no-op, never an overwrite
  return true;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_manifest_put(p_owner_account_id text, p_token_hash text, p_generation integer, p_payload jsonb) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_manifest_put(p_owner_account_id text, p_token_hash text, p_generation integer, p_payload jsonb) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_manifest_put(p_owner_account_id text, p_token_hash text, p_generation integer, p_payload jsonb) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_manifest_put(p_owner_account_id text, p_token_hash text, p_generation integer, p_payload jsonb) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_manifest_get(p_job_id uuid)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select payload from public.yorisou_account_deletion_manifests where job_id = p_job_id;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_manifest_get(p_job_id uuid) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_manifest_get(p_job_id uuid) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_manifest_get(p_job_id uuid) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_manifest_get(p_job_id uuid) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_irreversible_rank()
 RETURNS integer
 LANGUAGE sql
 IMMUTABLE
AS $function$ select 2 $function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_irreversible_rank() from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_irreversible_rank() from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_irreversible_rank() from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_irreversible_rank() to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_fingerprint(p_owner_account_id text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  select encode(sha256(convert_to('yorisou-account-deletion-v1:' || coalesce(p_owner_account_id, ''), 'utf8')), 'hex');
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_fingerprint(p_owner_account_id text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_fingerprint(p_owner_account_id text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_fingerprint(p_owner_account_id text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_fingerprint(p_owner_account_id text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_finalize(p_owner_account_id text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_id uuid; v_state text; v_left jsonb;
begin
  select id, state into v_id, v_state from public.yorisou_account_deletion_jobs
   where owner_account_id = p_owner_account_id for update;
  if not found then raise exception 'account_deletion_job_not_found'; end if;
  if v_state <> 'verifying' then raise exception 'account_deletion_not_verifying'; end if;

  v_left := public.yorisou_account_deletion_verify_database(p_owner_account_id);
  if v_left <> '{}'::jsonb then
    update public.yorisou_account_deletion_jobs
       set state='failed_retryable', last_error_code='verification_residue',
           attempt_count=attempt_count+1, updated_at=now()
     where id = v_id;
    insert into public.yorisou_account_deletion_audit (job_id, stage, outcome, detail)
    values (v_id, 'verifying', 'failed', jsonb_build_object('residue', v_left));
    return false;
  end if;

  update public.yorisou_account_deletion_jobs
     set state='completed', owner_account_id=null, completed_at=now(), updated_at=now()
   where id = v_id;
  insert into public.yorisou_account_deletion_audit (job_id, stage, outcome)
  values (v_id, 'completed', 'ok');
  return true;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_finalize(p_owner_account_id text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_finalize(p_owner_account_id text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_finalize(p_owner_account_id text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_finalize(p_owner_account_id text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_finalize_step(p_owner_account_id text, p_token_hash text, p_generation integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_job public.yorisou_account_deletion_jobs%rowtype; v_left jsonb;
begin
  v_job := public.yorisou_account_deletion_require_executor(p_owner_account_id, p_token_hash, p_generation);

  if v_job.execution_cursor is distinct from 'finalizing' then
    raise exception 'account_deletion_cursor_mismatch_expected_finalizing_actual_%',
      coalesce(v_job.execution_cursor, 'null');
  end if;

  v_left := public.yorisou_account_deletion_verify_database(p_owner_account_id);
  if v_left <> '{}'::jsonb then
    update public.yorisou_account_deletion_jobs
       set state='failed_retryable', last_error_code='verification_residue',
           attempt_count = attempt_count + 1, updated_at = now()
     where id = v_job.id;      -- cursor preserved: the retry re-runs finalizing, nothing earlier
    insert into public.yorisou_account_deletion_audit (job_id, stage, outcome, detail)
    values (v_job.id, 'finalizing', 'failed', jsonb_build_object('residue', v_left));
    return jsonb_build_object('completed', false, 'residue', v_left);
  end if;

  update public.yorisou_account_deletion_jobs
     set state = 'completed',
         execution_cursor = 'completed',
         owner_account_id = null,
         completed_at = now(),
         executor_token_hash = null,
         executor_expires_at = null,
         updated_at = now()
   where id = v_job.id;

  insert into public.yorisou_account_deletion_audit (job_id, stage, outcome)
  values (v_job.id, 'completed', 'ok');

  return jsonb_build_object('completed', true);
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_finalize_step(p_owner_account_id text, p_token_hash text, p_generation integer) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_finalize_step(p_owner_account_id text, p_token_hash text, p_generation integer) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_finalize_step(p_owner_account_id text, p_token_hash text, p_generation integer) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_finalize_step(p_owner_account_id text, p_token_hash text, p_generation integer) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_executor_renew(p_owner_account_id text, p_token_hash text, p_generation integer, p_ttl_seconds integer DEFAULT 90)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_rows integer;
begin
  if p_ttl_seconds is null or p_ttl_seconds < 5 or p_ttl_seconds > 600 then
    raise exception 'account_deletion_executor_ttl_out_of_range';
  end if;
  update public.yorisou_account_deletion_jobs
     set executor_expires_at = now() + make_interval(secs => p_ttl_seconds), updated_at = now()
   where owner_account_id = p_owner_account_id
     and executor_token_hash = p_token_hash
     and executor_generation = p_generation
     and executor_expires_at > now();
  get diagnostics v_rows = row_count;
  return v_rows = 1;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_executor_renew(p_owner_account_id text, p_token_hash text, p_generation integer, p_ttl_seconds integer) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_executor_renew(p_owner_account_id text, p_token_hash text, p_generation integer, p_ttl_seconds integer) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_executor_renew(p_owner_account_id text, p_token_hash text, p_generation integer, p_ttl_seconds integer) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_executor_renew(p_owner_account_id text, p_token_hash text, p_generation integer, p_ttl_seconds integer) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_executor_release(p_owner_account_id text, p_token_hash text, p_generation integer)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_rows integer;
begin
  -- The generation is NOT bumped here. Releasing is giving the job back, not invalidating the next
  -- holder before they exist; the bump belongs to the claim.
  update public.yorisou_account_deletion_jobs
     set executor_token_hash = null, executor_expires_at = null, updated_at = now()
   where owner_account_id = p_owner_account_id
     and executor_token_hash = p_token_hash
     and executor_generation = p_generation;
  get diagnostics v_rows = row_count;
  return v_rows = 1;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_executor_release(p_owner_account_id text, p_token_hash text, p_generation integer) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_executor_release(p_owner_account_id text, p_token_hash text, p_generation integer) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_executor_release(p_owner_account_id text, p_token_hash text, p_generation integer) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_executor_release(p_owner_account_id text, p_token_hash text, p_generation integer) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_executor_claim(p_owner_account_id text, p_token_hash text, p_ttl_seconds integer DEFAULT 90)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_job public.yorisou_account_deletion_jobs%rowtype; v_cursor text;
begin
  if p_owner_account_id is null or char_length(p_owner_account_id) = 0 then
    raise exception 'account_deletion_owner_required';
  end if;
  if p_token_hash is null or char_length(p_token_hash) < 32 then
    raise exception 'account_deletion_executor_token_required';
  end if;
  if p_ttl_seconds is null or p_ttl_seconds < 5 or p_ttl_seconds > 600 then
    raise exception 'account_deletion_executor_ttl_out_of_range';
  end if;

  select * into v_job from public.yorisou_account_deletion_jobs
   where owner_account_id = p_owner_account_id for update;
  if not found then raise exception 'account_deletion_job_not_found'; end if;

  if v_job.state in ('completed','cancelled','failed_terminal','legal_hold') then
    raise exception 'account_deletion_not_claimable_%', v_job.state;
  end if;

  -- Someone else is driving, and their claim has not lapsed.
  if v_job.executor_token_hash is not null
     and v_job.executor_token_hash <> p_token_hash
     and v_job.executor_expires_at is not null
     and v_job.executor_expires_at > now() then
    return jsonb_build_object(
      'claimed', false,
      'reason', 'executor_already_claimed',
      'generation', v_job.executor_generation,
      'cursor', v_job.execution_cursor,
      'irreversible', v_job.irreversible_started_at is not null
    );
  end if;

  -- First run of a job that has only been opened and verified.
  v_cursor := coalesce(v_job.execution_cursor, 'mutation_draining');

  update public.yorisou_account_deletion_jobs
     set executor_token_hash = p_token_hash,
         -- Bumped on EVERY claim, including a re-claim by the same executor: a token is not a
         -- generation, and a stale in-flight step from an earlier claim must fail even when the
         -- worker that issued it is the one claiming now.
         executor_generation = executor_generation + 1,
         executor_claimed_at = now(),
         executor_expires_at = now() + make_interval(secs => p_ttl_seconds),
         execution_cursor    = v_cursor,
         updated_at          = now()
   where id = v_job.id
  returning * into v_job;

  return jsonb_build_object(
    'claimed', true,
    'generation', v_job.executor_generation,
    'cursor', v_job.execution_cursor,
    'state', v_job.state,
    'irreversible', v_job.irreversible_started_at is not null,
    'attemptCount', v_job.attempt_count
  );
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_executor_claim(p_owner_account_id text, p_token_hash text, p_ttl_seconds integer) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_executor_claim(p_owner_account_id text, p_token_hash text, p_ttl_seconds integer) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_executor_claim(p_owner_account_id text, p_token_hash text, p_ttl_seconds integer) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_executor_claim(p_owner_account_id text, p_token_hash text, p_ttl_seconds integer) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_drain_gate(p_owner_account_id text, p_token_hash text, p_generation integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_job public.yorisou_account_deletion_jobs%rowtype;
        v_gate public.yorisou_account_mutation_gates%rowtype;
        v_active integer;
begin
  v_job := public.yorisou_account_deletion_require_executor(p_owner_account_id, p_token_hash, p_generation);

  insert into public.yorisou_account_mutation_gates (owner_account_id)
  values (p_owner_account_id) on conflict (owner_account_id) do nothing;

  select * into v_gate from public.yorisou_account_mutation_gates
   where owner_account_id = p_owner_account_id for update;

  if v_gate.gate_state = 'open' then
    update public.yorisou_account_mutation_gates
       set gate_state = 'draining', generation = generation + 1, updated_at = now()
     where owner_account_id = p_owner_account_id
    returning * into v_gate;
  end if;

  -- Abandon ONLY what cannot still be executing: expired PLUS the full execution grace. An expired
  -- lease inside the grace still blocks, because expiry proves the TTL elapsed, not that the process
  -- holding it has stopped running.
  update public.yorisou_account_mutation_leases
     set drained_at = now()
   where owner_account_id = p_owner_account_id
     and released_at is null
     and drained_at is null
     and expires_at + public.yorisou_account_mutation_execution_grace()
         < public.yorisou_account_mutation_clock();

  select count(*) into v_active from public.yorisou_account_mutation_leases
   where owner_account_id = p_owner_account_id
     and released_at is null and drained_at is null;

  if v_active = 0 and v_gate.gate_state = 'draining' then
    update public.yorisou_account_mutation_gates
       set gate_state = 'closed', closed_at = now(), updated_at = now()
     where owner_account_id = p_owner_account_id
    returning * into v_gate;
  end if;

  if v_gate.gate_state = 'closed' and v_active = 0 then
    update public.yorisou_account_deletion_jobs
       set mutation_gate_closed_at = coalesce(mutation_gate_closed_at, now()), updated_at = now()
     where id = v_job.id;
  end if;

  return jsonb_build_object(
    'gateState',  v_gate.gate_state,
    'generation', v_gate.generation,
    'activeLeases', v_active,
    'drained', v_active = 0 and v_gate.gate_state = 'closed'
  );
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_drain_gate(p_owner_account_id text, p_token_hash text, p_generation integer) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_drain_gate(p_owner_account_id text, p_token_hash text, p_generation integer) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_drain_gate(p_owner_account_id text, p_token_hash text, p_generation integer) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_drain_gate(p_owner_account_id text, p_token_hash text, p_generation integer) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_complete_step(p_owner_account_id text, p_token_hash text, p_generation integer, p_expected_cursor text, p_next_cursor text, p_detail jsonb DEFAULT '{}'::jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_job     public.yorisou_account_deletion_jobs%rowtype;
  v_from    integer;
  v_to      integer;
  v_gate    public.yorisou_account_mutation_gates%rowtype;
  v_active  integer;
  v_crossing boolean;
  v_state   text;
begin
  v_job := public.yorisou_account_deletion_require_executor(p_owner_account_id, p_token_hash, p_generation);

  if v_job.execution_cursor is distinct from p_expected_cursor then
    raise exception 'account_deletion_cursor_mismatch_expected_%_actual_%',
      p_expected_cursor, coalesce(v_job.execution_cursor, 'null');
  end if;

  v_from := public.yorisou_account_deletion_stage_rank(p_expected_cursor);
  v_to   := public.yorisou_account_deletion_stage_rank(p_next_cursor);
  if v_from is null or v_to is null then
    raise exception 'account_deletion_unknown_stage';
  end if;
  -- Exactly one forward. A skip would mark work done that never ran; a backward move would replay a
  -- stage that has already written — which is how an erased identity came back.
  if v_to <> v_from + 1 then
    raise exception 'account_deletion_illegal_cursor_%_to_%', p_expected_cursor, p_next_cursor;
  end if;

  v_crossing := v_to >= public.yorisou_account_deletion_irreversible_rank();

  -- THE MUTATION-LEASE INVARIANT. Anything at or past the crossing requires a gate that is closed
  -- with nothing outstanding — re-checked at EVERY step, not just at the crossing, because a lease
  -- taken after the close would otherwise sit unnoticed alongside a running erasure.
  if v_crossing then
    select * into v_gate from public.yorisou_account_mutation_gates
     where owner_account_id = p_owner_account_id;
    if not found or v_gate.gate_state not in ('closed','completed') then
      raise exception 'account_deletion_gate_not_closed';
    end if;
    select count(*) into v_active from public.yorisou_account_mutation_leases
     where owner_account_id = p_owner_account_id
       and released_at is null and drained_at is null;
    if v_active > 0 then
      raise exception 'account_deletion_gate_not_drained_%', v_active;
    end if;
  end if;

  -- The crossing itself also demands the manifest, because every stage after it depends on one.
  if v_to = public.yorisou_account_deletion_irreversible_rank() then
    if not exists (select 1 from public.yorisou_account_deletion_manifests where job_id = v_job.id) then
      raise exception 'account_deletion_manifest_missing';
    end if;
  end if;

  v_state := public.yorisou_account_deletion_state_for_cursor(p_next_cursor);

  update public.yorisou_account_deletion_jobs
     set execution_cursor = p_next_cursor,
         -- Set ONCE, at the crossing. `coalesce` is the whole guarantee: no later step and no retry
         -- can move it, and nothing can clear it.
         irreversible_started_at = case
           when v_crossing then coalesce(irreversible_started_at, now())
           else irreversible_started_at end,
         state = coalesce(v_state, state),
         locked_at = case when p_next_cursor = 'lock_marker' then coalesce(locked_at, now()) else locked_at end,
         -- A successful step clears the previous attempt's error. The attempt COUNT is kept: it is
         -- the history of the job, not the status of this run.
         last_error_code = null,
         updated_at = now()
   where id = v_job.id
  returning * into v_job;

  insert into public.yorisou_account_deletion_audit (job_id, stage, outcome, detail)
  values (v_job.id, p_next_cursor, 'ok',
          jsonb_build_object('from', p_expected_cursor, 'generation', p_generation)
          || coalesce(p_detail, '{}'::jsonb));

  return jsonb_build_object(
    'cursor', v_job.execution_cursor,
    'state', v_job.state,
    'irreversible', v_job.irreversible_started_at is not null
  );
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_complete_step(p_owner_account_id text, p_token_hash text, p_generation integer, p_expected_cursor text, p_next_cursor text, p_detail jsonb) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_complete_step(p_owner_account_id text, p_token_hash text, p_generation integer, p_expected_cursor text, p_next_cursor text, p_detail jsonb) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_complete_step(p_owner_account_id text, p_token_hash text, p_generation integer, p_expected_cursor text, p_next_cursor text, p_detail jsonb) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_complete_step(p_owner_account_id text, p_token_hash text, p_generation integer, p_expected_cursor text, p_next_cursor text, p_detail jsonb) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_close_mutation_gate(p_owner_account_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_gate public.yorisou_account_mutation_gates%rowtype; v_active integer;
begin
  insert into public.yorisou_account_mutation_gates (owner_account_id)
  values (p_owner_account_id)
  on conflict (owner_account_id) do nothing;

  select * into v_gate from public.yorisou_account_mutation_gates
   where owner_account_id = p_owner_account_id for update;

  if v_gate.gate_state = 'open' then
    update public.yorisou_account_mutation_gates
       set gate_state = 'draining', generation = generation + 1, updated_at = now()
     where owner_account_id = p_owner_account_id
    returning * into v_gate;
  end if;

  -- Abandon only what cannot still be executing: expired PLUS the execution grace.
  update public.yorisou_account_mutation_leases
     set drained_at = now()
   where owner_account_id = p_owner_account_id
     and released_at is null
     and drained_at is null
     and expires_at + public.yorisou_account_mutation_execution_grace() < now();

  select count(*) into v_active from public.yorisou_account_mutation_leases
   where owner_account_id = p_owner_account_id
     and released_at is null
     and drained_at is null;

  if v_active = 0 and v_gate.gate_state = 'draining' then
    update public.yorisou_account_mutation_gates
       set gate_state = 'closed', closed_at = now(), updated_at = now()
     where owner_account_id = p_owner_account_id
    returning * into v_gate;
  end if;

  return jsonb_build_object(
    'gateState', v_gate.gate_state,
    'generation', v_gate.generation,
    'activeLeases', v_active,
    'drained', v_active = 0 and v_gate.gate_state = 'closed'
  );
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_close_mutation_gate(p_owner_account_id text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_close_mutation_gate(p_owner_account_id text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_close_mutation_gate(p_owner_account_id text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_close_mutation_gate(p_owner_account_id text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_advance(p_owner_account_id text, p_to text, p_error_code text DEFAULT NULL::text)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_id uuid; v_from text; v_cursor text; v_irreversible timestamptz; v_ok boolean;
begin
  select id, state, execution_cursor, irreversible_started_at
    into v_id, v_from, v_cursor, v_irreversible
    from public.yorisou_account_deletion_jobs
   where owner_account_id = p_owner_account_id
   for update;
  if not found then raise exception 'account_deletion_job_not_found'; end if;

  -- The engine owns forward motion. Anything else is a bypass, and a bypass is how the invariants
  -- above become decorative.
  if v_cursor is not null
     and p_to not in ('failed_retryable','failed_terminal','cancelled','legal_hold') then
    raise exception 'account_deletion_advance_superseded_by_cursor';
  end if;

  if p_to = 'cancelled' and v_irreversible is not null then
    raise exception 'account_deletion_irreversible';
  end if;

  v_ok := case
    when p_to = 'identity_verified' then v_from in ('requested','failed_retryable')
    when p_to = 'locked'            then v_from in ('identity_verified','failed_retryable')
    when p_to = 'database_erasure'  then v_from in ('locked','failed_retryable','database_erasure')
    when p_to = 'storage_erasure'   then v_from in ('database_erasure','failed_retryable','storage_erasure')
    when p_to = 'identity_erasure'  then v_from in ('storage_erasure','failed_retryable','identity_erasure')
    when p_to = 'verifying'         then v_from in ('identity_erasure','failed_retryable','verifying')
    when p_to = 'failed_retryable'  then v_from not in ('completed','cancelled','failed_terminal','legal_hold')
    when p_to = 'failed_terminal'   then v_from not in ('completed','cancelled')
    when p_to = 'cancelled'         then v_from in ('requested','identity_verified')
    when p_to = 'legal_hold'        then v_from in ('requested','identity_verified','locked')
    else false
  end;

  if not v_ok then
    raise exception 'account_deletion_illegal_transition_%_to_%', v_from, p_to;
  end if;

  update public.yorisou_account_deletion_jobs
     set state           = p_to,
         verified_at     = case when p_to='identity_verified' then now() else verified_at end,
         locked_at       = case when p_to='locked'            then now() else locked_at   end,
         cancelled_at    = case when p_to='cancelled'         then now() else cancelled_at end,
         -- Reaching `identity_verified` is the moment the engine takes over, so the cursor is
         -- initialised here rather than on first claim. A job with a cursor is a job the engine owns.
         execution_cursor = case
           when p_to = 'identity_verified' then coalesce(execution_cursor, 'mutation_draining')
           else execution_cursor end,
         last_error_code = case when p_to like 'failed%' then left(coalesce(p_error_code,'unknown'), 80) else null end,
         attempt_count   = case when p_to like 'failed%' then attempt_count + 1 else attempt_count end,
         updated_at      = now()
   where id = v_id;

  insert into public.yorisou_account_deletion_audit (job_id, stage, outcome, detail)
  values (v_id, p_to, case when p_to like 'failed%' then 'failed' else 'ok' end,
          jsonb_build_object('from', v_from));
  return p_to;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_advance(p_owner_account_id text, p_to text, p_error_code text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_advance(p_owner_account_id text, p_to text, p_error_code text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_advance(p_owner_account_id text, p_to text, p_error_code text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_advance(p_owner_account_id text, p_to text, p_error_code text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_terminal_deidentify(p_owner_account_id text, p_reason text DEFAULT 'manifest_missing_pre_irreversible'::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_job public.yorisou_account_deletion_jobs%rowtype;
  v_now timestamptz := now();
  v_has_manifest boolean;
  v_claim_live boolean;
begin
  if p_owner_account_id is null or char_length(p_owner_account_id) = 0 then
    raise exception 'account_deletion_owner_required';
  end if;

  select * into v_job from public.yorisou_account_deletion_jobs
   where owner_account_id = p_owner_account_id
   for update;

  if not found then
    -- Idempotent: a job already de-identified no longer carries the id, so there is nothing to find
    -- and nothing to do. Reporting this as an error would make a safe repeat look like a fault.
    return jsonb_build_object('deidentified', false, 'outcome', 'absent_or_already_deidentified');
  end if;

  -- ── ELIGIBILITY. Every clause refuses a DIFFERENT way of getting this wrong. ──

  -- Only a terminal failure. A completed job has its own de-identification; anything live is work
  -- in progress and must keep the id every operation looks it up by.
  if v_job.state is distinct from 'failed_terminal' then
    raise exception 'terminal_deidentify_refused_state_%', v_job.state;
  end if;

  -- NOTHING MAY HAVE BEEN DESTROYED. Past the crossing, the job is the only record of what was
  -- erased and for whom; minimising it there would destroy the audit trail of a real deletion.
  if v_job.irreversible_started_at is not null then
    raise exception 'terminal_deidentify_refused_irreversible';
  end if;

  -- The cursor is the second, independent witness to the same question. `irreversible_started_at`
  -- is the recorded fact; a cursor at or past the crossing would contradict it, and a contradiction
  -- is not something to resolve in favour of deleting identity.
  if v_job.execution_cursor is not null
     and public.yorisou_account_deletion_stage_rank(v_job.execution_cursor)
         >= public.yorisou_account_deletion_irreversible_rank() then
    raise exception 'terminal_deidentify_refused_cursor_%', v_job.execution_cursor;
  end if;

  -- A frozen manifest means the job CAN still be resumed, so it must be — resuming is strictly
  -- better than minimising a failure that did not have to be final.
  select exists (select 1 from public.yorisou_account_deletion_manifests where job_id = v_job.id)
    into v_has_manifest;
  if v_has_manifest then
    raise exception 'terminal_deidentify_refused_manifest_present';
  end if;

  -- Someone may be driving it right now.
  v_claim_live := v_job.executor_token_hash is not null
                  and v_job.executor_expires_at is not null
                  and v_job.executor_expires_at > v_now;
  if v_claim_live then
    raise exception 'terminal_deidentify_refused_executor_held';
  end if;

  if p_reason is distinct from 'manifest_missing_pre_irreversible' then
    raise exception 'terminal_deidentify_refused_reason_%', coalesce(p_reason, 'null');
  end if;

  -- ── THE MINIMISATION ────────────────────────────────────────────────────────
  --
  -- The fingerprint stays: it is one-way, it is what the replay and authentication checks already
  -- consult, and it lets this failure still be recognised without naming anyone. `last_error_code`
  -- stays because a failure record that cannot say why it failed is not an audit record.
  update public.yorisou_account_deletion_jobs
     set owner_account_id = null,
         executor_token_hash = null,
         executor_expires_at = null,
         terminal_deidentified_at = v_now,
         terminal_deidentification_reason = p_reason,
         updated_at = v_now
   where id = v_job.id;

  insert into public.yorisou_account_deletion_audit (job_id, stage, outcome, detail)
  values (v_job.id, 'terminal_deidentified', 'ok',
          jsonb_build_object('reason', p_reason, 'from_state', v_job.state));

  return jsonb_build_object('deidentified', true, 'outcome', 'terminal_deidentified');
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_terminal_deidentify(p_owner_account_id text, p_reason text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_terminal_deidentify(p_owner_account_id text, p_reason text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_terminal_deidentify(p_owner_account_id text, p_reason text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_terminal_deidentify(p_owner_account_id text, p_reason text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_status(p_owner_account_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v jsonb;
begin
  select jsonb_build_object('state', state, 'requestedAt', requested_at, 'attemptCount', attempt_count,
                            'lastErrorCode', last_error_code, 'contractVersion', contract_version)
    into v from public.yorisou_account_deletion_jobs where owner_account_id = p_owner_account_id;
  if v is null then
    -- A completed job no longer carries the id; the fingerprint proves the deletion happened.
    select jsonb_build_object('state', state, 'completedAt', completed_at, 'contractVersion', contract_version)
      into v from public.yorisou_account_deletion_jobs
     where owner_fingerprint = public.yorisou_account_deletion_fingerprint(p_owner_account_id)
       and state = 'completed' limit 1;
  end if;
  return coalesce(v, jsonb_build_object('state', 'none'));
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_status(p_owner_account_id text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_status(p_owner_account_id text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_status(p_owner_account_id text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_status(p_owner_account_id text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_open(p_owner_account_id text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_id uuid; v_state text;
begin
  if p_owner_account_id is null or char_length(p_owner_account_id) = 0 then
    raise exception 'account_deletion_owner_required';
  end if;

  select id, state into v_id, v_state
    from public.yorisou_account_deletion_jobs
   where owner_account_id = p_owner_account_id
   for update;

  if found then
    if v_state = 'legal_hold'      then raise exception 'account_deletion_legal_hold'; end if;
    if v_state = 'failed_terminal' then raise exception 'account_deletion_failed_terminal'; end if;
    -- A cancelled job may be reopened; anything else in flight is simply returned.
    if v_state = 'cancelled' then
      update public.yorisou_account_deletion_jobs
         set state='requested', cancelled_at=null, last_error_code=null, updated_at=now()
       where id = v_id;
    end if;
    return v_id;
  end if;

  begin
    insert into public.yorisou_account_deletion_jobs (owner_account_id, owner_fingerprint)
    values (p_owner_account_id, public.yorisou_account_deletion_fingerprint(p_owner_account_id))
    returning id into v_id;

    insert into public.yorisou_account_deletion_audit (job_id, stage, outcome)
    values (v_id, 'requested', 'ok');
    return v_id;
  exception when unique_violation then
    -- The index serialized us. Re-read under a lock: by now the winner has committed, so this is a
    -- genuine read of their row and not a second guess at the race.
    select id, state into v_id, v_state
      from public.yorisou_account_deletion_jobs
     where owner_account_id = p_owner_account_id
     for update;

    if not found then
      -- A unique violation with no surviving row means the winner's transaction rolled back after
      -- claiming the key. Nothing can be returned honestly, and inventing a job would be worse.
      raise exception 'account_deletion_open_lost_race';
    end if;

    -- The refusals are not skipped just because we arrived here the hard way.
    if v_state = 'legal_hold'      then raise exception 'account_deletion_legal_hold'; end if;
    if v_state = 'failed_terminal' then raise exception 'account_deletion_failed_terminal'; end if;
    if v_state = 'cancelled' then
      update public.yorisou_account_deletion_jobs
         set state='requested', cancelled_at=null, last_error_code=null, updated_at=now()
       where id = v_id;
    end if;

    -- No second audit row. The winner already recorded `requested`; a duplicate would read as two
    -- people asking to be deleted.
    return v_id;
  end;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_open(p_owner_account_id text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_open(p_owner_account_id text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_open(p_owner_account_id text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_open(p_owner_account_id text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_manifest_for_owner(p_owner_account_id text)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select m.payload
    from public.yorisou_account_deletion_manifests m
    join public.yorisou_account_deletion_jobs j on j.id = m.job_id
   where j.owner_account_id = p_owner_account_id
      or j.owner_fingerprint = public.yorisou_account_deletion_fingerprint(p_owner_account_id)
   limit 1;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_manifest_for_owner(p_owner_account_id text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_manifest_for_owner(p_owner_account_id text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_manifest_for_owner(p_owner_account_id text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_manifest_for_owner(p_owner_account_id text) to service_role';
  end if;
end $$;
