-- Capability Package 6: governed, finite recommendation graph.
create table public.yorisou_resource_sources (
 id uuid primary key default gen_random_uuid(), project_id text not null default 'yorisou' check(project_id='yorisou'), name text not null check(char_length(name) between 1 and 160), owner_name text not null check(char_length(owner_name) between 1 and 160), domain text, source_type text not null check(source_type in ('yorisou','public','organic_external','editorial')), commercial_status text not null check(commercial_status in ('yorisou_owned','public_resource','organic_external','partner','affiliate','sponsored','unknown_review')), verification_status text not null default 'editorial_seed' check(verification_status in ('editorial_seed','url_checked','metadata_checked','reviewed','disabled')), last_verified_at timestamptz, lifecycle_status text not null default 'active' check(lifecycle_status in ('active','pending_review','disabled','expired')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(project_id,name)
);
create table public.yorisou_resources (
 id uuid primary key default gen_random_uuid(), project_id text not null default 'yorisou' check(project_id='yorisou'), source_id uuid not null references public.yorisou_resource_sources(id), title text not null check(char_length(title) between 1 and 200), description text not null check(char_length(description) between 1 and 1600), resource_type text not null check(resource_type in ('yorisou_guidance','experience_card','small_action','public_resource','book','article','podcast','video','tool','local_activity')), source_url text, internal_route text, language text not null default 'ja' check(language='ja'), japan_applicable boolean not null default true, cost_category text not null check(cost_category in ('free','library','unknown','paid')), commercial_status text not null check(commercial_status in ('yorisou_owned','public_resource','organic_external','partner','affiliate','sponsored','unknown_review')), state_tags text[] not null default '{}', social_intensity text not null default 'low' check(social_intensity in ('low','medium','high')), effort_level text not null default 'small' check(effort_level in ('small','medium','large')), risk_level text not null default 'low' check(risk_level in ('low','medium','high')), limitations text not null check(char_length(limitations) between 1 and 1000), provenance text not null check(char_length(provenance) between 1 and 1000), verification_status text not null default 'editorial_seed' check(verification_status in ('editorial_seed','url_checked','metadata_checked','reviewed','disabled')), last_verified_at timestamptz, expires_at timestamptz, lifecycle_status text not null default 'active' check(lifecycle_status in ('active','pending_review','disabled','expired')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(project_id,title)
);
create table public.yorisou_recommendation_sets (
 id uuid primary key default gen_random_uuid(), project_id text not null default 'yorisou' check(project_id='yorisou'), owner_account_id text not null, request_key text not null check(char_length(request_key) between 16 and 200), request_context jsonb not null default '{}'::jsonb check(octet_length(request_context::text)<=8000), inputs_used jsonb not null default '{}'::jsonb check(octet_length(inputs_used::text)<=8000), excluded_inputs jsonb not null default '[]'::jsonb, policy_version text not null default 'recommendation-graph-v1', provider text, model text, estimated_cost_cents integer not null default 0 check(estimated_cost_cents between 0 and 100), status text not null default 'completed' check(status in ('completed','failed','withdrawn')), created_at timestamptz not null default now(), unique(owner_account_id,request_key)
);
create table public.yorisou_recommendation_items (
 id uuid primary key default gen_random_uuid(), project_id text not null default 'yorisou' check(project_id='yorisou'), recommendation_set_id uuid not null references public.yorisou_recommendation_sets(id) on delete cascade, resource_id uuid references public.yorisou_resources(id) on delete set null, experience_id uuid references public.yorisou_experience_cards(id) on delete set null, rank smallint not null check(rank between 1 and 5), object_type text not null check(object_type in ('resource','experience_card','small_action')), reason text not null check(char_length(reason) between 1 and 800), disclosure text not null check(char_length(disclosure) between 1 and 500), ranking_factors jsonb not null default '{}'::jsonb, lifecycle_status text not null default 'active' check(lifecycle_status in ('active','withdrawn','suppressed')), created_at timestamptz not null default now(), unique(recommendation_set_id,rank), check((resource_id is not null)::int + (experience_id is not null)::int = 1)
);
create table public.yorisou_recommendation_actions (
 id uuid primary key default gen_random_uuid(), project_id text not null default 'yorisou' check(project_id='yorisou'), owner_account_id text not null, recommendation_item_id uuid not null references public.yorisou_recommendation_items(id) on delete cascade, action text not null check(action in ('viewed','reason_viewed','saved','try_intent','tried','helpful','not_helpful','not_relevant','hidden','reported','resource_opened')), idempotency_key text not null check(char_length(idempotency_key) between 16 and 200), note text check(note is null or char_length(note)<=1000), created_at timestamptz not null default now(), unique(owner_account_id,idempotency_key)
);
create table public.yorisou_recommendation_reports (id uuid primary key default gen_random_uuid(), project_id text not null default 'yorisou' check(project_id='yorisou'), owner_account_id text not null, recommendation_item_id uuid not null references public.yorisou_recommendation_items(id) on delete cascade, reason text not null check(reason in ('unsafe','misleading','stale','unavailable','undisclosed_commercial','other')), created_at timestamptz not null default now(), unique(owner_account_id,recommendation_item_id));
create table public.yorisou_recommendation_returns (id uuid primary key default gen_random_uuid(), project_id text not null default 'yorisou' check(project_id='yorisou'), owner_account_id text not null, recommendation_set_id uuid references public.yorisou_recommendation_sets(id) on delete set null, next_check_in_at timestamptz, return_path text not null default '/recommendations' check(return_path ~ '^/(recommendations|private-state|saved|experiences)(/|$)'), status text not null default 'active' check(status in ('active','completed','cancelled')), created_at timestamptz not null default now());
create table public.yorisou_recommendation_events (id uuid primary key default gen_random_uuid(), project_id text not null default 'yorisou' check(project_id='yorisou'), owner_account_id text not null, recommendation_set_id uuid references public.yorisou_recommendation_sets(id) on delete cascade, recommendation_item_id uuid references public.yorisou_recommendation_items(id) on delete cascade, event_type text not null check(event_type in ('recommendation_requested','recommendation_set_created','recommendation_viewed','recommendation_reason_viewed','recommendation_saved','recommendation_try_intent','recommendation_tried','recommendation_helpful','recommendation_not_relevant','recommendation_hidden','recommendation_reported','resource_viewed','resource_opened','resource_unavailable_reported','state_refresh_started','state_refresh_completed','outcome_review_completed','return_visit')), metadata jsonb not null default '{}'::jsonb check(octet_length(metadata::text)<=4000), created_at timestamptz not null default now());
create index yorisou_resources_active_idx on public.yorisou_resources(project_id,lifecycle_status,last_verified_at desc);
create index yorisou_recommendation_sets_owner_idx on public.yorisou_recommendation_sets(owner_account_id,created_at desc);
create index yorisou_recommendation_actions_owner_idx on public.yorisou_recommendation_actions(owner_account_id,created_at desc);
alter table public.yorisou_resource_sources enable row level security; alter table public.yorisou_resources enable row level security; alter table public.yorisou_recommendation_sets enable row level security; alter table public.yorisou_recommendation_items enable row level security; alter table public.yorisou_recommendation_actions enable row level security; alter table public.yorisou_recommendation_reports enable row level security; alter table public.yorisou_recommendation_returns enable row level security; alter table public.yorisou_recommendation_events enable row level security;
revoke all on table public.yorisou_resource_sources,public.yorisou_resources,public.yorisou_recommendation_sets,public.yorisou_recommendation_items,public.yorisou_recommendation_actions,public.yorisou_recommendation_reports,public.yorisou_recommendation_returns,public.yorisou_recommendation_events from public;
create function public.record_yorisou_recommendation_action(p_item_id uuid,p_owner text,p_action text,p_idempotency_key text,p_note text default null) returns uuid language plpgsql security definer set search_path=public as $$ declare v_id uuid; begin if p_owner !~ '^[A-Za-z0-9._:-]{1,200}$' or p_action not in ('viewed','reason_viewed','saved','try_intent','tried','helpful','not_helpful','not_relevant','hidden','reported','resource_opened') or char_length(p_idempotency_key) not between 16 and 200 then raise exception 'invalid recommendation action'; end if; if (select count(*) from public.yorisou_recommendation_actions where owner_account_id=p_owner and created_at>now()-interval '1 hour')>=60 then raise exception 'recommendation action rate limited'; end if; insert into public.yorisou_recommendation_actions(project_id,owner_account_id,recommendation_item_id,action,idempotency_key,note) values('yorisou',p_owner,p_item_id,p_action,p_idempotency_key,p_note) on conflict(owner_account_id,idempotency_key) do update set idempotency_key=excluded.idempotency_key returning id into v_id; return v_id; end $$;
revoke all on function public.record_yorisou_recommendation_action(uuid,text,text,text,text) from public; do $$ begin if exists(select 1 from pg_roles where rolname='anon') then execute 'revoke all on function public.record_yorisou_recommendation_action(uuid,text,text,text,text) from anon'; end if; if exists(select 1 from pg_roles where rolname='authenticated') then execute 'revoke all on function public.record_yorisou_recommendation_action(uuid,text,text,text,text) from authenticated'; end if; end $$; grant execute on function public.record_yorisou_recommendation_action(uuid,text,text,text,text) to service_role;
insert into public.yorisou_resource_sources(name,owner_name,domain,source_type,commercial_status,verification_status,last_verified_at) values
 ('YORISOU','YORISOU',null,'yorisou','yorisou_owned','reviewed',now()),('厚生労働省','厚生労働省','mhlw.go.jp','public','public_resource','url_checked',now()),('国立国会図書館','国立国会図書館','ndl.go.jp','public','public_resource','url_checked',now()) on conflict(project_id,name) do nothing;
insert into public.yorisou_resources(source_id,title,description,resource_type,internal_route,cost_category,commercial_status,state_tags,social_intensity,effort_level,risk_level,limitations,provenance,verification_status,last_verified_at) select id,'3分だけ、次にすることを一つ書く','今の状態を変えようとせず、次に試すことを一つだけ書き出す小さな行動です。','small_action','/private-state','free','yorisou_owned',array['整える','疲れ','迷い'],'low','small','low','急ぎの判断や専門的な支援が必要なときの代わりにはなりません。','YORISOU編集部の小さな行動テンプレート','reviewed',now() from public.yorisou_resource_sources where name='YORISOU' on conflict(project_id,title) do nothing;
insert into public.yorisou_resources(source_id,title,description,resource_type,source_url,cost_category,commercial_status,state_tags,social_intensity,effort_level,risk_level,limitations,provenance,verification_status,last_verified_at) select id,'こころの健康相談統一ダイヤル','公的な相談先を探すための案内です。必要なときは公式情報で現在の案内を確認してください。','public_resource','https://www.mhlw.go.jp/kokoro/','free','public_resource',array['相談','休む','整える'],'medium','small','medium','地域や時間帯で利用条件が異なります。専門的な助言そのものではありません。','厚生労働省の公開ページ（URL確認）','url_checked',now() from public.yorisou_resource_sources where name='厚生労働省' on conflict(project_id,title) do nothing;
