-- POR-1 PROMOTION P5 — Account mutation gates and leases
--
-- PRODUCTION_LINEAGE. Generated by scripts/por1/compile-promotion.mjs from the FINAL Preview
-- catalogue — not from the 24-migration Preview history. Only the last definition of a
-- `create or replace` chain is live, so promoting the history would promote bodies that were
-- already replaced, including the ones replaced because they were wrong.
--
-- Regenerate and verify with:  npm run por1:promotion-check
--
-- CONTENTS
--   tables 2 · sequences 0 · functions 3 · triggers 0
--
-- APPLY SEMANTICS
--   Every statement is guarded (`if not exists` / catalogue probe), so a partial failure can be
--   retried without a human reconstructing which half applied.
--
-- ROLLBACK CLASS
--   SCHEMA_REVERSIBLE_WHILE_FLAGS_OFF — additive only. Nothing here alters or drops an existing
--   Production object, so with the POR-1 capability controls unset these objects are inert: the
--   old application never names them. The Production incident response is to disable the
--   capability and roll back the application, NOT to drop the schema.
--
-- EXISTING-DATA IMPACT
--   None. No backfill, no column change to a populated table, no data movement.
--
-- LOCK CLASS
--   CREATE TABLE / CREATE INDEX on brand-new empty relations. No lock is taken on any table the
--   running application reads or writes.


-- ── tables ─────────────────────────────────────────────────────────────────

-- yorisou_account_mutation_gates

create table if not exists public.yorisou_account_mutation_gates (
  owner_account_id text not null,
  gate_state text default 'open'::text not null,
  generation integer default 1 not null,
  owner_fingerprint text,
  closed_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_mutation_gates_gate_state_check' and conrelid = 'public.yorisou_account_mutation_gates'::regclass) then
    alter table public.yorisou_account_mutation_gates add constraint yorisou_account_mutation_gates_gate_state_check CHECK ((gate_state = ANY (ARRAY['open'::text, 'draining'::text, 'closed'::text, 'completed'::text])));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_mutation_gates_generation_check' and conrelid = 'public.yorisou_account_mutation_gates'::regclass) then
    alter table public.yorisou_account_mutation_gates add constraint yorisou_account_mutation_gates_generation_check CHECK ((generation > 0));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_mutation_gates_pkey' and conrelid = 'public.yorisou_account_mutation_gates'::regclass) then
    alter table public.yorisou_account_mutation_gates add constraint yorisou_account_mutation_gates_pkey PRIMARY KEY (owner_account_id);
  end if;
end $$;

create index if not exists yorisou_account_mutation_gates_state_idx ON public.yorisou_account_mutation_gates USING btree (gate_state);

alter table public.yorisou_account_mutation_gates enable row level security;

alter table public.yorisou_account_mutation_gates force row level security;

revoke all on table public.yorisou_account_mutation_gates from public;
do $$ begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on table public.yorisou_account_mutation_gates from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on table public.yorisou_account_mutation_gates from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant delete, insert, references, select, trigger, truncate, update on table public.yorisou_account_mutation_gates to service_role';
  end if;
end $$;

-- yorisou_account_mutation_leases

create table if not exists public.yorisou_account_mutation_leases (
  id uuid default gen_random_uuid() not null,
  owner_account_id text not null,
  gate_generation integer not null,
  operation_code text not null,
  request_nonce_hash text,
  issued_at timestamp with time zone default now() not null,
  expires_at timestamp with time zone not null,
  released_at timestamp with time zone,
  drained_at timestamp with time zone
);

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_mutation_leases_operation_code_check' and conrelid = 'public.yorisou_account_mutation_leases'::regclass) then
    alter table public.yorisou_account_mutation_leases add constraint yorisou_account_mutation_leases_operation_code_check CHECK ((operation_code = ANY (ARRAY['support_profile_update'::text, 'password_update'::text, 'line_binding'::text, 'account_profile_update'::text, 'identity_mirror_sync'::text, 'session_identity_upgrade'::text, 'account_recovery'::text, 'account_registration'::text, 'line_primary_provisioning'::text, 'password_reset_issue'::text, 'session_account_binding'::text, 'foundation_profile_update'::text, 'foundation_identity_binding'::text])));
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'yorisou_account_mutation_leases_pkey' and conrelid = 'public.yorisou_account_mutation_leases'::regclass) then
    alter table public.yorisou_account_mutation_leases add constraint yorisou_account_mutation_leases_pkey PRIMARY KEY (id);
  end if;
end $$;

create index if not exists yorisou_account_mutation_leases_active_idx ON public.yorisou_account_mutation_leases USING btree (owner_account_id) WHERE ((released_at IS NULL) AND (drained_at IS NULL));

alter table public.yorisou_account_mutation_leases enable row level security;

alter table public.yorisou_account_mutation_leases force row level security;

revoke all on table public.yorisou_account_mutation_leases from public;
do $$ begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on table public.yorisou_account_mutation_leases from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on table public.yorisou_account_mutation_leases from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant delete, insert, references, select, trigger, truncate, update on table public.yorisou_account_mutation_leases to service_role';
  end if;
end $$;

-- ── functions ──────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.yorisou_account_mutation_release(p_lease_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  update public.yorisou_account_mutation_leases
     set released_at = coalesce(released_at, now())
   where id = p_lease_id;
  return found;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_mutation_release(p_lease_id uuid) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_mutation_release(p_lease_id uuid) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_mutation_release(p_lease_id uuid) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_mutation_release(p_lease_id uuid) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_mutation_execution_grace()
 RETURNS interval
 LANGUAGE sql
 IMMUTABLE
AS $function$ select interval '180 seconds' $function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_mutation_execution_grace() from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_mutation_execution_grace() from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_mutation_execution_grace() from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_mutation_execution_grace() to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_mutation_clock()
 RETURNS timestamp with time zone
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare v_raw text; v_skew interval;
begin
  v_raw := current_setting('yorisou.deletion_clock_skew_seconds', true);
  if v_raw is null or v_raw = '' then return now(); end if;
  v_skew := make_interval(secs => least(greatest(v_raw::numeric, 0), 86400));
  return now() + v_skew;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_mutation_clock() from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_mutation_clock() from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_mutation_clock() from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_mutation_clock() to service_role';
  end if;
end $$;
