-- POR-1 PROMOTION P7 — Cross-domain functions — created after every promoted table exists
--
-- PRODUCTION_LINEAGE. Generated by scripts/por1/compile-promotion.mjs from the FINAL Preview
-- catalogue — not from the 24-migration Preview history. Only the last definition of a
-- `create or replace` chain is live, so promoting the history would promote bodies that were
-- already replaced, including the ones replaced because they were wrong.
--
-- Regenerate and verify with:  npm run por1:promotion-check
--
-- CONTENTS
--   tables 0 · sequences 0 · functions 4 · triggers 0
--
-- APPLY SEMANTICS
--   Every statement is guarded (`if not exists` / catalogue probe), so a partial failure can be
--   retried without a human reconstructing which half applied.
--
-- ROLLBACK CLASS
--   SCHEMA_REVERSIBLE_WHILE_FLAGS_OFF — additive only. Nothing here alters or drops an existing
--   Production object, so with the POR-1 capability controls unset these objects are inert: the
--   old application never names them. The Production incident response is to disable the
--   capability and roll back the application, NOT to drop the schema.
--
-- EXISTING-DATA IMPACT
--   None. No backfill, no column change to a populated table, no data movement.
--
-- LOCK CLASS
--   CREATE TABLE / CREATE INDEX on brand-new empty relations. No lock is taken on any table the
--   running application reads or writes.


-- ── functions ──────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.yorisou_assessment_result_erase(p_result_row_id uuid, p_owner_account_id text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_attempt uuid; v_rows integer;
begin
  select attempt_id into v_attempt from public.yorisou_assessment_results
   where id = p_result_row_id and owner_account_id = p_owner_account_id and deleted_at is null;
  if not found then return false; end if;

  -- Recommendation graph first, while the owner linkage still exists to authorize it.
  delete from public.yorisou_canonical_recommendation_actions where result_row_id = p_result_row_id;
  delete from public.yorisou_canonical_recommendation_items  where result_row_id = p_result_row_id;
  delete from public.yorisou_canonical_recommendation_sets   where result_row_id = p_result_row_id;

  -- Interpretation responses carry corrections, reasons and idempotency nonces.
  perform set_config('yorisou.erasure_context', p_result_row_id::text, true);
  delete from public.yorisou_interpretation_responses where result_row_id = p_result_row_id;
  perform set_config('yorisou.erasure_context', '', true);

  update public.yorisou_assessment_results
     set deleted_at            = now(),
         result_id             = null,
         original_result_id    = null,
         overlay_id            = null,
         dimension_output      = '{}'::jsonb,
         owner_account_id      = null,
         scoring_version       = null,
         result_schema_version = null
   where id = p_result_row_id;
  get diagnostics v_rows = row_count;

  update public.yorisou_assessment_attempts
     set answers = '{}'::jsonb, answered_count = 0, claim_token_hash = null,
         status = 'abandoned', completed_at = null, owner_account_id = null, claimed_at = null,
         expires_at = null, updated_at = now()
   where id = v_attempt;

  return v_rows > 0;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_assessment_result_erase(p_result_row_id uuid, p_owner_account_id text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_assessment_result_erase(p_result_row_id uuid, p_owner_account_id text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_assessment_result_erase(p_result_row_id uuid, p_owner_account_id text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_assessment_result_erase(p_result_row_id uuid, p_owner_account_id text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_mutation_gate_finalize(p_owner_account_id text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_fingerprint text;
begin
  v_fingerprint := public.yorisou_account_deletion_fingerprint(p_owner_account_id);
  delete from public.yorisou_account_mutation_leases where owner_account_id = p_owner_account_id;
  update public.yorisou_account_mutation_gates
     set gate_state = 'completed',
         completed_at = now(),
         owner_fingerprint = v_fingerprint,
         owner_account_id = v_fingerprint,
         updated_at = now()
   where owner_account_id = p_owner_account_id;
  return found;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_mutation_gate_finalize(p_owner_account_id text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_mutation_gate_finalize(p_owner_account_id text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_mutation_gate_finalize(p_owner_account_id text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_mutation_gate_finalize(p_owner_account_id text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_mutation_begin(p_owner_account_id text, p_operation_code text, p_ttl_seconds integer DEFAULT 30, p_request_nonce_hash text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_gate  public.yorisou_account_mutation_gates%rowtype;
  v_job   public.yorisou_account_deletion_jobs%rowtype;
  v_lease uuid;
begin
  if p_owner_account_id is null or char_length(p_owner_account_id) = 0 then
    raise exception 'account_mutation_owner_required';
  end if;
  if p_ttl_seconds is null or p_ttl_seconds < 1 or p_ttl_seconds > 120 then
    raise exception 'account_mutation_ttl_out_of_range';
  end if;

  select * into v_job from public.yorisou_account_deletion_jobs
   where owner_account_id = p_owner_account_id
      or owner_fingerprint = public.yorisou_account_deletion_fingerprint(p_owner_account_id)
   limit 1;

  if found then
    if v_job.state = 'completed' then
      raise exception 'account_mutation_denied_deleted';
    end if;
    -- The recorded FACT first — it survives any state string, including `failed_retryable`.
    if v_job.irreversible_started_at is not null then
      raise exception 'account_mutation_denied_erasing';
    end if;
    if v_job.execution_cursor is not null
       and public.yorisou_account_deletion_stage_rank(v_job.execution_cursor)
           >= public.yorisou_account_deletion_irreversible_rank() then
      raise exception 'account_mutation_denied_erasing';
    end if;
    if v_job.state in ('locked','database_erasure','storage_erasure','identity_erasure','verifying') then
      raise exception 'account_mutation_denied_erasing';
    end if;
  end if;

  insert into public.yorisou_account_mutation_gates (owner_account_id)
  values (p_owner_account_id) on conflict (owner_account_id) do nothing;

  select * into v_gate from public.yorisou_account_mutation_gates
   where owner_account_id = p_owner_account_id for update;

  if v_gate.gate_state <> 'open' then
    raise exception 'account_mutation_denied_gate_%', v_gate.gate_state;
  end if;

  insert into public.yorisou_account_mutation_leases
    (owner_account_id, gate_generation, operation_code, request_nonce_hash, expires_at)
  values
    (p_owner_account_id, v_gate.generation, p_operation_code, left(coalesce(p_request_nonce_hash,''), 64),
     now() + make_interval(secs => p_ttl_seconds))
  returning id into v_lease;

  return jsonb_build_object('leaseId', v_lease, 'generation', v_gate.generation);
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_mutation_begin(p_owner_account_id text, p_operation_code text, p_ttl_seconds integer, p_request_nonce_hash text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_mutation_begin(p_owner_account_id text, p_operation_code text, p_ttl_seconds integer, p_request_nonce_hash text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_mutation_begin(p_owner_account_id text, p_operation_code text, p_ttl_seconds integer, p_request_nonce_hash text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_mutation_begin(p_owner_account_id text, p_operation_code text, p_ttl_seconds integer, p_request_nonce_hash text) to service_role';
  end if;
end $$;

CREATE OR REPLACE FUNCTION public.yorisou_account_deletion_erase_database(p_owner_account_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_id       uuid;
  v_plan     text[][] := array[
    -- identity-linked tables, owner column. Legacy AND canonical families both appear: a person's
    -- deletion must not depend on which generation of the product created the row.
    ['yorisou_test_results','owner_account_id'],
    ['yorisou_ai_reflections','owner_account_id'],
    ['yorisou_ai_runs','owner_account_id'],
    ['yorisou_daily_state_history_events','owner_account_id'],
    ['yorisou_daily_state_record_versions','record_id_owner_indirect'],   -- handled via parent below
    ['yorisou_daily_state_records','owner_account_id'],
    ['yorisou_values_assessment_events','owner_account_id'],
    ['yorisou_values_assessment_versions','assessment_id_owner_indirect'],-- handled via parent below
    ['yorisou_values_assessments','owner_account_id'],
    ['yorisou_private_check_in_plans','owner_account_id'],
    ['yorisou_private_memory_items','owner_account_id'],
    ['yorisou_private_recommendations','owner_account_id'],
    ['yorisou_experience_cards','owner_account_id'],
    ['yorisou_experience_consents','owner_account_id'],
    ['yorisou_experience_invites','owner_account_id'],
    ['yorisou_experience_revisions','owner_account_id'],
    ['yorisou_experience_visibility_events','owner_account_id'],
    ['yorisou_experience_events','actor_account_id'],
    ['yorisou_experience_interactions','actor_account_id'],
    ['yorisou_experience_moderation_events','actor_account_id'],
    ['yorisou_experience_reports','reporter_account_id'],
    ['yorisou_experience_blocks','blocker_account_id'],
    ['yorisou_experience_blocks','blocked_owner_account_id'],
    ['yorisou_recommendation_events','owner_account_id'],
    ['yorisou_recommendation_reports','owner_account_id'],
    ['yorisou_recommendation_returns','owner_account_id'],
    ['yorisou_recommendation_actions','owner_account_id'],
    ['yorisou_recommendation_sets','owner_account_id'],
    ['yorisou_canonical_recommendation_actions','owner_account_id'],
    ['yorisou_canonical_recommendation_items','owner_account_id'],
    ['yorisou_canonical_recommendation_sets','owner_account_id'],
    ['yorisou_account_deletion_requests','owner_account_id']
  ];
  v_i        integer;
  v_table    text;
  v_column   text;
  v_count    bigint;
  v_counts   jsonb := '{}'::jsonb;
  v_result   record;
begin
  select id into v_id from public.yorisou_account_deletion_jobs
   where owner_account_id = p_owner_account_id;
  if not found then raise exception 'account_deletion_job_not_found'; end if;

  -- 5.1 Canonical RESULTS go through the governed owner-scoped erasure, which clears the
  --     reconstructable content and leaves the contractual content-free tombstone. Deleting them
  --     outright here would quietly weaken the erasure contract the product publishes.
  if to_regclass('public.yorisou_assessment_results') is not null then
    v_count := 0;
    for v_result in
      select id from public.yorisou_assessment_results
       where owner_account_id = p_owner_account_id and deleted_at is null
    loop
      perform public.yorisou_assessment_result_erase(v_result.id, p_owner_account_id);
      v_count := v_count + 1;
    end loop;
    v_counts := v_counts || jsonb_build_object('yorisou_assessment_results_erased', v_count);
  end if;

  -- 5.2 Attempts hold the raw answers; they are removed, not tombstoned.
  if to_regclass('public.yorisou_assessment_attempts') is not null then
    delete from public.yorisou_assessment_attempts where owner_account_id = p_owner_account_id;
    get diagnostics v_count = row_count;
    v_counts := v_counts || jsonb_build_object('yorisou_assessment_attempts', v_count);
  end if;

  -- 5.3 Child rows whose ownership is only reachable through a parent.
  if to_regclass('public.yorisou_daily_state_record_versions') is not null
     and to_regclass('public.yorisou_daily_state_records') is not null then
    delete from public.yorisou_daily_state_record_versions v
     where exists (select 1 from public.yorisou_daily_state_records r
                    where r.id = v.record_id and r.owner_account_id = p_owner_account_id);
    get diagnostics v_count = row_count;
    v_counts := v_counts || jsonb_build_object('yorisou_daily_state_record_versions', v_count);
  end if;

  if to_regclass('public.yorisou_values_assessment_versions') is not null
     and to_regclass('public.yorisou_values_assessments') is not null then
    delete from public.yorisou_values_assessment_versions v
     where exists (select 1 from public.yorisou_values_assessments a
                    where a.id = v.assessment_id and a.owner_account_id = p_owner_account_id);
    get diagnostics v_count = row_count;
    v_counts := v_counts || jsonb_build_object('yorisou_values_assessment_versions', v_count);
  end if;

  -- 5.4 The declarative plan.
  for v_i in 1 .. array_length(v_plan, 1) loop
    v_table  := v_plan[v_i][1];
    v_column := v_plan[v_i][2];
    if v_column like '%_owner_indirect' then continue; end if;   -- handled above
    if to_regclass('public.' || v_table) is null then
      v_counts := v_counts || jsonb_build_object(v_table, 'absent');
      continue;
    end if;
    if not exists (select 1 from information_schema.columns
                    where table_schema='public' and table_name=v_table and column_name=v_column) then
      v_counts := v_counts || jsonb_build_object(v_table, 'column_absent');
      continue;
    end if;
    execute format('delete from public.%I where %I = $1', v_table, v_column) using p_owner_account_id;
    get diagnostics v_count = row_count;
    v_counts := v_counts || jsonb_build_object(
      case when v_counts ? v_table then v_table || ':' || v_column else v_table end, v_count);
  end loop;

  insert into public.yorisou_account_deletion_audit (job_id, stage, outcome, detail)
  values (v_id, 'database_erasure', 'ok', jsonb_build_object('counts', v_counts));

  return v_counts;
end;
$function$;

do $$ begin
  execute 'revoke all on function public.yorisou_account_deletion_erase_database(p_owner_account_id text) from public';
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on function public.yorisou_account_deletion_erase_database(p_owner_account_id text) from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on function public.yorisou_account_deletion_erase_database(p_owner_account_id text) from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.yorisou_account_deletion_erase_database(p_owner_account_id text) to service_role';
  end if;
end $$;
