import "server-only";
import { YORISOU_PROJECT_ID } from "./governanceResources";

export const taskStates = ["queued", "scheduled", "ready", "claimed", "running", "waiting_for_review", "retry_wait", "completed", "failed", "cancelled", "paused", "dead_letter"] as const;
export type TaskStatus = (typeof taskStates)[number];
export type RuntimeTask = { id: string; project_id: typeof YORISOU_PROJECT_ID; agent_id: string | null; workflow_type: string; skill_id: string | null; status: TaskStatus; priority: number; input_payload: Record<string, unknown>; data_classification: "internal" | "sensitive" | "restricted"; approval_required: boolean; scheduled_at: string | null; available_at: string; claimed_at: string | null; started_at: string | null; completed_at: string | null; failed_at: string | null; cancelled_at: string | null; attempt_count: number; maximum_attempts: number; timeout_seconds: number; retry_policy: Record<string, unknown>; idempotency_key: string; cost_budget_cents: number; error_class: string | null; error_summary: string | null; parent_task_id: string | null; correlation_id: string; created_at: string; updated_at: string; };
export type SkillReference = { skill_id: string; skill_version: string; status: "draft" | "approved" | "active" | "paused" | "retired"; checksum: string; input_schema_reference: string; output_schema_reference: string; allowed_agent_ids: string[]; approval_level: "none" | "required"; timeout_seconds: number; cost_limit_cents: number; };
const legal: Partial<Record<TaskStatus, TaskStatus[]>> = { queued: ["ready", "scheduled", "paused", "cancelled"], scheduled: ["ready", "paused", "cancelled"], ready: ["claimed", "paused", "cancelled"], claimed: ["running", "ready", "paused", "cancelled"], running: ["completed", "waiting_for_review", "retry_wait", "failed", "paused", "cancelled"], waiting_for_review: ["ready", "cancelled", "paused"], retry_wait: ["ready", "failed", "paused", "cancelled"], failed: ["dead_letter"], paused: ["ready", "cancelled"] };
export function assertRuntimeTaskInput(input: Omit<RuntimeTask, "id" | "created_at" | "updated_at" | "status" | "attempt_count" | "claimed_at" | "started_at" | "completed_at" | "failed_at" | "cancelled_at" | "error_class" | "error_summary">) { if (input.project_id !== YORISOU_PROJECT_ID) throw new Error("agent_runtime_project_forbidden"); if (!input.agent_id && !input.workflow_type) throw new Error("agent_runtime_identity_required"); if (JSON.stringify(input.input_payload).length > 65536) throw new Error("agent_runtime_payload_too_large"); if (input.maximum_attempts < 1 || input.maximum_attempts > 10 || input.timeout_seconds < 1 || input.timeout_seconds > 3600) throw new Error("agent_runtime_limits_invalid"); }
export function assertTransition(from: TaskStatus, to: TaskStatus) { if (!legal[from]?.includes(to)) throw new Error(`agent_runtime_invalid_transition:${from}:${to}`); }
export type RuntimeQueueRepository = { createTask(input: Omit<RuntimeTask, "id" | "created_at" | "updated_at" | "status" | "attempt_count" | "claimed_at" | "started_at" | "completed_at" | "failed_at" | "cancelled_at" | "error_class" | "error_summary">): Promise<RuntimeTask>; getTask(id: string): Promise<RuntimeTask | null>; listTasks(input: { status?: TaskStatus; limit: number }): Promise<RuntimeTask[]>; claimNextTask(input: { workerId: string; leaseSeconds: number; batchSize: number }): Promise<RuntimeTask[]>; startTask(input: { taskId: string; actor: string; correlationId: string }): Promise<RuntimeTask>; completeTask(input: { taskId: string; actor: string; summary?: string; correlationId: string }): Promise<RuntimeTask>; failTask(input: { taskId: string; actor: string; errorClass: string; summary: string; correlationId: string }): Promise<RuntimeTask>; scheduleRetry(input: { taskId: string; actor: string; availableAt: string; reason: string; correlationId: string }): Promise<RuntimeTask>; pauseTask(input: { taskId: string; actor: string; reason: string; correlationId: string }): Promise<RuntimeTask>; cancelTask(input: { taskId: string; actor: string; reason: string; correlationId: string }): Promise<RuntimeTask>; createReviewItem(input: { taskId: string; reason: string; requiredApprover: "edward" }): Promise<void>; resolveReviewItem(input: { taskId: string; reviewerId: string; decision: "approve" | "reject" | "request_revision" | "cancel"; reason: string }): Promise<void>; writeArtifactReference(input: { taskId: string; uri: string; sha256: string; classification: string }): Promise<void>; };
